from vp6 import *


class frmCalculator(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Calculator'
        self.Width = 264
        self.Height = 313
        self.BorderStyle = 3
        self.KeyPreview = True
        self.txtDisplay = TextBox(self, Text='0', Left=16, Top=16, Width=232, Height=40,
                                  Alignment=1, Locked=True, FontSize=20)
        self.cmdDigit = ControlArray()
        self.cmdDigit[7] = CommandButton(self, Caption='7', Left=16, Top=72, Width=52, Height=40,
                                         FontSize=14, TabIndex=1)
        self.cmdDigit[8] = CommandButton(self, Caption='8', Left=76, Top=72, Width=52, Height=40,
                                         FontSize=14, TabIndex=2)
        self.cmdDigit[9] = CommandButton(self, Caption='9', Left=136, Top=72, Width=52, Height=40,
                                         FontSize=14, TabIndex=3)
        self.cmdOperator = ControlArray()
        self.cmdOperator[0] = CommandButton(self, Caption='/', Left=196, Top=72, Width=52,
                                            Height=40, FontSize=14, TabIndex=4)
        self.cmdDigit[4] = CommandButton(self, Caption='4', Left=16, Top=120, Width=52, Height=40,
                                         FontSize=14, TabIndex=5)
        self.cmdDigit[5] = CommandButton(self, Caption='5', Left=76, Top=120, Width=52, Height=40,
                                         FontSize=14, TabIndex=6)
        self.cmdDigit[6] = CommandButton(self, Caption='6', Left=136, Top=120, Width=52, Height=40,
                                         FontSize=14, TabIndex=7)
        self.cmdOperator[1] = CommandButton(self, Caption='*', Left=196, Top=120, Width=52,
                                            Height=40, FontSize=14, TabIndex=8)
        self.cmdDigit[1] = CommandButton(self, Caption='1', Left=16, Top=168, Width=52, Height=40,
                                         FontSize=14, TabIndex=9)
        self.cmdDigit[2] = CommandButton(self, Caption='2', Left=76, Top=168, Width=52, Height=40,
                                         FontSize=14, TabIndex=10)
        self.cmdDigit[3] = CommandButton(self, Caption='3', Left=136, Top=168, Width=52, Height=40,
                                         FontSize=14, TabIndex=11)
        self.cmdOperator[2] = CommandButton(self, Caption='-', Left=196, Top=168, Width=52,
                                            Height=40, FontSize=14, TabIndex=12)
        self.cmdDigit[0] = CommandButton(self, Caption='0', Left=16, Top=216, Width=52, Height=40,
                                         FontSize=14, TabIndex=13)
        self.cmdPoint = CommandButton(self, Caption='.', Left=76, Top=216, Width=52, Height=40,
                                      FontSize=14, TabIndex=14)
        self.cmdOperator[4] = CommandButton(self, Caption='=', Left=136, Top=216, Width=52,
                                            Height=40, Default=True, FontSize=14, TabIndex=15)
        self.cmdOperator[3] = CommandButton(self, Caption='+', Left=196, Top=216, Width=52,
                                            Height=40, FontSize=14, TabIndex=16)
        self.cmdClear = CommandButton(self, Caption='C', Left=16, Top=264, Width=232, Height=33,
                                      Cancel=True, TabIndex=17)
    # endregion

    def Form_Load(self):
        self.accumulator = 0.0
        self.pending = None      # the operator waiting for its second operand
        self.fresh = True        # next digit starts a new number

    # cmdDigit and cmdOperator are control arrays: one handler per array, and
    # Index tells which button was clicked (a digit's Index is its value)
    def cmdDigit_Click(self, Index):
        self.press(str(Index))

    def cmdOperator_Click(self, Index):
        self.press(self.cmdOperator[Index].Caption)

    def cmdPoint_Click(self):
        self.press(".")

    def Form_KeyPress(self, KeyAscii):
        key = chr(KeyAscii)
        if key in "0123456789.+-*/=":
            self.press(key)
            return 0

    def press(self, key):
        display = self.txtDisplay
        if key.isdigit() or key == ".":
            if self.fresh:
                display.Text = "0." if key == "." else key
                self.fresh = False
            elif key != "." or "." not in display.Text:
                display.Text += key
            return
        self.calculate()
        self.pending = None if key == "=" else key
        self.fresh = True

    def calculate(self):
        value = float(self.txtDisplay.Text)
        if self.pending is None:
            self.accumulator = value
        elif self.pending == "/" and value == 0:
            MsgBox("Cannot divide by zero.", vpExclamation, "Calculator")
            self.cmdClear_Click()
            return
        else:
            self.accumulator = {
                "+": self.accumulator + value, "-": self.accumulator - value,
                "*": self.accumulator * value, "/": self.accumulator / value,
            }[self.pending]
        self.txtDisplay.Text = f"{self.accumulator:g}"

    def cmdClear_Click(self):
        self.accumulator, self.pending, self.fresh = 0.0, None, True
        self.txtDisplay.Text = "0"


if __name__ == "__main__":
    run(frmCalculator)
