"""Tools > Options: editor theme, colors and font."""

from __future__ import annotations

import copy

from PySide6.QtCore import Qt
from PySide6.QtGui import QColor, QFontDatabase, QIcon, QPixmap
from PySide6.QtWidgets import (
    QCheckBox, QColorDialog, QComboBox, QDialog, QDialogButtonBox, QFormLayout, QGroupBox,
    QHBoxLayout, QHeaderView, QInputDialog, QLabel, QMessageBox, QPushButton, QSpinBox,
    QTableWidget, QTableWidgetItem, QVBoxLayout, QWidget,
)

from .chrome import FRAME_STYLES
from .theme import (BUILTIN_THEMES, DARK, LIGHT, SYNTAX_ROLES, SYSTEM, UI_ROLES, system_is_dark,
                    theme_manager)

PREVIEW = '''from vp6 import *


class Form1(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Preview'
    # endregion

    @property
    def total(self):
        return 42 * 0x10  # a comment

    def Command1_Click(self):
        """Say hello."""
        if MsgBox("Hello, world!", vpYesNo) == vpYes:
            print(len(self.Caption), True, None)
'''


def _swatch(color: str) -> QIcon:
    pixmap = QPixmap(16, 16)
    pixmap.fill(QColor(color))
    return QIcon(pixmap)


class OptionsDialog(QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Options")
        self.manager = theme_manager()
        self.state = copy.deepcopy(self.manager.state)
        self.edit_name = self.manager.current().name
        self._loading = False

        # -- theme selection --------------------------------------------------------------
        self.selection = QComboBox()
        self.system_light = QComboBox()
        self.system_dark = QComboBox()
        self.selection.activated.connect(self._on_selection)
        self.system_light.activated.connect(self._on_system_slots)
        self.system_dark.activated.connect(self._on_system_slots)
        theme_box = QGroupBox("Theme")
        theme_form = QFormLayout(theme_box)
        theme_form.addRow("Editor theme:", self.selection)
        theme_form.addRow("With a light system appearance:", self.system_light)
        theme_form.addRow("With a dark system appearance:", self.system_dark)
        self.system_note = QLabel()
        self.system_note.setStyleSheet("color: gray;")
        theme_form.addRow("", self.system_note)

        # -- colors -----------------------------------------------------------------------
        self.edit_combo = QComboBox()
        self.edit_combo.activated.connect(
            lambda i: self._edit_theme(self.edit_combo.itemText(i)))
        self.new_button = QPushButton("New…")
        self.delete_button = QPushButton("Delete")
        self.reset_button = QPushButton("Reset")
        self.new_button.clicked.connect(self._new_theme)
        self.delete_button.clicked.connect(self._delete_theme)
        self.reset_button.clicked.connect(self._reset_theme)
        edit_row = QHBoxLayout()
        edit_row.addWidget(QLabel("Customize:"))
        edit_row.addWidget(self.edit_combo, 1)
        edit_row.addWidget(self.new_button)
        edit_row.addWidget(self.delete_button)
        edit_row.addWidget(self.reset_button)

        self.table = QTableWidget(0, 4)
        self.table.setHorizontalHeaderLabels(["Element", "Color", "Bold", "Italic"])
        self.table.verticalHeader().hide()
        self.table.setSelectionMode(QTableWidget.NoSelection)
        header = self.table.horizontalHeader()
        header.setSectionResizeMode(0, QHeaderView.Stretch)
        for column in (1, 2, 3):
            header.setSectionResizeMode(column, QHeaderView.ResizeToContents)
        colors_box = QGroupBox("Colors")
        colors_layout = QVBoxLayout(colors_box)
        colors_layout.addLayout(edit_row)
        colors_layout.addWidget(self.table)

        # -- font -------------------------------------------------------------------------
        self.font_family = QComboBox()
        self.font_family.addItem("(Default)", "")
        for family in QFontDatabase.families():
            if QFontDatabase.isFixedPitch(family) and not family.startswith("."):
                self.font_family.addItem(family, family)
        self.font_size = QSpinBox()
        self.font_size.setRange(0, 72)
        self.font_size.setSpecialValueText("(Default)")
        self.font_family.activated.connect(self._on_font)
        self.font_size.valueChanged.connect(self._on_font)
        font_box = QGroupBox("Font")
        font_row = QHBoxLayout(font_box)
        font_row.addWidget(self.font_family, 1)
        font_row.addWidget(QLabel("Size:"))
        font_row.addWidget(self.font_size)

        # -- form designer ----------------------------------------------------------------
        self.frame_style = QComboBox()
        for key, label in FRAME_STYLES.items():
            self.frame_style.addItem(label, key)
        self.frame_style.setToolTip("The window frame drawn around forms in the designer.")
        self.frame_style.activated.connect(self._on_frame_style)
        designer_box = QGroupBox("Form Designer")
        designer_form = QFormLayout(designer_box)
        designer_form.addRow("Window frame:", self.frame_style)
        self.show_grid = QCheckBox("Show grid (controls snap to it either way)")
        self.show_grid.toggled.connect(self._on_show_grid)
        designer_form.addRow("", self.show_grid)

        # -- preview ----------------------------------------------------------------------
        from .codeeditor import CodeEditor
        from .documents import FormDocument

        self.preview_doc = FormDocument("Preview.py", PREVIEW)
        self.preview = CodeEditor(self.preview_doc, follow_theme=False)
        self.preview.region_folded = False
        self.preview.setReadOnly(True)
        preview_box = QGroupBox("Preview")
        QVBoxLayout(preview_box).addWidget(self.preview)

        buttons = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel |
                                   QDialogButtonBox.Apply)
        buttons.accepted.connect(self.accept)
        buttons.rejected.connect(self.reject)
        buttons.button(QDialogButtonBox.Apply).clicked.connect(self.apply)

        left = QVBoxLayout()
        left.addWidget(theme_box)
        left.addWidget(colors_box, 1)
        left.addWidget(font_box)
        left.addWidget(designer_box)
        columns = QHBoxLayout()
        columns.addLayout(left, 3)
        columns.addWidget(preview_box, 4)
        layout = QVBoxLayout(self)
        layout.addLayout(columns)
        layout.addWidget(buttons)
        self.resize(1080, 680)
        self._reload()

    # -- populating ------------------------------------------------------------------------------
    def _reload(self) -> None:
        self._loading = True
        names = list(self.state.themes)
        self.selection.clear()
        self.selection.addItem("System (follow light/dark appearance)", SYSTEM)
        for name in names:
            self.selection.addItem(name, name)
        self.selection.setCurrentIndex(max(self.selection.findData(self.state.selection), 0))
        for combo, value in ((self.system_light, self.state.system_light),
                             (self.system_dark, self.state.system_dark)):
            combo.clear()
            combo.addItems(names)
            combo.setCurrentIndex(max(combo.findText(value), 0))
        system = self.state.selection == SYSTEM
        self.system_light.setEnabled(system)
        self.system_dark.setEnabled(system)
        self.system_note.setText(
            f"The system appearance is currently {'dark' if system_is_dark() else 'light'}.")
        if self.edit_name not in self.state.themes:
            self.edit_name = self.manager.resolve(self.state).name
        self.edit_combo.clear()
        self.edit_combo.addItems(names)
        self.edit_combo.setCurrentIndex(self.edit_combo.findText(self.edit_name))
        self.delete_button.setEnabled(self.edit_name not in BUILTIN_THEMES)
        self.reset_button.setEnabled(self.edit_name in BUILTIN_THEMES)
        self.font_family.setCurrentIndex(max(self.font_family.findData(self.state.font_family),
                                             0))
        self.font_size.setValue(self.state.font_size)
        self.frame_style.setCurrentIndex(max(self.frame_style.findData(self.state.frame_style),
                                             0))
        self.show_grid.setChecked(self.state.show_grid)
        self._fill_table()
        self._loading = False
        self._update_preview()

    def _fill_table(self) -> None:
        theme = self.state.themes[self.edit_name]
        rows = [(key, label, None) for key, label in UI_ROLES] + \
            [(key, label, theme.syntax[key]) for key, label in SYNTAX_ROLES]
        self.table.setRowCount(len(rows))
        for row, (key, label, style) in enumerate(rows):
            item = QTableWidgetItem(label)
            item.setFlags(Qt.ItemIsEnabled)
            self.table.setItem(row, 0, item)
            color = style.color if style else theme.colors[key]
            button = QPushButton(color)
            button.setIcon(_swatch(color))
            button.setStyleSheet("text-align: left; padding: 2px 6px;")
            button.clicked.connect(lambda _=False, k=key, s=style is not None, l=label:
                                   self._pick_color(k, s, l))
            self.table.setCellWidget(row, 1, button)
            for column, attr in ((2, "bold"), (3, "italic")):
                if style is None:
                    self.table.setCellWidget(row, column, QWidget())
                    continue
                box = QCheckBox()
                box.setChecked(getattr(style, attr))
                box.toggled.connect(lambda on, k=key, a=attr: self._set_style_flag(k, a, on))
                holder = QWidget()
                holder_layout = QHBoxLayout(holder)
                holder_layout.setContentsMargins(0, 0, 0, 0)
                holder_layout.setAlignment(Qt.AlignCenter)
                holder_layout.addWidget(box)
                self.table.setCellWidget(row, column, holder)

    def _update_preview(self) -> None:
        theme = self.state.themes[self.edit_name]
        self.preview.apply_theme(theme, self.manager.font(self.state))
        self.preview_doc.highlighter.set_theme(theme)
        self.preview.apply_fold()

    # -- editing ---------------------------------------------------------------------------------
    def _on_selection(self, index: int) -> None:
        self.state.selection = self.selection.itemData(index)
        self.edit_name = self.manager.resolve(self.state).name
        self._reload()

    def _on_system_slots(self, *_):
        self.state.system_light = self.system_light.currentText()
        self.state.system_dark = self.system_dark.currentText()
        if self.state.selection == SYSTEM:
            self.edit_name = self.manager.resolve(self.state).name
        self._reload()

    def _edit_theme(self, name: str) -> None:
        self.edit_name = name
        self._reload()

    def _pick_color(self, key: str, syntax: bool, label: str) -> None:
        theme = self.state.themes[self.edit_name]
        current = theme.syntax[key].color if syntax else theme.colors[key]
        color = QColorDialog.getColor(QColor(current), self, label)
        if not color.isValid():
            return
        if syntax:
            theme.syntax[key].color = color.name()
        else:
            theme.colors[key] = color.name()
        self._reload()

    def _set_style_flag(self, key: str, attr: str, on: bool) -> None:
        if self._loading:
            return
        setattr(self.state.themes[self.edit_name].syntax[key], attr, on)
        self._update_preview()

    def _on_font(self, *_):
        if self._loading:
            return
        self.state.font_family = self.font_family.currentData() or ""
        self.state.font_size = self.font_size.value()
        self._update_preview()

    def _on_frame_style(self, index: int) -> None:
        self.state.frame_style = self.frame_style.itemData(index)

    def _on_show_grid(self, on: bool) -> None:
        if not self._loading:
            self.state.show_grid = on

    def _new_theme(self) -> None:
        name, ok = QInputDialog.getText(self, "New Theme", "Name of the new theme:",
                                        text=f"{self.edit_name} Custom")
        name = name.strip()
        if not ok or not name:
            return
        if name in self.state.themes or name == SYSTEM:
            QMessageBox.warning(self, "New Theme", f"A theme named '{name}' already exists.")
            return
        theme = copy.deepcopy(self.state.themes[self.edit_name])
        theme.name = name
        self.state.themes[name] = theme
        self.edit_name = name
        # Use the new theme right away, in place of the one it was copied from
        if self.state.selection != SYSTEM:
            self.state.selection = name
        elif system_is_dark():
            self.state.system_dark = name
        else:
            self.state.system_light = name
        self._reload()

    def _delete_theme(self) -> None:
        name = self.edit_name
        if name in BUILTIN_THEMES:
            return
        del self.state.themes[name]
        if self.state.selection == name:
            self.state.selection = SYSTEM
        if self.state.system_light == name:
            self.state.system_light = LIGHT
        if self.state.system_dark == name:
            self.state.system_dark = DARK
        self.edit_name = self.manager.resolve(self.state).name
        self._reload()

    def _reset_theme(self) -> None:
        if self.edit_name in BUILTIN_THEMES:
            self.state.themes[self.edit_name] = copy.deepcopy(BUILTIN_THEMES[self.edit_name])
            self._reload()

    # -- applying -------------------------------------------------------------------------------------
    def apply(self) -> None:
        self.manager.apply(self.state)

    def accept(self) -> None:
        self.apply()
        super().accept()

