"""Control arrays: the runtime, the form file format, the designer, the
Properties window and the code window."""

import os

import pytest
from PySide6.QtCore import QRect

from vp6 import CommandButton, ControlArray, Form, Frame, Label, Load, Unload, formfile
from vp6.formfile import FormFileError
from vp6.ide.codeeditor import CodeWindow, complete
from vp6.ide.designer import FormDesigner
from vp6.ide.documents import FormDocument
from vp6.ide.properties import PropertiesWindow

os.environ.setdefault("VP6_NO_ERROR_DIALOG", "1")


# --- runtime ---------------------------------------------------------------------------------

class Digits(Form):
    def InitializeComponent(self):
        self.cmdDigit = ControlArray()
        self.cmdDigit[0] = CommandButton(self, Caption="0", Left=0, TabIndex=0)
        self.cmdDigit[2] = CommandButton(self, Caption="2", Left=100, TabIndex=1)
        self.fraBox = ControlArray()
        self.fraBox[0] = Frame(self, Caption="Box", Left=200, Width=200, Height=100)
        self.lblInside = Label(self.fraBox[0], Caption="inside")

    def Form_Load(self):
        self.clicks = []

    def cmdDigit_Click(self, Index):
        self.clicks.append(Index)

    def cmdDigit_MouseUp(self, Index, Button):
        self.clicks.append(("up", Index, Button))


@pytest.fixture
def digits(qapp):
    form = Digits()
    form.Load()
    yield form
    form.Unload()


def test_elements_and_properties(digits):
    array = digits.cmdDigit
    assert repr(array) == "<ControlArray cmdDigit [0, 2]>"
    assert (array.Count, len(array), array.LBound, array.UBound) == (2, 2, 0, 2)
    assert array[2] is array(2) is array.Item(2)  # VB style cmdDigit(2) too
    assert [c.Caption for c in array] == ["0", "2"]  # iterating: in Index order
    assert 2 in array and 1 not in array
    assert array[2].Name == "cmdDigit" and array[2].Index == 2
    assert repr(array[2]) == "<CommandButton cmdDigit(2)>"
    assert digits.lblInside.Parent is digits.fraBox[0]
    assert digits.lblInside.Index is None  # not in an array
    with pytest.raises(IndexError, match=r"cmdDigit\(1\)"):
        array[1]
    with pytest.raises(AttributeError, match="Index"):
        array[0].Index = 5  # only the designer sets it


def test_handlers_get_the_index_first(digits):
    digits.cmdDigit[2]._widget.click()
    digits.cmdDigit[0]._widget.click()
    digits.cmdDigit[2]._fire("MouseUp", 1, 0, 5, 5)  # extra arguments are trimmed
    assert digits.clicks == [2, 0, ("up", 2, 1)]


def test_load_and_unload_elements(digits):
    array = digits.cmdDigit
    new = Load(array, 5)  # VB: Load cmdDigit(5)
    assert array[5] is new and new.Index == 5 and array.UBound == 5
    assert new.Caption == "0" and new.Left == 0  # copied from the lowest element
    assert not new.Visible  # hidden until placed
    assert new.TabIndex == 2  # the end of the tab order
    assert new in digits.Controls
    new._widget.click()
    assert digits.clicks == [5]
    assert array.Load(6).Index == 6  # also as a method
    Unload(array, 5)
    array.Unload(6)
    assert list(array) == [array[0], array[2]] and new not in digits.Controls
    with pytest.raises(ValueError, match="designer"):
        Unload(array, 0)  # created in the designer
    with pytest.raises(ValueError, match="already exists"):
        array.Load(2)
    with pytest.raises(ValueError, match="0 to 32767"):
        array.Load(-1)


def test_elements_must_have_one_type(qapp):
    class Mixed(Form):
        def InitializeComponent(self):
            self.things = ControlArray()
            self.things[0] = CommandButton(self)
            self.things[1] = Label(self)

    with pytest.raises(TypeError, match="CommandButton"):
        Mixed()


# --- the form file ---------------------------------------------------------------------------

SOURCE = '''from vp6 import *


class Form1(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Form1'
        self.Width = 480
        self.Height = 360
        self.fraBox = ControlArray()
        self.fraBox[1] = Frame(self, Caption='Box', Left=8, Top=8, Width=200, Height=120)
        self.cmdDigit = ControlArray()
        self.cmdDigit[0] = CommandButton(self.fraBox[1], Caption='0', Left=8, Top=16, Width=40,
                                         Height=32)
        self.cmdDigit[1] = CommandButton(self.fraBox[1], Caption='1', Left=56, Top=16, Width=40,
                                         Height=32, TabIndex=1)
        self.lblTotal = Label(self, Caption='Total', Left=8, Top=160, Width=96, Height=24)
    # endregion

    def cmdDigit_Click(self, Index):
        pass


if __name__ == "__main__":
    run(Form1)
'''


def test_parse_and_generate_round_trip():
    form = formfile.parse(SOURCE)
    assert [c.key for c in form.controls] == ["fraBox(1)", "cmdDigit(0)", "cmdDigit(1)",
                                              "lblTotal"]
    assert form.control("cmdDigit(1)").parent == "fraBox(1)"
    assert form.control("cmdDigit(1)").index == 1 and form.control("lblTotal").index is None
    assert [c.key for c in form.elements("cmdDigit")] == ["cmdDigit(0)", "cmdDigit(1)"]
    assert form.is_array("cmdDigit") and not form.is_array("lblTotal")
    assert formfile.replace_region(SOURCE, form) == SOURCE


@pytest.mark.parametrize("line, message", [
    ("self.btn[0] = CommandButton(self)", "not declared"),
    ("self.btn = ControlArray()\n        self.btn = CommandButton(self)", "is a control array"),
    ("self.btn = ControlArray()\n        self.btn[0] = CommandButton(self)\n"
     "        self.btn[0] = CommandButton(self)", "defined twice"),
    ("self.btn = ControlArray()\n        self.btn[0] = CommandButton(self)\n"
     "        self.btn[1] = Label(self)", "mixes"),
    ("self.btn = ControlArray()\n        self.lbl = Label(self.btn[3])", "not defined before"),
])
def test_invalid_arrays(line, message):
    body = f"def InitializeComponent(self):\n        {line}\n"
    with pytest.raises(FormFileError, match=message):
        formfile.parse_region_body(body.replace("        ", "    "), "Form1")


def test_index_parameter_and_stubs():
    source = ("    def cmd_Click(self):\n"
              "    def cmd_MouseDown(self, Button, Shift, X, Y):\n"
              "    def cmd_Clicked(self):\n"
              "    def cmdOther_Click(self):\n")
    events = CommandButton.Events
    added = formfile.set_index_parameter(source, "cmd", events, True)
    assert added == ("    def cmd_Click(self, Index):\n"
                     "    def cmd_MouseDown(self, Index, Button, Shift, X, Y):\n"
                     "    def cmd_Clicked(self):\n"
                     "    def cmdOther_Click(self):\n")
    assert formfile.set_index_parameter(added, "cmd", events, True) == added  # once
    assert formfile.set_index_parameter(added, "cmd", events, False) == source
    assert formfile.event_stub("cmd", "KeyPress", "KeyAscii", index=True) == \
        "    def cmd_KeyPress(self, Index, KeyAscii):\n        pass\n"


# --- the designer ----------------------------------------------------------------------------

@pytest.fixture
def designer(qapp, tmp_path):
    path = tmp_path / "Form1.py"
    path.write_text(formfile.new_form_source("Form1") +
                    "\n\ndef helper():\n    pass\n")
    d = FormDesigner(FormDocument(str(path)), str(tmp_path))
    questions = d.questions = []

    def answer(name):
        questions.append(name)
        return True  # Yes, create a control array

    d.ask_create_array = answer
    d.resize(800, 600)
    d.show()
    yield d
    d.close()


def _button(d, x=16):
    origin = d.form_canvas_rect().topLeft()
    return d.create_control("CommandButton", QRect(origin.x() + x, origin.y() + 16, 96, 32),
                            None)


def _keys(d):
    return [c.key for c in d.form_def.controls]


def test_paste_creates_an_array_after_asking(designer):
    d = designer
    _button(d)
    d.document.replace_text(d.document.text.replace(
        "    def Form_Load(self):", "    def Command1_Click(self):\n        pass\n\n"
                                    "    def Form_Load(self):"))
    d.select(["Command1"])
    d.copy_selection()
    d.paste()  # VB: "You already have a control named 'Command1'..." - Yes
    assert d.questions == ["Command1"]
    assert _keys(d) == ["Command1(0)", "Command1(1)"]
    assert d.selection == ["Command1(1)"]
    assert "def Command1_Click(self, Index):" in d.document.text  # handlers get Index
    assert "self.Command1 = ControlArray()" in d.document.text
    assert "self.Command1[1] = CommandButton(self," in d.document.text
    d.paste()  # already an array: no question, the next Index
    assert d.questions == ["Command1"] and _keys(d)[-1] == "Command1(2)"
    assert d.controls["Command1(2)"].Index == 2
    d.ask_create_array = lambda name: False
    _button(d, 200)  # Command2
    d.select(["Command2"])
    d.copy_selection()
    d.paste()  # "No": a new name, like before
    assert _keys(d)[-1] == "Command3"


def test_rename_joins_an_array(designer):
    d = designer
    _button(d)
    _button(d, 120)
    d.select(["Command2"])
    assert d.set_property("Name", "Command1") is None  # asks, then both form an array
    assert d.questions == ["Command1"]
    assert _keys(d) == ["Command1(0)", "Command1(1)"]
    d.select(["Command1(1)"])
    assert d.set_property("Name", "cmdOther") is None  # leaves the array, keeps its Index
    assert _keys(d) == ["Command1(0)", "cmdOther(1)"]
    d.create_control("Label", None, None, d.form_canvas_rect().topLeft())
    d.select(["Label1"])
    assert "already used by a CommandButton" in d.set_property("Name", "Command1")
    d.select([])
    assert "already used" in d.set_property("Name", "Command1")  # the form


def test_index_property(designer):
    d = designer
    _button(d)
    d.document.replace_text(d.document.text.replace(
        "    def Form_Load(self):", "    def Command1_Click(self):\n        pass\n\n"
                                    "    def Form_Load(self):"))
    d.select(["Command1"])
    assert d.set_property("Index", 3) is None  # a one-element array
    assert _keys(d) == ["Command1(3)"] and d.selection == ["Command1(3)"]
    assert "def Command1_Click(self, Index):" in d.document.text
    _button(d, 120)
    d.select(["Command2"])
    d.set_property("Name", "Command1")  # joins with the next Index
    assert _keys(d) == ["Command1(3)", "Command1(4)"]
    assert d.set_property("Index", 3) == "'Command1(3)' already exists"
    assert d.set_property("Index", 40000) == "Index must be from 0 to 32767"
    assert "Other controls" in d.set_property("Index", None)
    assert d.set_property("Index", 0) is None
    assert _keys(d) == ["Command1(3)", "Command1(0)"]
    d.select(["Command1(3)"])
    d.delete_selection()
    d.select(["Command1(0)"])
    assert d.set_property("Index", None) is None  # the last one: a plain control again
    assert _keys(d) == ["Command1"]
    assert "def Command1_Click(self):" in d.document.text
    d.undo()
    assert _keys(d) == ["Command1(0)"]


def test_containers_in_arrays(designer):
    d = designer
    origin = d.form_canvas_rect().topLeft()
    d.create_control("Frame", QRect(origin.x() + 16, origin.y() + 16, 200, 150), None)
    d.select(["Frame1"])
    d.set_property("Index", 0)
    d.create_control("CheckBox", None, "Frame1(0)", origin + d.parent_rect("Frame1(0)").center())
    assert d.form_def.control("Check1").parent == "Frame1(0)"
    assert "CheckBox(self.Frame1[0]," in d.document.text
    d.select(["Frame1(0)"])
    d.set_property("Index", 2)  # the child follows its container
    assert d.form_def.control("Check1").parent == "Frame1(2)"
    assert formfile.parse(d.document.text) == d.form_def


def test_properties_window(designer):
    d = designer
    _button(d)
    d.select(["Command1"])
    d.set_property("Index", 0)
    window = PropertiesWindow()
    window.set_designer(d)
    rows = {window.table.item(r, 0).text(): window.table.cellWidget(r, 1)
            for r in range(window.table.rowCount())}
    assert list(rows)[:2] == ["(Name)", "Index"]  # Index right after (Name), like VB
    assert rows["(Name)"].text() == "Command1" and rows["Index"].text() == "0"
    assert window.object_combo.currentText() == "Command1(0)  CommandButton"
    d.select([])  # the form has no Index
    assert "Index" not in [window.table.item(r, 0).text()
                           for r in range(window.table.rowCount())]


def test_code_window_and_completion(designer):
    d = designer
    _button(d)
    d.select(["Command1"])
    d.copy_selection()
    d.paste()
    window = CodeWindow(d.document)
    objects = [name for name, _ in window._objects()]
    assert objects.count("Command1") == 1  # an array is one object
    window.goto_event("Command1", "MouseDown")  # the new handler gets Index
    assert "def Command1_MouseDown(self, Index, Button, Shift, X, Y):" in d.document.text
    doc = d.document
    assert complete("self.", doc).count("Command1") == 1
    assert "UBound" in complete("self.Command1.", doc) and "Caption" not in \
        complete("self.Command1.", doc)
    assert "Caption" in complete("self.Command1[0].", doc)
    assert "Caption" in complete("self.Command1(Index).", doc)
