"""Reading and writing the designer region of form source files.

A form is a single Python file. The IDE owns one block inside the form class:

    class Form1(Form):
        # region VP6 Designer - generated by the form designer, do not edit
        def InitializeComponent(self):
            self.Caption = 'Form1'
            self.Command1 = CommandButton(self, Caption='OK', Left=16, Top=16, ...)
        # endregion

        def Command1_Click(self):
            ...

Control arrays are declared, then filled element by element::

            self.cmdDigit = ControlArray()
            self.cmdDigit[0] = CommandButton(self, Caption='0', ...)
            self.chkOption = CheckBox(self.fraGroup[1], ...)   # inside an element

The block is parsed with ``ast`` (the user's code is never executed) and
regenerated whenever the design changes. Everything outside it is yours.
"""

from __future__ import annotations

import ast
import re
import textwrap
from dataclasses import dataclass, field

from .controls import CONTROL_TYPES
from .form import Form

REGION_START = "# region VP6 Designer - generated by the form designer, do not edit"
REGION_END = "# endregion"
_START_RE = re.compile(r"^\s*# region VP6 Designer")
_END_RE = re.compile(r"^\s*# endregion\b")
_CLASS_RE = re.compile(r"^class\s+(\w+)\s*\(\s*(?:\w+\.)?(Form|UserControl)\s*\)\s*:",
                       re.M)
_DEF_RE = re.compile(r"^\s+def\s+(\w+)\s*\(", re.M)

MAX_LINE = 99


class FormFileError(Exception):
    pass


def control_key(name: str, index: int | None) -> str:
    """How a control is identified: 'Command1', or 'cmdDigit(3)' for an
    element of a control array (as VB shows it)."""
    return name if index is None else f"{name}({index})"


@dataclass
class ControlDef:
    type: str
    name: str
    parent: str | None = None  # the container's key; None = directly on the form
    props: dict = field(default_factory=dict)
    index: int | None = None  # the Index in a control array; None = not in one

    @property
    def key(self) -> str:
        return control_key(self.name, self.index)


@dataclass
class FormDef:
    class_name: str
    props: dict = field(default_factory=dict)
    controls: list[ControlDef] = field(default_factory=list)
    # "form", or "usercontrol": a UserControl's file, whose own properties are
    # its Surface's (``self.Surface.Width = 160``)
    kind: str = "form"

    def control(self, key: str) -> ControlDef | None:
        """The control with this key ('Command1' or 'cmdDigit(3)')."""
        return next((c for c in self.controls if c.key == key), None)

    def elements(self, name: str) -> list[ControlDef]:
        """All controls with this name: one, or a control array's elements
        in Index order."""
        return sorted((c for c in self.controls if c.name == name),
                      key=lambda c: -1 if c.index is None else c.index)

    def is_array(self, name: str) -> bool:
        return any(c.name == name and c.index is not None for c in self.controls)


# --- locating the region ---------------------------------------------------------

def find_region(source: str) -> tuple[int, int] | None:
    """Return (start, end) line indices (inclusive) of the designer region."""
    lines = source.splitlines()
    start = next((i for i, line in enumerate(lines) if _START_RE.match(line)), None)
    if start is None:
        return None
    end = next((i for i in range(start + 1, len(lines)) if _END_RE.match(lines[i])), None)
    if end is None:
        raise FormFileError("Designer region has no '# endregion' line")
    return start, end


def find_form_class(source: str) -> str | None:
    match = _CLASS_RE.search(source)
    return match.group(1) if match else None


def find_form_kind(source: str) -> str | None:
    """"form" for a Form's file, "usercontrol" for a UserControl's, else None."""
    match = _CLASS_RE.search(source)
    if match is None:
        return None
    return "usercontrol" if match.group(2) == "UserControl" else "form"


def is_form_source(source: str) -> bool:
    return find_form_class(source) is not None and find_region(source) is not None


def defined_methods(source: str) -> list[str]:
    """Names of methods defined (indented ``def``) in the source."""
    return _DEF_RE.findall(source)


# --- parsing -------------------------------------------------------------------------

def parse(source: str) -> FormDef:
    class_name = find_form_class(source)
    if class_name is None:
        raise FormFileError("No 'class ...(Form):' or 'class ...(UserControl):' found")
    region = find_region(source)
    if region is None:
        raise FormFileError("No designer region found")
    start, end = region
    body = "\n".join(source.splitlines()[start + 1:end])
    return parse_region_body(textwrap.dedent(body), class_name, find_form_kind(source))


def parse_region_body(body: str, class_name: str, kind: str = "form") -> FormDef:
    try:
        module = ast.parse(body)
    except SyntaxError as exc:
        raise FormFileError(f"Designer region is not valid Python: {exc}") from exc
    func = next((n for n in module.body
                 if isinstance(n, ast.FunctionDef) and n.name == "InitializeComponent"), None)
    if func is None:
        raise FormFileError("Designer region has no InitializeComponent method")

    form = FormDef(class_name, kind=kind)
    arrays: set[str] = set()  # declared with ControlArray()
    for stmt in func.body:
        if isinstance(stmt, ast.Pass) or (isinstance(stmt, ast.Expr)
                                          and isinstance(stmt.value, ast.Constant)):
            continue
        if not (isinstance(stmt, ast.Assign) and len(stmt.targets) == 1):
            raise FormFileError(f"Unexpected statement in designer region, line {stmt.lineno}")
        target, value = stmt.targets[0], stmt.value
        element = _self_element(target)
        if element is not None:  # self.cmdDigit[0] = CommandButton(...)
            name, index = element
            if name not in arrays:
                raise FormFileError(f"'{name}' is not declared as a ControlArray() before "
                                    f"line {stmt.lineno}")
            if not _is_control_call(value):
                raise FormFileError(f"'{name}[{index}]' must be a control (line {stmt.lineno})")
            _add_control(form, _parse_control(name, value, form, index), stmt.lineno)
            continue
        if kind == "usercontrol" and _is_surface_attr(target):  # self.Surface.Width = 160
            form.props[target.attr] = _literal(value, stmt.lineno)
            continue
        if not _is_self_attr(target):
            raise FormFileError(f"Unexpected statement in designer region, line {stmt.lineno}")
        name = target.attr
        if isinstance(value, ast.Call) and isinstance(value.func, ast.Name) and \
                value.func.id == "ControlArray":
            if value.args or value.keywords or name in arrays or form.elements(name):
                raise FormFileError(f"Invalid control array '{name}' (line {stmt.lineno})")
            arrays.add(name)
        elif _is_control_call(value):
            if name in arrays:
                raise FormFileError(f"'{name}' is a control array: its elements are "
                                    f"'self.{name}[Index] = ...' (line {stmt.lineno})")
            _add_control(form, _parse_control(name, value, form), stmt.lineno)
        else:
            form.props[name] = _literal(value, stmt.lineno)
    return form


def _is_self_attr(node) -> bool:
    return (isinstance(node, ast.Attribute) and isinstance(node.value, ast.Name)
            and node.value.id == "self")


def _is_surface_attr(node) -> bool:
    """``self.Surface.Name``: a property of a user control's surface."""
    return isinstance(node, ast.Attribute) and _is_self_attr(node.value) and \
        node.value.attr == "Surface"


def _self_element(node) -> tuple[str, int] | None:
    """('cmdDigit', 3) for ``self.cmdDigit[3]``, else None."""
    if isinstance(node, ast.Subscript) and _is_self_attr(node.value) and \
            isinstance(node.slice, ast.Constant) and type(node.slice.value) is int:
        return node.value.attr, node.slice.value
    return None


def _is_control_call(value) -> bool:
    return isinstance(value, ast.Call) and bool(value.args) and (
        _is_self_attr(value.args[0]) or _self_element(value.args[0]) is not None or
        (isinstance(value.args[0], ast.Name) and value.args[0].id == "self"))


def _add_control(form: FormDef, control: ControlDef, lineno: int) -> None:
    if form.control(control.key) is not None:
        raise FormFileError(f"'{control.key}' is defined twice (line {lineno})")
    others = form.elements(control.name)
    if others and others[0].type != control.type:
        raise FormFileError(f"Control array '{control.name}' mixes {others[0].type} and "
                            f"{control.type} (line {lineno})")
    form.controls.append(control)


def _parse_control(name: str, call: ast.Call, form: FormDef,
                   index: int | None = None) -> ControlDef:
    key = control_key(name, index)
    if not isinstance(call.func, ast.Name) or call.func.id not in CONTROL_TYPES:
        raise FormFileError(f"Unknown control type for '{key}' (line {call.lineno})")
    if len(call.args) != 1:
        raise FormFileError(f"Control '{key}' must have exactly one parent argument")
    parent_node = call.args[0]
    element = _self_element(parent_node)
    if isinstance(parent_node, ast.Name) and parent_node.id == "self":
        parent = None
    elif _is_self_attr(parent_node) or element is not None:
        parent = parent_node.attr if element is None else control_key(*element)
        if form.control(parent) is None:
            raise FormFileError(f"Parent '{parent}' of '{key}' is not defined before it")
    else:
        raise FormFileError(f"Invalid parent for control '{key}'")
    props = {kw.arg: _literal(kw.value, call.lineno) for kw in call.keywords}
    return ControlDef(call.func.id, name, parent, props, index)


def _literal(node, lineno):
    try:
        return ast.literal_eval(node)
    except ValueError as exc:
        raise FormFileError(f"Designer values must be literals (line {lineno})") from exc


# --- generation --------------------------------------------------------------------------

def format_value(kind: str, value) -> str:
    if kind == "color" and isinstance(value, int):
        return f"0x{value:06X}"
    return repr(value)


def _props_to_args(specs: dict, props: dict) -> list[str]:
    args = []
    for spec in specs.values():  # spec order keeps the output stable
        if spec.name not in props:
            continue
        value = props[spec.name]
        if not spec.always and value == spec.default:
            continue
        args.append((spec.name, format_value(spec.kind, value)))
    # Values the class doesn't know (e.g. a user control's that couldn't be
    # imported): kept as they are, never dropped
    for name in sorted(set(props) - set(specs)):
        args.append((name, repr(props[name])))
    return args


def surface_specs() -> dict:
    """The properties a user control's surface has in the designer."""
    from .usercontrol import SURFACE_PROPERTIES

    return {name: Form._specs[name] for name in SURFACE_PROPERTIES}


def _wrap_call(prefix: str, args: list[str]) -> list[str]:
    """Fill arguments into lines of at most MAX_LINE, aligned after '('."""
    hanging = " " * len(prefix)
    lines, current = [], prefix
    for i, arg in enumerate(args):
        piece = arg + (", " if i < len(args) - 1 else ")")
        if current not in (prefix, hanging) and len(current + piece.rstrip()) > MAX_LINE:
            lines.append(current.rstrip())
            current = hanging
        current += piece
    lines.append(current)
    return lines


def generate_region(form: FormDef, indent: str = "    ") -> str:
    body = indent * 2
    lines = [indent + REGION_START, indent + "def InitializeComponent(self):"]
    if form.kind == "usercontrol":
        for name, value in _props_to_args(surface_specs(), form.props):
            lines.append(f"{body}self.Surface.{name} = {value}")
    else:
        for name, value in _props_to_args(Form._specs, form.props):
            lines.append(f"{body}self.{name} = {value}")
    declared = set()
    for control in form.controls:
        cls = CONTROL_TYPES.get(control.type)
        specs = cls._specs if cls is not None else {}
        parent = "self" if control.parent is None else _reference(form.control(control.parent))
        args = [parent] + [f"{k}={v}" for k, v in _props_to_args(specs, control.props)]
        if control.index is not None and control.name not in declared:
            lines.append(f"{body}self.{control.name} = ControlArray()")
            declared.add(control.name)
        lines.extend(_wrap_call(f"{body}{_reference(control)} = {control.type}(", args))
    lines.append(indent + REGION_END)
    return "\n".join(lines)


def _reference(control: ControlDef) -> str:
    """How code refers to a control: self.Command1 or self.cmdDigit[3]."""
    if control.index is None:
        return f"self.{control.name}"
    return f"self.{control.name}[{control.index}]"


def replace_region(source: str, form: FormDef) -> str:
    region = find_region(source)
    if region is None:
        raise FormFileError("No designer region found")
    start, end = region
    lines = source.splitlines()
    indent = re.match(r"\s*", lines[start]).group(0) or "    "
    new = generate_region(form, indent).splitlines()
    trailing = "\n" if source.endswith("\n") else ""
    return "\n".join(lines[:start] + new + lines[end + 1:]) + trailing


# --- templates and refactoring ----------------------------------------------------------------

def new_form_source(class_name: str, caption: str | None = None) -> str:
    form = FormDef(class_name, {"Caption": caption or class_name, "Width": 480, "Height": 360})
    return (
        "from vp6 import *\n\n\n"
        f"class {class_name}(Form):\n"
        f"{generate_region(form)}\n\n"
        "    def Form_Load(self):\n"
        "        pass\n\n\n"
        'if __name__ == "__main__":\n'
        f"    run({class_name})\n"
    )


def new_user_control_source(class_name: str) -> str:
    """A new user control: an empty surface, a property and an event to start from."""
    from .usercontrol import DEFAULT_SURFACE

    form = FormDef(class_name, {"Width": DEFAULT_SURFACE[0], "Height": DEFAULT_SURFACE[1]},
                   kind="usercontrol")
    return (
        "from vp6 import *\n\n\n"
        f"class {class_name}(UserControl):\n"
        "    # Its properties (set in the Properties window and in code) and events\n"
        "    # (handled on the form it is on; raised with self.RaiseEvent)\n"
        '    Properties = (Property("Caption", "str", "", description="Its text"),)\n'
        '    Events = ("Click",)\n\n'
        f"{generate_region(form)}\n\n"
        "    def UserControl_PropertyChanged(self, PropertyName):\n"
        "        pass\n\n"
        "    def UserControl_Click(self):\n"
        '        self.RaiseEvent("Click")\n'
    )


def import_insertion(source: str, module: str, name: str) -> tuple[int, str] | None:
    """Where ``from module import name`` goes in a file (the line after its
    imports) and the statement, or None if the file already imports it."""
    if re.search(rf"^\s*from\s+{re.escape(module)}\s+import\s+.*\b{re.escape(name)}\b",
                 source, re.M):
        return None
    last = None
    for index, line in enumerate(source.splitlines()):
        if re.match(r"(from\s+\S+\s+import\s|import\s)", line):
            last = index
        elif line.strip() and not line.startswith(("#", '"', "'", " ")) and last is not None:
            break
    return (0 if last is None else last + 1), f"from {module} import {name}"


def ensure_import(source: str, module: str, name: str) -> str:
    """Add ``from module import name`` after the file's imports (a form using
    a user control imports its class), unless it is there."""
    insertion = import_insertion(source, module, name)
    if insertion is None:
        return source
    line, statement = insertion
    lines = source.splitlines(keepends=True)
    lines.insert(line, statement + "\n")
    return "".join(lines)


def new_module_source(with_main: bool = False, console: bool = False,
                      startup_form: str | None = None) -> str:
    """Source of a new module.

    with_main adds ``Main()`` (the project's Sub Main) and an
    ``if __name__ == "__main__"`` block, so the module runs on its own too:

    * console: Main() asks for a name and greets you;
    * startup_form: Main() shows that form and runs until it is closed;
    * otherwise Main() is empty.
    """
    header = "from vp6 import *\n"
    if not with_main:
        return header + "\n\n"
    if console:
        body = ('    name = input("What is your name? ")\n'
                '    print(f"Hello, {name}!")\n')
    elif startup_form:
        header += f"from {startup_form} import {startup_form}\n"
        body = ("    # Show the startup form and run until it is closed\n"
                f"    run({startup_form})\n")
    else:
        body = "    pass\n"
    return (header + "\n\n"
            "def Main():\n" + body + "\n\n"
            'if __name__ == "__main__":\n'
            "    Main()\n")


def rename_form_class(source: str, old: str, new: str) -> str:
    source = re.sub(rf"^class\s+{re.escape(old)}\s*\(", f"class {new}(", source, flags=re.M)
    return re.sub(rf"\brun\(\s*{re.escape(old)}\s*\)", f"run({new})", source)


def rename_control_references(source: str, old: str, new: str) -> str:
    """Rename event handlers (``def Old_Click``) and ``self.Old`` references
    outside the designer region (which is regenerated separately)."""
    region = find_region(source)
    lines = source.splitlines(keepends=True)
    skip = range(region[0], region[1] + 1) if region else range(0)
    handler = re.compile(rf"\bdef\s+{re.escape(old)}_(\w+)\s*\(")
    reference = re.compile(rf"\bself\.{re.escape(old)}\b")
    for i, line in enumerate(lines):
        if i in skip:
            continue
        line = handler.sub(lambda m: f"def {new}_{m.group(1)}(", line)
        lines[i] = reference.sub(f"self.{new}", line)
    return "".join(lines)


_FROM_IMPORT_RE = re.compile(r"^(\s*from\s+)([\w.]+)(\s+import\s+)(.*)$")
_IMPORT_RE = re.compile(r"^(\s*import\s+)(.*)$")


def _map_lines(source: str, fix_line) -> str:
    """Apply fix_line(line_without_newline) to every line, keeping newlines."""
    out = []
    for line in source.splitlines(keepends=True):
        body = line.rstrip("\r\n")
        out.append(fix_line(body) + line[len(body):])
    return "".join(out)


def rename_class_references(source: str, old: str, new: str) -> str:
    """Rename references to a class (e.g. a renamed form) in another file.

    In ``from Form1 import Form1`` only the imported name changes, since the
    module is the file, which keeps its name; ``import X`` lines are left
    alone. Elsewhere every ``old`` that isn't an attribute (``x.old``) is
    renamed."""
    word = re.compile(rf"(?<![\w.]){re.escape(old)}\b")

    def fix(line: str) -> str:
        m = _FROM_IMPORT_RE.match(line)
        if m:
            return m.group(1) + m.group(2) + m.group(3) + word.sub(new, m.group(4))
        if _IMPORT_RE.match(line):
            return line
        return word.sub(new, line)

    return _map_lines(source, fix)


def rename_module_references(source: str, old: str, new: str) -> str:
    """Rename references to a module (a renamed module file) in another file:
    ``from old import ...``, ``import old`` and qualified uses ``old.name``."""
    word = re.compile(rf"(?<![\w.]){re.escape(old)}\b")
    qualified = re.compile(rf"(?<![\w.]){re.escape(old)}(?=\s*\.)")

    def fix(line: str) -> str:
        m = _FROM_IMPORT_RE.match(line)
        if m:
            module = new if m.group(2) == old else m.group(2)
            return m.group(1) + module + m.group(3) + m.group(4)
        m = _IMPORT_RE.match(line)
        if m:
            return m.group(1) + word.sub(new, m.group(2))
        return qualified.sub(new, line)

    return _map_lines(source, fix)


def set_index_parameter(source: str, name: str, events, present: bool) -> str:
    """Add (``present``) or remove the ``Index`` parameter of the event
    handlers of ``name`` (``def name_Click(self)`` <-> ``def name_Click(self,
    Index)``): what VB does when a control becomes a control array or stops
    being one."""
    if not events:
        return source
    handler = re.compile(
        rf"^(\s*def\s+{re.escape(name)}_(?:{'|'.join(map(re.escape, events))})\s*\(\s*self)"
        r"(\s*,\s*Index\b(?:\s*:\s*[\w.]+)?)?(?=\s*[,)])", re.M)

    def fix(match):
        if present:
            return match.group(0) if match.group(2) else match.group(1) + ", Index"
        return match.group(1)

    return handler.sub(fix, source)


def event_stub(obj: str, event: str, args: str, index: bool = False) -> str:
    """A new handler; ``index`` for a control array (Index comes first)."""
    params = ["self"] + (["Index"] if index else []) + ([args] if args else [])
    return f"    def {obj}_{event}({', '.join(params)}):\n        pass\n"
