"""Reading and writing the designer region of form source files.

A form is a single Python file. The IDE owns one block inside the form class:

    class Form1(Form):
        # region VP6 Designer - generated by the form designer, do not edit
        def InitializeComponent(self):
            self.Caption = 'Form1'
            self.Command1 = CommandButton(self, Caption='OK', Left=16, Top=16, ...)
        # endregion

        def Command1_Click(self):
            ...

The block is parsed with ``ast`` (the user's code is never executed) and
regenerated whenever the design changes. Everything outside it is yours.
"""

from __future__ import annotations

import ast
import re
import textwrap
from dataclasses import dataclass, field

from .controls import CONTROL_TYPES
from .form import Form

REGION_START = "# region VP6 Designer - generated by the form designer, do not edit"
REGION_END = "# endregion"
_START_RE = re.compile(r"^\s*# region VP6 Designer")
_END_RE = re.compile(r"^\s*# endregion\b")
_CLASS_RE = re.compile(r"^class\s+(\w+)\s*\(\s*(?:\w+\.)?Form\s*\)\s*:", re.M)
_DEF_RE = re.compile(r"^\s+def\s+(\w+)\s*\(", re.M)

MAX_LINE = 99


class FormFileError(Exception):
    pass


@dataclass
class ControlDef:
    type: str
    name: str
    parent: str | None = None  # None = directly on the form
    props: dict = field(default_factory=dict)


@dataclass
class FormDef:
    class_name: str
    props: dict = field(default_factory=dict)
    controls: list[ControlDef] = field(default_factory=list)

    def control(self, name: str) -> ControlDef | None:
        return next((c for c in self.controls if c.name == name), None)


# --- locating the region ---------------------------------------------------------

def find_region(source: str) -> tuple[int, int] | None:
    """Return (start, end) line indices (inclusive) of the designer region."""
    lines = source.splitlines()
    start = next((i for i, line in enumerate(lines) if _START_RE.match(line)), None)
    if start is None:
        return None
    end = next((i for i in range(start + 1, len(lines)) if _END_RE.match(lines[i])), None)
    if end is None:
        raise FormFileError("Designer region has no '# endregion' line")
    return start, end


def find_form_class(source: str) -> str | None:
    match = _CLASS_RE.search(source)
    return match.group(1) if match else None


def is_form_source(source: str) -> bool:
    return find_form_class(source) is not None and find_region(source) is not None


def defined_methods(source: str) -> list[str]:
    """Names of methods defined (indented ``def``) in the source."""
    return _DEF_RE.findall(source)


# --- parsing -------------------------------------------------------------------------

def parse(source: str) -> FormDef:
    class_name = find_form_class(source)
    if class_name is None:
        raise FormFileError("No 'class ...(Form):' found")
    region = find_region(source)
    if region is None:
        raise FormFileError("No designer region found")
    start, end = region
    body = "\n".join(source.splitlines()[start + 1:end])
    return parse_region_body(textwrap.dedent(body), class_name)


def parse_region_body(body: str, class_name: str) -> FormDef:
    try:
        module = ast.parse(body)
    except SyntaxError as exc:
        raise FormFileError(f"Designer region is not valid Python: {exc}") from exc
    func = next((n for n in module.body
                 if isinstance(n, ast.FunctionDef) and n.name == "InitializeComponent"), None)
    if func is None:
        raise FormFileError("Designer region has no InitializeComponent method")

    form = FormDef(class_name)
    for stmt in func.body:
        if isinstance(stmt, ast.Pass) or (isinstance(stmt, ast.Expr)
                                          and isinstance(stmt.value, ast.Constant)):
            continue
        if not (isinstance(stmt, ast.Assign) and len(stmt.targets) == 1
                and _is_self_attr(stmt.targets[0])):
            raise FormFileError(f"Unexpected statement in designer region, line {stmt.lineno}")
        name = stmt.targets[0].attr
        value = stmt.value
        if isinstance(value, ast.Call) and value.args and (
                _is_self_attr(value.args[0]) or
                (isinstance(value.args[0], ast.Name) and value.args[0].id == "self")):
            form.controls.append(_parse_control(name, value, form))
        else:
            form.props[name] = _literal(value, stmt.lineno)
    return form


def _is_self_attr(node) -> bool:
    return (isinstance(node, ast.Attribute) and isinstance(node.value, ast.Name)
            and node.value.id == "self")


def _parse_control(name: str, call: ast.Call, form: FormDef) -> ControlDef:
    if not isinstance(call.func, ast.Name) or call.func.id not in CONTROL_TYPES:
        raise FormFileError(f"Unknown control type for '{name}' (line {call.lineno})")
    if len(call.args) != 1:
        raise FormFileError(f"Control '{name}' must have exactly one parent argument")
    parent_node = call.args[0]
    if isinstance(parent_node, ast.Name) and parent_node.id == "self":
        parent = None
    elif _is_self_attr(parent_node):
        parent = parent_node.attr
        if form.control(parent) is None:
            raise FormFileError(f"Parent '{parent}' of '{name}' is not defined before it")
    else:
        raise FormFileError(f"Invalid parent for control '{name}'")
    props = {kw.arg: _literal(kw.value, call.lineno) for kw in call.keywords}
    return ControlDef(call.func.id, name, parent, props)


def _literal(node, lineno):
    try:
        return ast.literal_eval(node)
    except ValueError as exc:
        raise FormFileError(f"Designer values must be literals (line {lineno})") from exc


# --- generation --------------------------------------------------------------------------

def format_value(kind: str, value) -> str:
    if kind == "color" and isinstance(value, int):
        return f"0x{value:06X}"
    return repr(value)


def _props_to_args(specs: dict, props: dict) -> list[str]:
    args = []
    for spec in specs.values():  # spec order keeps the output stable
        if spec.name not in props:
            continue
        value = props[spec.name]
        if not spec.always and value == spec.default:
            continue
        args.append((spec.name, format_value(spec.kind, value)))
    return args


def _wrap_call(prefix: str, args: list[str]) -> list[str]:
    """Fill arguments into lines of at most MAX_LINE, aligned after '('."""
    hanging = " " * len(prefix)
    lines, current = [], prefix
    for i, arg in enumerate(args):
        piece = arg + (", " if i < len(args) - 1 else ")")
        if current not in (prefix, hanging) and len(current + piece.rstrip()) > MAX_LINE:
            lines.append(current.rstrip())
            current = hanging
        current += piece
    lines.append(current)
    return lines


def generate_region(form: FormDef, indent: str = "    ") -> str:
    body = indent * 2
    lines = [indent + REGION_START, indent + "def InitializeComponent(self):"]
    for name, value in _props_to_args(Form._specs, form.props):
        lines.append(f"{body}self.{name} = {value}")
    for control in form.controls:
        cls = CONTROL_TYPES[control.type]
        parent = "self" if control.parent is None else f"self.{control.parent}"
        args = [parent] + [f"{k}={v}" for k, v in _props_to_args(cls._specs, control.props)]
        lines.extend(_wrap_call(f"{body}self.{control.name} = {control.type}(", args))
    lines.append(indent + REGION_END)
    return "\n".join(lines)


def replace_region(source: str, form: FormDef) -> str:
    region = find_region(source)
    if region is None:
        raise FormFileError("No designer region found")
    start, end = region
    lines = source.splitlines()
    indent = re.match(r"\s*", lines[start]).group(0) or "    "
    new = generate_region(form, indent).splitlines()
    trailing = "\n" if source.endswith("\n") else ""
    return "\n".join(lines[:start] + new + lines[end + 1:]) + trailing


# --- templates and refactoring ----------------------------------------------------------------

def new_form_source(class_name: str, caption: str | None = None) -> str:
    form = FormDef(class_name, {"Caption": caption or class_name, "Width": 480, "Height": 360})
    return (
        "from vp6 import *\n\n\n"
        f"class {class_name}(Form):\n"
        f"{generate_region(form)}\n\n"
        "    def Form_Load(self):\n"
        "        pass\n\n\n"
        'if __name__ == "__main__":\n'
        f"    run({class_name})\n"
    )


def new_module_source(with_main: bool = False, console: bool = False,
                      startup_form: str | None = None) -> str:
    """Source of a new module.

    with_main adds ``Main()`` (the project's Sub Main) and an
    ``if __name__ == "__main__"`` block, so the module runs on its own too:

    * console: Main() asks for a name and greets you;
    * startup_form: Main() shows that form and runs until it is closed;
    * otherwise Main() is empty.
    """
    header = "from vp6 import *\n"
    if not with_main:
        return header + "\n\n"
    if console:
        body = ('    name = input("What is your name? ")\n'
                '    print(f"Hello, {name}!")\n')
    elif startup_form:
        header += f"from {startup_form} import {startup_form}\n"
        body = ("    # Show the startup form and run until it is closed\n"
                f"    run({startup_form})\n")
    else:
        body = "    pass\n"
    return (header + "\n\n"
            "def Main():\n" + body + "\n\n"
            'if __name__ == "__main__":\n'
            "    Main()\n")


def rename_form_class(source: str, old: str, new: str) -> str:
    source = re.sub(rf"^class\s+{re.escape(old)}\s*\(", f"class {new}(", source, flags=re.M)
    return re.sub(rf"\brun\(\s*{re.escape(old)}\s*\)", f"run({new})", source)


def rename_control_references(source: str, old: str, new: str) -> str:
    """Rename event handlers (``def Old_Click``) and ``self.Old`` references
    outside the designer region (which is regenerated separately)."""
    region = find_region(source)
    lines = source.splitlines(keepends=True)
    skip = range(region[0], region[1] + 1) if region else range(0)
    handler = re.compile(rf"\bdef\s+{re.escape(old)}_(\w+)\s*\(")
    reference = re.compile(rf"\bself\.{re.escape(old)}\b")
    for i, line in enumerate(lines):
        if i in skip:
            continue
        line = handler.sub(lambda m: f"def {new}_{m.group(1)}(", line)
        lines[i] = reference.sub(f"self.{new}", line)
    return "".join(lines)


def event_stub(obj: str, event: str, args: str) -> str:
    params = "self" + (f", {args}" if args else "")
    return f"    def {obj}_{event}({params}):\n        pass\n"
