"""Your own controls: VB's UserControl.

A user control is a class designed like a form (its constituent controls in
an ``InitializeComponent`` region, laid out in the designer) and placed on
forms like any other control::

    class ctlCounter(UserControl):
        Properties = (Property("Value", "int", 0, description="The count"),
                      Property("Step", "int", 1))
        Events = ("Change(Value)",)            # what forms can handle

        # region VP6 Designer - generated by the form designer, do not edit
        def InitializeComponent(self):
            self.Surface.Width = 160
            self.Surface.Height = 40
            self.lblValue = Label(self, Caption='0', Left=8, Top=8, Width=60, Height=25)
            self.cmdUp = CommandButton(self, Caption='+', Left=76, Top=4, Width=36, Height=30)
        # endregion

        def cmdUp_Click(self):                  # its own controls' events
            self.Value += self.Step

        def UserControl_PropertyChanged(self, PropertyName):
            if PropertyName == "Value":
                self.lblValue.Caption = str(self.Value)
                self.RaiseEvent("Change", self.Value)   # the form's ctlCounter1_Change(Value)

A form places it as ``self.ctlCounter1 = ctlCounter(self, Left=16, Top=16,
Value=3)`` (with ``from ctlCounter import ctlCounter``).

* ``Properties`` declares its properties (``Property(name, kind, default,
  description=...)``, kinds as in the Properties window: "str", "int",
  "bool", "color", "font", "file", ...). They are set in the designer and in
  code; ``UserControl_PropertyChanged(PropertyName)`` follows every change
  (also each initial value, and at design time, so it can show them).
* ``Events`` declares its events, each optionally with its arguments
  (``"Change(Value)"``); ``RaiseEvent(Name, *args)`` fires one on the form,
  returning what the form's handler returned.
* Its own events are ``UserControl_Initialize`` (its controls exist, before
  the property values), ``UserControl_Resize``, ``UserControl_Click``, the
  mouse and key events, as ``Form_...`` events are for a form.
* ``Surface`` is the area its controls are on (a form inside it: its
  BackColor, ForeColor, Font, and its designed Width and Height, the size a
  new one gets on a form). ``UserMode`` is False while it is on a form in the
  designer (its controls' events don't fire then).
* As a control on a form it has Left, Top, Width, Height, Visible, Enabled,
  TabIndex, ToolTipText, Tag and ZIndex like the others.
"""

from __future__ import annotations

import re

from ._props import P, PropSpec
from .controls import _COMMON, Control, ControlArray, _geometry
from .form import Form

# A new user control's surface: the size the designer starts it with
DEFAULT_SURFACE = (161, 97)
# The surface's properties in the designer (the user control's own "form" properties)
SURFACE_PROPERTIES = ("BackColor", "ForeColor", "FontName", "FontSize", "FontBold",
                      "FontItalic", "FontUnderline", "Width", "Height")
# Its own events that also fire at design time (so it looks right on a form there)
_DESIGN_TIME_EVENTS = ("Resize", "PropertyChanged", "Initialize")
# The surface's (form) events that are the user control's own
_SURFACE_EVENTS = ("Resize", "Click", "DblClick", "MouseDown", "MouseMove", "MouseUp",
                   "KeyDown", "KeyPress", "KeyUp", "Paint")
# Its own events, in the code window's list for "UserControl" (and their arguments)
OWN_EVENTS = ("Initialize", "PropertyChanged", "Resize", "Click", "DblClick", "MouseDown",
              "MouseMove", "MouseUp", "KeyDown", "KeyPress", "KeyUp", "Paint")
OWN_EVENT_ARGS = {"PropertyChanged": "PropertyName"}
_EVENT_RE = re.compile(r"^\s*(\w+)\s*(?:\((.*)\))?\s*$")


def Property(Name: str, Kind: str = "str", Default=None, description: str = "",
             choices=None, category: str = "") -> PropSpec:
    """A user control's property: its name, kind ("str", "text", "int",
    "bool", "enum", "color", "font", "file"), default value and the
    description the Properties window shows. An "enum" takes ``choices``:
    names (numbered from 0) or (value, label) pairs. ``category``: where the
    Categorized view lists it (e.g. "Appearance"; else by its name, or Misc)."""
    if Kind == "enum" and choices and not isinstance(choices[0], tuple):
        choices = tuple((i, f"{i} - {label}") for i, label in enumerate(choices))
    if Default is None:
        Default = {"str": "", "text": "", "int": 0, "bool": False, "enum": 0,
                   "file": "", "list": []}.get(Kind)
    return P(Name, Kind, Default, choices or (), description=description, category=category)


def parse_events(events) -> tuple[tuple[str, ...], dict[str, str]]:
    """("Change(Value)", "Click") -> (("Change", "Click"), {"Change": "Value",
    "Click": ""})."""
    names, args = [], {}
    for event in events:
        match = _EVENT_RE.match(str(event))
        if match is None:
            raise ValueError(f"Not an event declaration: {event!r} (e.g. 'Change(Value)')")
        name, arguments = match.group(1), match.group(2) or ""
        names.append(name)
        args[name] = ", ".join(a.strip() for a in arguments.split(",") if a.strip())
    return tuple(names), args


def _is_handler_name(name: str) -> bool:
    """cmdUp_Click and the like (a control's event handler), not the form's own
    (Form_Load, InitializeComponent...)."""
    control, _, event = name.partition("_")
    return bool(control and event) and control != "Form" and not name.startswith("_") and \
        name != "InitializeComponent"


class _UserControlSurface(Form):
    """The form inside a user control that its constituent controls are on.
    Its events go to the user control (Form_Resize -> UserControl_Resize), and
    so do its controls' (cmdUp_Click is a method of the user control). It is
    never loaded, so it isn't in Forms."""

    _design_mode = False  # (its controls run as they will; events are held back instead)
    _vp_no_default = True  # (one per user control: no default instance)

    def __init__(self, owner: "UserControl"):
        self.__dict__["_owner"] = owner
        super().__init__()

    def __getattr__(self, name):
        # A constituent control's handler, e.g. cmdUp_Click: the user control's,
        # but not while it is on a form in the designer
        owner = self.__dict__.get("_owner")
        if owner is None or owner._design_mode or not _is_handler_name(name):
            raise AttributeError(name)
        return getattr(owner, name)

    def _fire(self, event: str, *args):
        owner = self._owner
        if event not in _SURFACE_EVENTS or (owner._design_mode and
                                            event not in _DESIGN_TIME_EVENTS):
            return None  # (Initialize is the user control's own, after its controls)
        return owner._own_event(event, *args)

    def _base_dir(self) -> str:
        return self._owner._form._base_dir()

    def _handles_paint(self) -> bool:
        return getattr(type(self._owner), "UserControl_Paint", None) is not None


class UserControl(Control):
    """The base class of your own controls (see the module's documentation)."""

    TypeName = "UserControl"
    DefaultEvent = ""
    DefaultSize = DEFAULT_SURFACE
    InToolbox = False  # (your classes are, from the project)
    IsContainer = False
    Events: tuple[str, ...] = ()
    EventArgs: dict[str, str] = {}
    Properties = (*_geometry(*DEFAULT_SURFACE), *_COMMON)
    _BASE_PROPERTIES = Properties

    def __init_subclass__(cls, **kwargs):
        own = cls.__dict__.get("Properties")
        if own is not None and own is not UserControl._BASE_PROPERTIES and \
                not cls.__dict__.get("_merged"):
            names = {spec.name for spec in own}
            cls._author_properties = tuple(spec.name for spec in own)
            cls.Properties = tuple(s for s in UserControl._BASE_PROPERTIES
                                   if s.name not in names) + tuple(own)
            cls._merged = True
        elif "_author_properties" not in cls.__dict__:
            inherited = getattr(cls, "_author_properties", ())
            cls._author_properties = inherited
        events = cls.__dict__.get("Events")
        if events is not None:
            cls.Events, args = parse_events(events)
            cls.EventArgs = args
        cls.TypeName = cls.__name__
        cls.InToolbox = True
        if cls.Events and not cls.__dict__.get("DefaultEvent"):
            cls.DefaultEvent = cls.Events[0]
        super().__init_subclass__(**kwargs)

    _author_properties: tuple[str, ...] = ()

    # -- being made ---------------------------------------------------------------------------
    def _create_widget(self, parent):
        surface = _UserControlSurface(self)
        self.__dict__["_surface"] = surface
        widget = surface._widget
        widget.setParent(parent)
        return widget

    def _build_widget(self) -> None:
        super()._build_widget()
        surface = self._surface
        initialize = getattr(self, "InitializeComponent", None)
        if initialize is not None and not self.__dict__.get("_initialized"):
            self.__dict__["_initialized"] = True
            initialize()
            surface._layout_aligned()
            surface._apply_tab_order()
            self.__dict__["_design_size"] = (surface._values.get("Width", DEFAULT_SURFACE[0]),
                                             surface._values.get("Height", DEFAULT_SURFACE[1]))
            self._own_event("Initialize")

    def _init_values(self, props: dict) -> None:
        width, height = self.__dict__.get("_design_size", self.DefaultSize)
        props = {"Width": width, "Height": height, **props}  # (a new one: its designed size)
        super()._init_values(props)

    def _owner_form(self):
        return self._surface  # (its own controls are on its surface)

    def _container_widget(self):
        return self._surface._container_widget()

    def __setattr__(self, name, value):
        # `self.cmdUp = CommandButton(self, ...)` in InitializeComponent names it
        if isinstance(value, (Control, ControlArray)):
            if not value._name:
                value.__dict__["_name"] = name
            object.__setattr__(self, name, value)
            return
        super().__setattr__(name, value)

    # -- its properties and events ------------------------------------------------------------
    def _set_prop(self, name: str, value) -> None:
        super()._set_prop(name, value)
        if name in self._author_properties:
            self._own_event("PropertyChanged", name)

    def _own_event(self, event: str, *args):
        """Its own event: UserControl_Resize, ..._PropertyChanged and so on."""
        handler = getattr(type(self), f"UserControl_{event}", None)
        if handler is None:
            return None
        from .app import call_handler

        return call_handler(handler.__get__(self), *args)

    def RaiseEvent(self, Name: str, *args):
        """Fire one of its Events on the form it is on (the form's
        ctlName_Event handler gets the arguments); returns what the handler
        returned (e.g. True to cancel)."""
        if Name not in self.Events:
            raise ValueError(f"{self.TypeName} '{self.Name}': no event {Name!r} in its Events "
                             f"{self.Events}")
        return self._fire(Name, *args)

    @property
    def Surface(self) -> Form:
        """The area its controls are on: BackColor, ForeColor, Font..., and its
        designed Width and Height."""
        return self._surface

    @property
    def UserMode(self) -> bool:
        """False while it is on a form in the designer, True when the program runs."""
        return not self._design_mode

    @property
    def Controls(self) -> list:
        """Its constituent controls."""
        return list(self._surface._controls)


# --- the IDE: a project's user controls among the control types ------------------------------

def register_user_control(cls: type) -> None:
    """Make a project's user control a control type (the designer, the
    Toolbox, the Properties window and form files know it by its class name).
    A built-in control's name can't be taken."""
    from .controls import CONTROL_TYPES

    if not (isinstance(cls, type) and issubclass(cls, UserControl)):
        raise TypeError(f"{cls!r} is not a UserControl")
    if cls.TypeName in _BUILTIN_TYPES:
        raise ValueError(f"{cls.TypeName} is the name of a built-in control")
    CONTROL_TYPES[cls.TypeName] = cls


def unregister_user_controls() -> None:
    """Forget every registered user control (the project was closed)."""
    from .controls import CONTROL_TYPES

    for name in [n for n in CONTROL_TYPES if n not in _BUILTIN_TYPES]:
        del CONTROL_TYPES[name]


def user_control_types() -> list[str]:
    """The registered user controls' names."""
    from .controls import CONTROL_TYPES

    return [n for n in CONTROL_TYPES if n not in _BUILTIN_TYPES]


def _builtin_types() -> frozenset:
    from .controls import CONTROL_TYPES

    return frozenset(CONTROL_TYPES)


_BUILTIN_TYPES = _builtin_types()


def load_user_control(path: str, text: str | None = None) -> type:
    """A user control's class from its file (or ``text``, e.g. not saved yet),
    as a module named after the file, the way forms import it. Its
    DefaultSize is its designed surface's size. Raises what its code raises."""
    import os
    import sys
    import types

    from . import formfile

    if text is None:
        with open(path, encoding="utf-8") as f:
            text = f.read()
    form_def = formfile.parse(text)
    module_name = os.path.splitext(os.path.basename(path))[0]
    module = types.ModuleType(module_name)
    module.__file__ = os.path.abspath(path)
    sys.modules[module_name] = module
    exec(compile(text, path, "exec"), module.__dict__)  # noqa: S102 - the project's code
    cls = getattr(module, form_def.class_name, None)
    if not (isinstance(cls, type) and issubclass(cls, UserControl)):
        raise TypeError(f"{os.path.basename(path)} has no UserControl class "
                        f"{form_def.class_name}")
    cls.DefaultSize = (form_def.props.get("Width", DEFAULT_SURFACE[0]),
                       form_def.props.get("Height", DEFAULT_SURFACE[1]))
    return cls
