"""Kitchen Sink user control: a star rating, a control of the project's own (VB's
UserControl). Its properties (Value, Max, StarColor, Locked) are set in the Properties
window like any control's; its events (Change, Hover) are handled on the form it is on.
Its stars are a control array of Labels on its surface."""

from vp6 import *

LIT, UNLIT = "★", "☆"  # a filled and an empty star


class ctlRating(UserControl):
    Properties = (
        Property("Value", "int", 3, description="How many stars are lit (0 to Max)"),
        Property("Max", "int", 5, description="How many stars there are (1 to 5)"),
        Property("StarColor", "color", 0x00C0FF, description="The lit stars' color"),
        Property("Locked", "bool", False, description="Clicks don't change the Value"),
    )
    Events = ("Change(Value)", "Hover(Stars)")

    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Surface.Width = 160
        self.Surface.Height = 36
        self.lblStar = ControlArray()
        self.lblStar[0] = Label(self, Caption='☆', Left=0, Top=0, Width=32, Height=36, Alignment=2,
                                BackStyle=0, FontSize=22)
        self.lblStar[1] = Label(self, Caption='☆', Left=32, Top=0, Width=32, Height=36,
                                Alignment=2, BackStyle=0, FontSize=22)
        self.lblStar[2] = Label(self, Caption='☆', Left=64, Top=0, Width=32, Height=36,
                                Alignment=2, BackStyle=0, FontSize=22)
        self.lblStar[3] = Label(self, Caption='☆', Left=96, Top=0, Width=32, Height=36,
                                Alignment=2, BackStyle=0, FontSize=22)
        self.lblStar[4] = Label(self, Caption='☆', Left=128, Top=0, Width=32, Height=36,
                                Alignment=2, BackStyle=0, FontSize=22)
    # endregion

    def UserControl_PropertyChanged(self, PropertyName):
        # Every property change comes here: from the designer, from code, and each
        # initial value (also while it is on a form in the designer)
        if PropertyName == "Max" and not 1 <= self.Max <= 5:
            self.Max = min(max(self.Max, 1), 5)  # (comes back here)
            return
        if PropertyName in ("Value", "Max") and not 0 <= self.Value <= self.Max:
            self.Value = min(max(self.Value, 0), self.Max)
            return
        self.show_stars(self.Value)
        if PropertyName == "Value":
            self.RaiseEvent("Change", self.Value)  # the form's ctlName_Change(Value)

    def show_stars(self, lit: int) -> None:
        for star in self.lblStar:
            star.Visible = star.Index < self.Max
            on = star.Index < lit
            star.Caption = LIT if on else UNLIT
            star.ForeColor = self.StarColor if on else None

    # --- its own controls' events -------------------------------------------------------------
    def lblStar_Click(self, Index):
        if not self.Locked:
            self.Value = Index + 1

    def lblStar_MouseMove(self, Index, Button, Shift, X, Y):
        if not self.Locked:
            self.RaiseEvent("Hover", Index + 1)  # the rating the mouse is on
