"""Kitchen Sink: the explorer window.

A tree on the left lists the topics; choosing one shows its page, a form of
its own (pgText.py, pgLists.py, ...), in the content pane with ShowIn. Keep
this project up to date: when VP6 gains a control, event or API function,
demonstrate it on a page (tests/test_kitchen_sink.py checks this).
"""

from vp6 import *
from pgArrays import pgArrays
from pgButtons import pgButtons
from pgDialogs import pgDialogs
from pgEmbedded import pgEmbedded
from pgGlobals import pgGlobals
from pgIntro import pgIntro
from pgKeyboard import pgKeyboard
from pgLayout import pgLayout
from pgLists import pgLists
from pgMenus import pgMenus
from pgMouse import pgMouse
from pgPictures import pgPictures
from pgSchemes import SCHEMES, pgSchemes
from pgScrollBars import pgScrollBars
from pgScrolling import pgScrolling
from pgTabs import pgTabs
from pgText import pgText
from pgTimer import pgTimer
from pgTree import pgTree
from pgValues import pgValues
from pgZOrder import pgZOrder

# The page shown for each key of the index (the TreeView's nodes)
PAGES = {
    "intro": pgIntro, "text": pgText, "buttons": pgButtons, "lists": pgLists,
    "scrollbars": pgScrollBars, "values": pgValues, "pictures": pgPictures,
    "zorder": pgZOrder, "tree": pgTree, "tabs": pgTabs, "timer": pgTimer,
    "layout": pgLayout, "scrolling": pgScrolling, "embedded": pgEmbedded,
    "dialogs": pgDialogs, "schemes": pgSchemes, "keyboard": pgKeyboard, "mouse": pgMouse,
    "arrays": pgArrays, "menus": pgMenus, "globals": pgGlobals,
}

HELP = """Kitchen Sink keys:

F1\tthis help (Help > Keys: a menu Shortcut)
Ctrl+Q\tEnd the program immediately (File > End)
Enter / Esc\tthe Default / Cancel button (see the Keyboard page)"""


class Form1(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'VP6 Kitchen Sink'
        self.Width = 900
        self.Height = 600
        self.KeyPreview = True
        self.sbStatus = StatusBar(self, Left=0, Top=572, Width=900, Height=28,
                                  Panels=['Ready|status|spring', '|caps|caps 56 center', '|clock|time 90 center'],
                                  ToolTipText='A StatusBar: click the clock to see the date')
        self.picNav = PictureBox(self, Left=0, Top=0, Width=220, Height=572, BorderStyle=0,
                                 Align=3, TabIndex=3)
        self.tvwIndex = TreeView(self.picNav, Left=0, Top=0, Width=220, Height=572,
                                 Items=['Introduction|intro', 'Controls|controls', '    Text and labels|text', '    Buttons and options|buttons', '    Lists|lists', '    Scroll bars|scrollbars', '    Sliders, progress and spinners|values', '    Pictures|pictures', '    Lines and z-order|zorder', '    TreeView|tree', '    TabStrip|tabs', '    Timer|timer', 'Layout|layout_section', '    Docked panes and Splitter|layout', '    Scrolling|scrolling', '    Forms inside forms|embedded', 'Forms and dialogs|forms_section', '    Dialogs|dialogs', '    Color schemes|schemes', '    Keyboard|keyboard', '    Mouse|mouse', 'Programming|programming', '    Control arrays|arrays', '    Menus|menus', '    App, Screen, Clipboard...|globals'],
                                 TabIndex=4,
                                 ToolTipText='The topics: its nodes were typed in the designer (Items)')
        self.splNav = Splitter(self, Left=220, Top=0, Width=6, Height=572, MinSize=150,
                               ToolTipText='Drag to resize the navigation pane')
        self.picHeader = PictureBox(self, Left=226, Top=0, Width=674, Height=44, BorderStyle=0,
                                    Align=1, TabIndex=5)
        self.lblTitle = Label(self.picHeader, Caption='Introduction', Left=16, Top=8, Width=640,
                              Height=30, FontSize=16, FontBold=True, TabIndex=6)
        self.picContent = PictureBox(self, Left=226, Top=44, Width=674, Height=528, BorderStyle=0,
                                     Align=5, ScrollBars=3, TabIndex=7,
                                     ToolTipText='The pages are forms of their own, shown here with ShowIn')
        self.mnuFile = Menu(self, Caption='&File')
        self.mnuFileEnd = Menu(self.mnuFile, Caption='&End (no questions asked)',
                               Shortcut='Ctrl+Q')
        self.mnuFileSep = Menu(self.mnuFile, Caption='-')
        self.mnuFileClose = Menu(self.mnuFile, Caption='&Close')
        self.mnuView = Menu(self, Caption='&View')
        self.mnuViewNav = Menu(self.mnuView, Caption='&Navigation pane', Checked=True)
        self.mnuViewSep = Menu(self.mnuView, Caption='-')
        self.mnuScheme = ControlArray()
        self.mnuScheme[0] = Menu(self.mnuView, Caption='&System colors', Checked=True)
        self.mnuScheme[1] = Menu(self.mnuView, Caption='&Light')
        self.mnuScheme[2] = Menu(self.mnuView, Caption='&Dark')
        self.mnuScheme[3] = Menu(self.mnuView, Caption='Follow the &IDE')
        self.mnuBookmarks = Menu(self, Caption='&Bookmarks')
        self.mnuBookmark = ControlArray()
        self.mnuBookmark[0] = Menu(self.mnuBookmarks, Caption='&Introduction', Tag='intro')
        self.mnuHelp = Menu(self, Caption='&Help', NegotiatePosition=3)
        self.mnuHelpKeys = Menu(self.mnuHelp, Caption='&Keys', Shortcut='F1')
        self.mnuHelpAbout = Menu(self.mnuHelp, Caption='&About')
    # endregion

    # --- the window ---------------------------------------------------------------------------
    def Form_Load(self):
        self.pages = {}  # the pages shown so far, by key: shown again, not loaded again
        self.scheme = 0  # the index of the color scheme in SCHEMES
        for node in self.tvwIndex.Nodes:
            node.Expanded = True
        self.show_page("intro")
        Debug.Print("Form_Load:", App.Title, "- screen", Screen.Width, "x", Screen.Height)

    def Form_Unload(self):
        # Returning True cancels closing (VB's Cancel = 1)
        if MsgBox("Close the Kitchen Sink?", vpYesNo + vpQuestion) == vpNo:
            return True
        # The pages shown in this window are unloaded with it; a page popped out
        # into a window of its own too
        for page in self.pages.values():
            page.Unload()

    def status(self, text):
        self.sbStatus.Panels("status").Text = text  # the StatusBar's first panel

    def sbStatus_PanelClick(self, Panel):
        # The clock panel shows the time or the date: a click switches
        if Panel.Key == "clock":
            Panel.Style = vpSbrDate if Panel.Style == vpSbrTime else vpSbrTime
            self.status("The clock shows the " + ("date" if Panel.Style == vpSbrDate
                                                    else "time"))

    # --- pages ----------------------------------------------------------------------------------
    def show_page(self, key):
        """Show the page with this key in the content pane (it replaces the one
        there, which is hidden and deactivated, not unloaded)."""
        page = self.pages.get(key)
        if page is None:
            page = PAGES[key]()
            page.shell = self  # pages that talk to this window use it
            self.pages[key] = page
        node = self.tvwIndex.Nodes(key)
        self.tvwIndex.SelectedItem = node  # selected by code: no NodeClick
        node.EnsureVisible()
        self.lblTitle.Caption = node.Text
        page.ShowIn(self.picContent)
        self.picContent.ScrollTop = self.picContent.ScrollLeft = 0
        self.status(node.FullPath)

    def page_titles(self):
        """(key, title) of every page, in the index's order (the Menus page)."""
        return [(node.Key, node.Text) for node in self.tvwIndex.Nodes if node.Key in PAGES]

    def tvwIndex_NodeClick(self, Node):
        if Node.Key in PAGES:
            self.show_page(Node.Key)
        elif Node.Child is not None:  # a section: its first page
            self.show_page(Node.Child.Key)

    # --- the docked panes: their Resize events size what is on them -----------------------------
    def picNav_Resize(self):
        self.tvwIndex.Move(0, 0, self.picNav.Width, self.picNav.Height)

    def picHeader_Resize(self):
        self.lblTitle.Width = max(self.picHeader.Width - 32, 16)

    def splNav_Moved(self):
        self.status(f"The navigation pane is now {self.picNav.Width} pixels wide")

    def picContent_Scroll(self):
        self.status(f"Scrolled to {self.picContent.ScrollLeft}, {self.picContent.ScrollTop}")

    def show_navigation(self, visible):
        """Show or hide the navigation pane (a hidden docked pane takes no space)."""
        self.picNav.Visible = self.splNav.Visible = visible
        self.mnuViewNav.Checked = visible
        layout = self.pages.get("layout")
        if layout is not None:
            layout.chkNav.Value = vpChecked if visible else vpUnchecked

    # --- color schemes ------------------------------------------------------------------------------
    def set_scheme(self, index):
        """The window's color scheme, chosen on the Color schemes page or in the
        View menu (both kept in step)."""
        if index == self.scheme:
            return
        self.scheme = index
        self.ColorScheme = SCHEMES[index]
        for item in self.mnuScheme:  # a menu control array
            item.Checked = item.Index == index
        page = self.pages.get("schemes")
        if page is not None:
            page.optScheme[index].Value = True

    # --- menus (Tools > Menu Editor) ---------------------------------------------------------------
    def mnuFileEnd_Click(self):
        End()  # ends at once, without Form_Unload

    def mnuFileClose_Click(self):
        self.Unload()

    def mnuView_Click(self):
        # A menu's Click fires just before it opens: a place to update its items
        self.mnuViewNav.Checked = self.picNav.Visible

    def mnuViewNav_Click(self):
        self.show_navigation(not self.picNav.Visible)

    def mnuScheme_Click(self, Index):
        self.set_scheme(Index)

    def add_bookmark(self, key, title):
        """A new item in the Bookmarks menu (a menu control array)."""
        if any(item.Tag == key for item in self.mnuBookmark):
            self.status(f"{title} is already bookmarked")
            return
        item = Load(self.mnuBookmark, self.mnuBookmark.UBound + 1)  # after the last one
        item.Caption, item.Tag, item.Visible = title, key, True
        self.status(f"Bookmarked {title}: see the Bookmarks menu")

    def mnuBookmark_Click(self, Index):
        self.show_page(self.mnuBookmark[Index].Tag)

    def mnuHelpKeys_Click(self):
        MsgBox(HELP, vpInformation, "Kitchen Sink help")

    def mnuHelpAbout_Click(self):
        controls = sum(isinstance(c, Control) for c in self.Controls)
        MsgBox(f"{App.Title}\n\n"
               f"Forms loaded: {Forms.Count} (the pages shown so far, and this window)\n"
               f"Controls on this window: {controls}\n"
               f"Screen: {Screen.Width} x {Screen.Height}\n"
               f"Folder: {App.Path}",
               vpInformation, "About")


if __name__ == "__main__":
    run(Form1)
