"""Kitchen Sink main form: every VP6 control and most of the API in one place.

Keep this project up to date: when VP6 gains a control, event or API
function, demonstrate it here (tests/test_kitchen_sink.py checks this).
"""

import time

from vp6 import *
from frmDialog import frmDialog

HELP = """Kitchen Sink keys:

F1\tthis help (Form_KeyDown with KeyPreview)
Enter\tGreet (the Default button)
Esc\tClose (the Cancel button)
Ctrl+Q\tEnd the program immediately (End)"""

SWATCH_COLORS = {
    "Default": None,
    "Red": vpRed,
    "Green": RGB(0, 160, 0),
    "Blue": vpBlue,
    "QB Yellow": QBColor(14),
}


class Form1(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'VP6 Kitchen Sink'
        self.Width = 760
        self.Height = 532
        self.KeyPreview = True
        self.fraText = Frame(self, Caption='Text and buttons', Left=16, Top=16, Width=348,
                             Height=236, TabIndex=1)
        self.lblName = Label(self.fraText, Caption='&Name:', Left=16, Top=32, Width=60, Height=25,
                             TabIndex=2)
        self.txtName = TextBox(self.fraText, Text='', Left=80, Top=28, Width=160, Height=25,
                               TabIndex=3, ToolTipText='Type a name, then Greet or Add')
        self.cmdGreet = CommandButton(self.fraText, Caption='&Greet', Left=248, Top=26, Width=84,
                                      Height=30, Default=True, TabIndex=4,
                                      ToolTipText='Default button: Enter clicks it')
        self.lblNotes = Label(self.fraText, Caption='Notes:', Left=16, Top=72, Width=60, Height=25,
                              TabIndex=5)
        self.txtNotes = TextBox(self.fraText, MultiLine=True,
                                Text='A multi-line\nTextBox with\na vertical scroll bar', Left=80,
                                Top=68, Width=252, Height=80, ScrollBars=2, TabIndex=6)
        self.lblPassword = Label(self.fraText, Caption='Password:', Left=16, Top=164, Width=64,
                                 Height=25, TabIndex=7)
        self.txtPassword = TextBox(self.fraText, Text='', Left=80, Top=160, Width=160, Height=25,
                                   PasswordChar='*', TabIndex=8)
        self.lblUpper = Label(self.fraText, Caption='UPPER:', Left=16, Top=200, Width=60,
                              Height=25, TabIndex=9)
        self.txtUpper = TextBox(self.fraText, Text='', Left=80, Top=196, Width=160, Height=25,
                                TabIndex=10,
                                ToolTipText='KeyPress turns what you type into upper case')
        self.fraOptions = Frame(self, Caption='Options', Left=380, Top=16, Width=364, Height=236,
                                TabIndex=11)
        self.optSystem = OptionButton(self.fraOptions, Caption='System colors', Left=16, Top=24,
                                      Width=150, Height=25, Value=True, TabIndex=12)
        self.optLight = OptionButton(self.fraOptions, Caption='Light', Left=16, Top=48, Width=150,
                                     Height=25, TabIndex=13)
        self.optDark = OptionButton(self.fraOptions, Caption='Dark', Left=16, Top=72, Width=150,
                                    Height=25, TabIndex=14)
        self.optIDE = OptionButton(self.fraOptions, Caption='Follow the IDE', Left=16, Top=96,
                                   Width=150, Height=25, TabIndex=15)
        self.chkBold = CheckBox(self.fraOptions, Caption='Bold clock', Left=184, Top=24, Width=160,
                                Height=25, TabIndex=16)
        self.chkTimer = CheckBox(self.fraOptions, Caption='Clock running', Left=184, Top=48,
                                 Width=160, Height=25, Value=1, TabIndex=17)
        self.chkPicture = CheckBox(self.fraOptions, Caption='Show picture', Left=184, Top=72,
                                   Width=160, Height=25, Value=1, TabIndex=18)
        self.lblSize = Label(self.fraOptions, Caption='Font size:', Left=16, Top=132, Width=76,
                             Height=25, TabIndex=19)
        self.hsbSize = HScrollBar(self.fraOptions, Left=96, Top=136, Width=180, Height=17, Min=8,
                                  Max=18, Value=12, LargeChange=2, TabIndex=20)
        self.lblSizeValue = Label(self.fraOptions, Caption='12', Left=284, Top=132, Width=60,
                                  Height=25, TabIndex=21)
        self.cboColors = ComboBox(self.fraOptions, Style=2, Left=16, Top=164, Width=160, Height=25,
                                  List=['Default', 'Red', 'Green', 'Blue', 'QB Yellow'],
                                  Text='Default', TabIndex=22)
        self.lblSwatch = Label(self.fraOptions, Caption='Color sample', Left=184, Top=164,
                               Width=164, Height=25, Alignment=2, BorderStyle=1, TabIndex=23)
        self.cboFree = ComboBox(self.fraOptions, Left=16, Top=198, Width=160, Height=25,
                                List=['apple', 'banana', 'cherry'], Text='Type or pick',
                                TabIndex=24)
        self.lblEcho = Label(self.fraOptions, Caption='', Left=184, Top=198, Width=164, Height=25,
                             TabIndex=25)
        self.lstItems = ListBox(self, Left=16, Top=268, Width=200, Height=160,
                                List=['Alpha', 'Bravo', 'Charlie'], Sorted=True, TabIndex=26)
        self.cmdAdd = CommandButton(self, Caption='&Add', Left=224, Top=268, Width=97, Height=33,
                                    Enabled=False, TabIndex=27,
                                    ToolTipText='Adds the Name text to the list')
        self.cmdRemove = CommandButton(self, Caption='&Remove', Left=224, Top=308, Width=97,
                                       Height=33, TabIndex=28)
        self.cmdCount = CommandButton(self, Caption='Count to &100', Left=224, Top=348, Width=97,
                                      Height=33, TabIndex=29,
                                      ToolTipText='A long loop that stays responsive thanks to DoEvents')
        self.vsbLevel = VScrollBar(self, Left=336, Top=268, Width=17, Height=160, Max=100,
                                   Value=50, LargeChange=10, TabIndex=30)
        self.lblLevel = Label(self, Caption='50', Left=360, Top=268, Width=40, Height=25,
                              TabIndex=31)
        self.picLogo = PictureBox(self, Left=416, Top=268, Width=160, Height=120,
                                  Picture='vp6.png', Stretch=True, TabIndex=32)
        self.lblOnPicture = Label(self.picLogo, Caption='Click to set a Tag', Left=8, Top=88,
                                  Width=144, Height=25, Alignment=2, BackColor=0xFFFFFF,
                                  ForeColor=0x000000, TabIndex=33)
        self.lblClock = Label(self, Caption='00:00:00', Left=592, Top=268, Width=152, Height=25,
                              Alignment=2, FontSize=14, TabIndex=34)
        self.cmdDialog = CommandButton(self, Caption='&Dialog...', Left=592, Top=308, Width=152,
                                       Height=33, TabIndex=35,
                                       ToolTipText='Shows a modal dialog (with its own dark color scheme)')
        self.cmdClipboard = CommandButton(self, Caption='Copy &name', Left=592, Top=348, Width=152,
                                          Height=33, TabIndex=36)
        self.cmdAbout = CommandButton(self, Caption='A&bout', Left=592, Top=388, Width=152,
                                      Height=33, TabIndex=37)
        self.lblZRed = Label(self, Caption='Red: ZIndex 2', Left=16, Top=440, Width=132, Height=40,
                             Alignment=2, BackColor=0x0000FF, ForeColor=0xFFFFFF, TabIndex=40,
                             ToolTipText='Click to bring to front (ZOrder 0)', ZIndex=2)
        self.lblZBlue = Label(self, Caption='Blue: ZIndex 1', Left=80, Top=452, Width=132,
                              Height=40, Alignment=2, BackColor=0xFF0000, ForeColor=0xFFFFFF,
                              TabIndex=41, ToolTipText='Click to bring to front (ZOrder 0)',
                              ZIndex=1)
        self.cmdSwapZ = CommandButton(self, Caption='Swap &Z-order', Left=224, Top=448, Width=120,
                                      Height=33, TabIndex=42,
                                      ToolTipText="Swaps the two labels' ZIndex values")
        self.cmdClose = CommandButton(self, Caption='&Close', Left=647, Top=440, Width=97,
                                      Height=33, Cancel=True, TabIndex=38,
                                      ToolTipText='Cancel button: Esc clicks it')
        self.tmrClock = Timer(self, Left=600, Top=440, Interval=1000)
        self.lblStatus = Label(self, Caption='Ready', Left=16, Top=496, Width=728, Height=25,
                               BorderStyle=1, TabIndex=39)
    # endregion

    # --- form events -------------------------------------------------------------------
    def Form_Load(self):
        Debug.Print("Form_Load:", App.Title, "- screen", Screen.Width, "x", Screen.Height)
        self.tmrClock_Timer()
        controls = sum(isinstance(c, Control) for c in self.Controls)
        self.lblStatus.Caption = f"{controls} controls loaded. Press F1 for help."

    def Form_Resize(self):
        # Keep the status bar along the bottom edge
        self.lblStatus.Move(16, self.ScaleHeight - 36, self.ScaleWidth - 32)

    def Form_MouseMove(self, Button, Shift, X, Y):
        self.lblStatus.Caption = f"Mouse at {X}, {Y}"

    def Form_KeyDown(self, KeyCode, Shift):
        # KeyPreview = True: the form sees keys before its controls
        if KeyCode == vpKeyF1:
            MsgBox(HELP, vpInformation, "Kitchen Sink help")
            return 0  # handled: the focused control doesn't get the key
        if KeyCode == vpKeyQ and Shift & vpCtrlMask:
            End()  # ends at once, without Form_Unload

    def Form_Unload(self):
        # Returning True cancels closing (VB's Cancel = 1)
        return MsgBox("Close the Kitchen Sink?", vpYesNo + vpQuestion) == vpNo

    # --- text and buttons --------------------------------------------------------------------
    def fraText_Click(self):
        self.lblStatus.Caption = "Frames are containers; click events work on them too"

    def txtName_Change(self):
        self.cmdAdd.Enabled = bool(self.txtName.Text.strip())

    def cmdGreet_Click(self):
        name = self.txtName.Text.strip()
        if not name:
            Beep()
            name = InputBox("What is your name?", "Greeting", "World")
            if not name:
                return
            self.txtName.Text = name
        MsgBox(f"Hello, {name}!", vpInformation, "Greeting")

    def txtNotes_GotFocus(self):
        self.lblStatus.Caption = "Editing the multi-line TextBox"

    def txtPassword_LostFocus(self):
        self.lblStatus.Caption = f"The password has {len(self.txtPassword.Text)} characters"

    def txtUpper_KeyPress(self, KeyAscii):
        # Returning a character code replaces the typed key (0 would swallow it)
        return ord(chr(KeyAscii).upper())

    # --- options ---------------------------------------------------------------------------------
    def optSystem_Click(self):
        self.ColorScheme = vpSchemeSystem

    def optLight_Click(self):
        self.ColorScheme = vpSchemeLight

    def optDark_Click(self):
        self.ColorScheme = vpSchemeDark

    def optIDE_Click(self):
        self.ColorScheme = vpSchemeIDE

    def chkBold_Click(self):
        self.lblClock.FontBold = self.chkBold.Value == vpChecked

    def chkTimer_Click(self):
        self.tmrClock.Enabled = self.chkTimer.Value == vpChecked

    def chkPicture_Click(self):
        self.picLogo.Visible = self.chkPicture.Value == vpChecked

    def hsbSize_Change(self):
        self.lblSizeValue.Caption = str(self.hsbSize.Value)
        self.lblSwatch.FontSize = self.hsbSize.Value

    def hsbSize_Scroll(self):
        self.hsbSize_Change()  # update live while the thumb is dragged

    def cboColors_Click(self):
        color = SWATCH_COLORS[self.cboColors.Text]
        self.lblSwatch.BackColor = color
        self.lblSwatch.ForeColor = vpWhite if color in (vpRed, vpBlue, RGB(0, 160, 0)) else None

    def cboFree_Change(self):
        self.lblEcho.Caption = self.cboFree.Text

    # --- list ------------------------------------------------------------------------------------
    def lstItems_Click(self):
        self.lblStatus.Caption = (f"Selected {self.lstItems.Text!r} "
                                  f"({self.lstItems.ListIndex + 1} of {self.lstItems.ListCount})")

    def lstItems_DblClick(self):
        MsgBox(self.lstItems.Text, vpOKOnly, "You double-clicked")

    def cmdAdd_Click(self):
        self.lstItems.AddItem(self.txtName.Text.strip())
        self.txtName.Text = ""
        self.txtName.SetFocus()

    def cmdRemove_Click(self):
        if self.lstItems.ListIndex < 0:
            MsgBox("Select an item first.", vpExclamation)
            return
        self.lstItems.RemoveItem(self.lstItems.ListIndex)

    def cmdCount_Click(self):
        for i in range(1, 101):
            self.cmdCount.Caption = f"Counting {i}"
            DoEvents()  # keep the window responsive during the loop
            time.sleep(0.01)
        self.cmdCount.Caption = "Count to &100"

    def vsbLevel_Change(self):
        self.lblLevel.Caption = str(self.vsbLevel.Value)

    # --- picture ---------------------------------------------------------------------------------
    def picLogo_Click(self):
        self.lblStatus.Caption = f"PictureBox clicked (Tag: {self.picLogo.Tag or 'none'})"

    def picLogo_MouseDown(self, Button, Shift, X, Y):
        if Button == vpRightButton:
            self.lblStatus.Caption = f"Right button at {X}, {Y} on the picture"

    def lblOnPicture_Click(self):
        # A Label inside the PictureBox container
        tag = InputBox("A Tag for the picture:", "Tag", self.picLogo.Tag)
        if tag:
            self.picLogo.Tag = tag
            self.lblOnPicture.Caption = tag

    def tmrClock_Timer(self):
        self.lblClock.Caption = time.strftime("%H:%M:%S")

    # --- z-order -------------------------------------------------------------------------------
    def cmdSwapZ_Click(self):
        # ZIndex: higher values are drawn on top, and changes apply at once
        self.lblZRed.ZIndex, self.lblZBlue.ZIndex = self.lblZBlue.ZIndex, self.lblZRed.ZIndex
        self.show_z_order()

    def lblZRed_Click(self):
        self.lblZRed.ZOrder(0)  # VB's ZOrder method: 0 = bring to front, 1 = send to back
        self.show_z_order()

    def lblZBlue_Click(self):
        self.lblZBlue.ZOrder(0)
        self.show_z_order()

    def show_z_order(self):
        self.lblZRed.Caption = f"Red: ZIndex {self.lblZRed.ZIndex}"
        self.lblZBlue.Caption = f"Blue: ZIndex {self.lblZBlue.ZIndex}"

    # --- other forms, clipboard, about -----------------------------------------------------------
    def cmdDialog_Click(self):
        dialog = frmDialog()
        Load(dialog)
        dialog.Show(vpModal, self)  # waits until the dialog is hidden
        if dialog.Result:
            self.lstItems.AddItem(dialog.Result)
        Unload(dialog)

    def cmdClipboard_Click(self):
        Clipboard.SetText(self.txtName.Text)
        self.lblStatus.Caption = f"Copied {Clipboard.GetText()!r} to the clipboard"

    def cmdAbout_Click(self):
        buttons = sum(isinstance(c, CommandButton) for c in self.Controls)
        MsgBox(f"{App.Title}\n\n"
               f"Forms loaded: {Forms.Count}\n"
               f"Controls: {len(self.Controls)} ({buttons} buttons)\n"
               f"Screen: {Screen.Width} x {Screen.Height}\n"
               f"Folder: {App.Path}",
               vpInformation, "About")

    def cmdClose_Click(self):
        self.Unload()


if __name__ == "__main__":
    run(Form1)
