"""A modal dialog with its own color scheme (ColorScheme = 3 - Dark) and window icon
(Icon), used through its default instance (frmDialog.Show(vpModal): no frmDialog()
needed), telling why it closed in Form_QueryUnload."""

from vp6 import *


class frmDialog(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Add an item'
        self.Width = 320
        self.Height = 146
        self.StartUpPosition = 1
        self.BorderStyle = 3
        self.ColorScheme = 3
        self.Icon = 'images/star.png'
        self.lblPrompt = Label(self, Caption='New list item:', Left=16, Top=16, Width=288,
                               Height=25, TabIndex=1)
        self.txtItem = TextBox(self, Text='', Left=16, Top=44, Width=288, Height=25, TabIndex=2)
        self.cmdOK = CommandButton(self, Caption='OK', Left=112, Top=96, Width=90, Height=33,
                                   Default=True, TabIndex=3)
        self.cmdCancel = CommandButton(self, Caption='Cancel', Left=214, Top=96, Width=90,
                                       Height=33, Cancel=True, TabIndex=4)
    # endregion

    def Form_Load(self):
        # (its default instance is used again: Form_Load runs each time it is loaded)
        self.Result = None
        self.ClosedBy = ""
        self.txtItem.Text = ""

    def Form_QueryUnload(self, UnloadMode):
        # Before Form_Unload: why it is closing (returning True would keep it open)
        self.ClosedBy = {vpFormControlMenu: "its close button", vpFormCode: "Unload in code",
                         vpAppTaskManager: "Ctrl+C", vpFormOwner: "its owner form"}.get(
            UnloadMode, f"UnloadMode {UnloadMode}")

    def Form_Activate(self):
        self.txtItem.SetFocus()

    def cmdOK_Click(self):
        self.Result = self.txtItem.Text.strip() or None
        self.Hide()  # ends Show(vpModal); the caller reads Result, then unloads

    def cmdCancel_Click(self):
        self.Result = None
        self.Hide()


if __name__ == "__main__":
    run(frmDialog)
