"""A modal dialog with its own color scheme (ColorScheme = 3 - Dark)."""

from vp6 import *


class frmDialog(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Add an item'
        self.Width = 320
        self.Height = 146
        self.StartUpPosition = 1
        self.BorderStyle = 3
        self.ColorScheme = 3
        self.lblPrompt = Label(self, Caption='New list item:', Left=16, Top=16, Width=288,
                               Height=25, TabIndex=1)
        self.txtItem = TextBox(self, Text='', Left=16, Top=44, Width=288, Height=25, TabIndex=2)
        self.cmdOK = CommandButton(self, Caption='OK', Left=112, Top=96, Width=90, Height=33,
                                   Default=True, TabIndex=3)
        self.cmdCancel = CommandButton(self, Caption='Cancel', Left=214, Top=96, Width=90,
                                       Height=33, Cancel=True, TabIndex=4)
    # endregion

    def Form_Load(self):
        self.Result = None

    def Form_Activate(self):
        self.txtItem.SetFocus()

    def cmdOK_Click(self):
        self.Result = self.txtItem.Text.strip() or None
        self.Hide()  # ends Show(vpModal); the caller reads Result, then unloads

    def cmdCancel_Click(self):
        self.Result = None
        self.Hide()


if __name__ == "__main__":
    run(frmDialog)
