"""A form shown inside another: Form1 shows it in a PictureBox with ShowIn."""

from vp6 import *


class frmEmbedded(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Embedded form'
        self.Width = 144
        self.Height = 156
        self.lblInfo = Label(self,
                             Caption="A form of its own, shown in Form1's PictureBox with ShowIn",
                             Left=8, Top=8, Width=128, Height=80, WordWrap=True, TabIndex=1)
        self.picButtons = PictureBox(self, Left=0, Top=116, Width=144, Height=40, BorderStyle=0,
                                     Align=2, TabIndex=2,
                                     ToolTipText='Align = 2 - Bottom: docked to the bottom edge')
        self.cmdPop = CommandButton(self.picButtons, Caption='Pop &out', Left=8, Top=4, Width=128,
                                    Height=32, TabIndex=3,
                                    ToolTipText='Show this form in a window of its own, or put it back')
    # endregion

    def Form_Load(self):
        self.home = None  # the container it was in before popping out

    def Form_Resize(self):
        # In a container, the form fills it and follows its size. The button's
        # PictureBox has Align = Bottom, so it stays docked at the bottom by itself
        self.lblInfo.Width = max(self.ScaleWidth - 16, 16)
        self.cmdPop.Width = max(self.picButtons.Width - 16, 16)

    def cmdPop_Click(self):
        if self.Container is not None:  # shown in Form1's PictureBox
            self.home = self.Container
            self.ShowIn(None)  # a window of its own
            self.cmdPop.Caption = "Put &back"
        else:
            self.ShowIn(self.home)
            self.cmdPop.Caption = "Pop &out"


if __name__ == "__main__":
    run(frmEmbedded)
