"""A form shown inside another: Form1 shows it in a PictureBox with ShowIn."""

from vp6 import *


class frmEmbedded(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Embedded form'
        self.Width = 144
        self.Height = 300
        self.picInfo = PictureBox(self, Left=0, Top=0, Width=144, Height=260, BorderStyle=0,
                                  Align=5, TabIndex=1,
                                  ToolTipText='Align = 5 - Fill: the space the button pane leaves')
        self.lblInfo = Label(self.picInfo, TextFormat=2,
                             Caption="A **form of its own**, shown in Form1's PictureBox with `ShowIn`.\n\nIt is taller than the pane, so the pane *scrolls* (ScrollBars = Vertical).\n\n[Pop it out](popout) or scroll down to the button.",
                             Left=8, Top=8, Width=128, Height=200, WordWrap=True, TabIndex=2)
        self.lblShown = Label(self.picInfo, Caption='Shown here for 0 s', Left=8, Top=216,
                              Width=128, Height=25, TabIndex=3)
        self.tmrShown = Timer(self, Left=104, Top=216, Interval=1000, Enabled=False)
        self.picButtons = PictureBox(self, Left=0, Top=260, Width=144, Height=40, BorderStyle=0,
                                     Align=2, TabIndex=4,
                                     ToolTipText='Align = 2 - Bottom: docked to the bottom edge')
        self.cmdPop = CommandButton(self.picButtons, Caption='Pop &out', Left=8, Top=4, Width=128,
                                    Height=32, TabIndex=5,
                                    ToolTipText='Show this form in a window of its own, or put it back')
    # endregion

    def Form_Load(self):
        self.home = None  # the container it was in before popping out
        self.seconds = 0

    # Shown in a container, the form is activated when it becomes visible there
    # and deactivated when it is hidden (also when its pane is): the clock only
    # runs while the form can be seen
    def Form_Activate(self):
        self.tmrShown.Enabled = True

    def Form_Deactivate(self):
        self.tmrShown.Enabled = False

    def tmrShown_Timer(self):
        self.seconds += 1
        self.lblShown.Caption = f"Shown here for {self.seconds} s"

    # In a container, the form fills it and follows its size. Its two panes dock
    # by themselves: picButtons at the bottom (Align = Bottom) and picInfo in the
    # rest (Align = Fill); each one's Resize event sizes what is on it
    def picInfo_Resize(self):
        self.lblInfo.Width = max(self.picInfo.Width - 16, 16)
        self.lblShown.Width = self.lblInfo.Width

    def picButtons_Resize(self):
        self.cmdPop.Width = max(self.picButtons.Width - 16, 16)

    def lblInfo_LinkClick(self, URL):
        # The Label's Caption is Markdown (TextFormat = 2): a link fires LinkClick
        if URL == "popout":
            self.cmdPop_Click()

    def cmdPop_Click(self):
        if self.Container is not None:  # shown in Form1's PictureBox
            self.home = self.Container
            self.ShowIn(None)  # a window of its own
            self.cmdPop.Caption = "Put &back"
        else:
            self.ShowIn(self.home)
            self.cmdPop.Caption = "Pop &out"


if __name__ == "__main__":
    run(frmEmbedded)
