"""Kitchen Sink: an MDI form (MDIForm), a window for the note forms (frmNote,
MDIChild = True): a tool pane docked at its top, a Notes menu, a Window menu
listing the notes (WindowList) and arranging them (Arrange), ActiveForm, and
MDIForm_ event handlers."""

from vp6 import *
from frmNote import frmNote


class frmMDI(MDIForm):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Notes (an MDI form)'
        self.Width = 640
        self.Height = 420
        self.picTools = PictureBox(self, Left=0, Top=0, Width=640, Height=40, BorderStyle=0,
                                   Align=1, TabIndex=1)
        self.cmdNew = CommandButton(self.picTools, Caption='&New note', Left=6, Top=5, Width=100,
                                    Height=30, TabIndex=2)
        self.cmdCascade = CommandButton(self.picTools, Caption='&Cascade', Left=112, Top=5,
                                        Width=90, Height=30, TabIndex=3)
        self.cmdTile = CommandButton(self.picTools, Caption='&Tile', Left=208, Top=5, Width=80,
                                     Height=30, TabIndex=4)
        self.lblActive = Label(self.picTools, Caption='', Left=300, Top=12, Width=330, Height=20,
                               TabIndex=5)
        self.mnuNotes = Menu(self, Caption='&Notes')
        self.mnuNotesNew = Menu(self.mnuNotes, Caption='&New Note')
        self.mnuNotesClose = Menu(self.mnuNotes, Caption='&Close Note')
        self.mnuWindow = Menu(self, Caption='&Window', WindowList=True)
        self.mnuWindowCascade = Menu(self.mnuWindow, Caption='&Cascade')
        self.mnuWindowTileH = Menu(self.mnuWindow, Caption='Tile &Horizontally')
        self.mnuWindowTileV = Menu(self.mnuWindow, Caption='Tile &Vertically')
        self.mnuWindowIcons = Menu(self.mnuWindow, Caption='&Arrange Icons')
    # endregion

    def MDIForm_Load(self):
        # An MDI form's handlers are MDIForm_..., as in VB
        self.count = 0
        self.new_note()
        self.new_note()

    def new_note(self):
        self.count += 1
        note = frmNote()  # a new instance of the child form each time
        note.Caption = f"Note {self.count}"
        note.Show()  # shown inside this window (MDIChild = True)

    def show_active(self):
        active = self.ActiveForm
        self.lblActive.Caption = f"ActiveForm: {active.Caption}" if active else "No note open"

    def cmdNew_Click(self):
        self.new_note()

    def mnuNotesNew_Click(self):
        self.new_note()

    def mnuNotesClose_Click(self):
        if self.ActiveForm is not None:
            Unload(self.ActiveForm)

    def cmdCascade_Click(self):
        self.Arrange(vpCascade)

    def cmdTile_Click(self):
        self.Arrange(vpTileVertical)

    def mnuWindowCascade_Click(self):
        self.Arrange(vpCascade)

    def mnuWindowTileH_Click(self):
        self.Arrange(vpTileHorizontal)  # one above the other

    def mnuWindowTileV_Click(self):
        self.Arrange(vpTileVertical)  # side by side

    def mnuWindowIcons_Click(self):
        self.Arrange(vpArrangeIcons)


if __name__ == "__main__":
    run(frmMDI)
