"""Kitchen Sink: a note, an MDI child form (MDIChild = True): it is shown inside
the Notes window (frmMDI), its Activate firing as it becomes the active note;
its own menu replaces the Notes window's while it is active, as in VB."""

from vp6 import *


class frmNote(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Note'
        self.Width = 280
        self.Height = 160
        self.MDIChild = True
        self.txtNote = TextBox(self, MultiLine=True, Text='', Left=0, Top=0, Width=280, Height=160,
                               ScrollBars=2, TabIndex=1)
        self.mnuNote = Menu(self, Caption='&Note')
        self.mnuNoteStamp = Menu(self.mnuNote, Caption='Insert the &time')
        self.mnuNoteClose = Menu(self.mnuNote, Caption='&Close')
        self.mnuWindow = Menu(self, Caption='&Window', WindowList=True)
        self.mnuWindowCascade = Menu(self.mnuWindow, Caption='&Cascade')
    # endregion

    def Form_Resize(self):
        self.txtNote.Move(0, 0, self.ScaleWidth, self.ScaleHeight)

    def Form_Activate(self):
        from frmMDI import frmMDI

        frmMDI.show_active()

    def Form_Unload(self):
        from frmMDI import frmMDI

        frmMDI.lblActive.Caption = f"Closed {self.Caption}"

    def mnuNoteStamp_Click(self):
        import time

        self.txtNote.SelText = time.strftime("%H:%M ")

    def mnuNoteClose_Click(self):
        Unload(self)

    def mnuWindowCascade_Click(self):
        from frmMDI import frmMDI

        frmMDI.Arrange(vpCascade)


if __name__ == "__main__":
    run(frmNote)
