"""Kitchen Sink: a popup form (ShowPopup): a list of suggestions shown under a
TextBox without taking the focus from it (the MDI and popup forms page)."""

from vp6 import *


class frmSuggest(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Suggestions'
        self.Width = 200
        self.Height = 120
        self.lstChoices = ListBox(self, Left=0, Top=0, Width=200, Height=120, TabIndex=1)
    # endregion

    chosen = None  # set by the page: what a double-click on a suggestion does

    def fill(self, items):
        self.lstChoices.Clear()
        for item in items:
            self.lstChoices.AddItem(item)
        self.lstChoices.ListIndex = 0

    def move(self, step):
        count = self.lstChoices.ListCount
        if count:
            self.lstChoices.ListIndex = (self.lstChoices.ListIndex + step) % count

    def lstChoices_Click(self):
        pass  # (choosing with the mouse: a double-click takes it)

    def lstChoices_DblClick(self):
        if self.chosen is not None:
            self.chosen(self.lstChoices.Text)


if __name__ == "__main__":
    run(frmSuggest)
