"""Kitchen Sink page: control arrays, and loading elements at run time."""

from vp6 import *


class pgArrays(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Control arrays'
        self.Width = 640
        self.Height = 440
        self.lblArrays = Label(self, TextFormat=2,
                               Caption='`cmdMore` is a **control array**: one handler for all its buttons, told apart by `Index`. **+** loads a new element (`Load`), clicking one unloads it (`Unload`). The option buttons on the Color schemes page are one too.',
                               Left=16, Top=16, Width=600, Height=60, WordWrap=True, TabIndex=1)
        self.cmdMore = ControlArray()
        self.cmdMore[0] = CommandButton(self, Caption='+', Left=16, Top=90, Width=40, Height=33,
                                        TabIndex=2,
                                        ToolTipText='Loads a new element of the control array')
        self.lblMore = Label(self, Caption='', Left=16, Top=140, Width=600, Height=25, TabIndex=3)
    # endregion

    def cmdMore_Click(self, Index):
        more = self.cmdMore  # the ControlArray; its elements are more[i] or more(i)
        if Index == 0:  # "+": add an element in the first free place
            free = [i for i in range(1, 5) if i not in more]
            if not free:
                self.lblMore.Caption = "That's enough buttons"
                return
            button = Load(more, free[0])  # VB: Load cmdMore(i) - a hidden copy of cmdMore(0)
            button.Caption = str(button.Index)
            button.Left = more(0).Left + 44 * button.Index
            button.Visible = True
        else:
            Unload(more, Index)  # only elements added with Load can be unloaded
        self.lblMore.Caption = (f"cmdMore has {more.Count} elements, Index {more.LBound} "
                                f"to {more.UBound}: " +
                                ", ".join(element.Caption for element in more))


if __name__ == "__main__":
    run(pgArrays)
