"""Kitchen Sink page: CommandButtons, CheckBoxes, OptionButtons and Frames."""

from vp6 import *


class pgButtons(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Buttons and options'
        self.Width = 640
        self.Height = 440
        self.cmdClick = CommandButton(self, Caption='&Click me', Left=16, Top=16, Width=120,
                                      Height=32, TabIndex=1)
        self.cmdAuto = CommandButton(self, Caption='Click it &from code', Left=146, Top=16,
                                     Width=170, Height=32, TabIndex=2,
                                     ToolTipText="Setting a CommandButton's Value to True clicks it")
        self.lblClicks = Label(self, Caption='Not clicked yet', Left=330, Top=22, Width=290,
                               Height=25, TabIndex=3)
        self.chkBold = CheckBox(self, Caption='&Bold', Left=16, Top=70, Width=160, Height=25,
                                TabIndex=4)
        self.chkItalic = CheckBox(self, Caption='&Italic', Left=16, Top=96, Width=160, Height=25,
                                  TabIndex=5)
        self.chkMixed = CheckBox(self, Caption='Grayed (Value = 2)', Left=16, Top=122, Width=180,
                                 Height=25, Value=2, TabIndex=6)
        self.lblSample = Label(self, Caption='Sample text', Left=210, Top=70, Width=300, Height=60,
                               FontSize=12, TabIndex=7)
        self.fraSize = Frame(self, Caption='Size', Left=16, Top=170, Width=180, Height=100,
                             TabIndex=8)
        self.optSmall = OptionButton(self.fraSize, Caption='&Small', Left=12, Top=28, Width=150,
                                     Height=25, Value=True, TabIndex=9)
        self.optLarge = OptionButton(self.fraSize, Caption='&Large', Left=12, Top=56, Width=150,
                                     Height=25, TabIndex=10)
        self.fraColor = Frame(self, Caption='Color', Left=210, Top=170, Width=180, Height=100,
                              TabIndex=11)
        self.optBlack = OptionButton(self.fraColor, Caption='Blac&k', Left=12, Top=28, Width=150,
                                     Height=25, Value=True, TabIndex=12)
        self.optBlue = OptionButton(self.fraColor, Caption='Bl&ue', Left=12, Top=56, Width=150,
                                    Height=25, TabIndex=13)
    # endregion

    def Form_Load(self):
        self.clicks = 0

    def cmdClick_Click(self):
        self.clicks += 1
        self.lblClicks.Caption = f"Clicked {self.clicks} times"

    def cmdAuto_Click(self):
        self.cmdClick.Value = True  # clicks it, firing cmdClick_Click

    def chkBold_Click(self):
        self.lblSample.FontBold = self.chkBold.Value == vpChecked

    def chkItalic_Click(self):
        self.lblSample.FontItalic = self.chkItalic.Value == vpChecked

    def chkMixed_Click(self):
        self.lblClicks.Caption = f"The third CheckBox's Value is {self.chkMixed.Value}"

    def fraSize_Click(self):
        # Option buttons are a group per container: Size and Color are separate choices
        self.lblClicks.Caption = "Each Frame's option buttons are a group of their own"

    def optSmall_Click(self):
        self.lblSample.FontSize = 12

    def optLarge_Click(self):
        self.lblSample.FontSize = 20

    def optBlack_Click(self):
        self.lblSample.ForeColor = None  # the color scheme's text color

    def optBlue_Click(self):
        self.lblSample.ForeColor = vpBlue


if __name__ == "__main__":
    run(pgButtons)
