"""Kitchen Sink page: CommandButtons, CheckBoxes, OptionButtons (also Graphical ones: a
picture button and toggle buttons) and Frames, and a button moving into another container
at run time (Container)."""

from vp6 import *


class pgButtons(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Buttons and options'
        self.Width = 640
        self.Height = 440
        self.cmdClick = CommandButton(self, Caption='&Click me', Left=16, Top=16, Width=120,
                                      Height=32, TabIndex=1)
        self.cmdAuto = CommandButton(self, Caption='Click it &from code', Left=146, Top=16,
                                     Width=170, Height=32, TabIndex=2,
                                     ToolTipText="Setting a CommandButton's Value to True clicks it")
        self.lblClicks = Label(self, Caption='Not clicked yet', Left=330, Top=22, Width=290,
                               Height=25, TabIndex=3)
        self.chkBold = CheckBox(self, Caption='&Bold', Left=16, Top=70, Width=160, Height=25,
                                TabIndex=4)
        self.chkItalic = CheckBox(self, Caption='&Italic', Left=16, Top=96, Width=160, Height=25,
                                  TabIndex=5)
        self.chkMixed = CheckBox(self, Caption='Grayed (Value = 2)', Left=16, Top=122, Width=180,
                                 Height=25, Value=2, TabIndex=6)
        self.lblSample = Label(self, Caption='Sample text', Left=210, Top=70, Width=300, Height=60,
                               FontSize=12, TabIndex=7)
        self.fraSize = Frame(self, Caption='Size', Left=16, Top=170, Width=180, Height=100,
                             TabIndex=8)
        self.optSmall = OptionButton(self.fraSize, Caption='&Small', Left=12, Top=28, Width=150,
                                     Height=25, Value=True, TabIndex=9)
        self.optLarge = OptionButton(self.fraSize, Caption='&Large', Left=12, Top=56, Width=150,
                                     Height=25, TabIndex=10)
        self.fraColor = Frame(self, Caption='Color', Left=210, Top=170, Width=180, Height=100,
                              TabIndex=11)
        self.optBlack = OptionButton(self.fraColor, Caption='Blac&k', Left=12, Top=28, Width=150,
                                     Height=25, Value=True, TabIndex=12)
        self.optBlue = OptionButton(self.fraColor, Caption='Bl&ue', Left=12, Top=56, Width=150,
                                    Height=25, TabIndex=13)
        self.cmdStar = CommandButton(self, Caption='&Star', Left=16, Top=290, Width=90, Height=70,
                                     Style=1, Picture='images/star.png',
                                     DownPicture='images/sun.png', TabIndex=14,
                                     ToolTipText='A Graphical CommandButton: its Picture, and its DownPicture while pressed')
        self.chkUnderline = CheckBox(self, Caption='&Underline', Left=120, Top=290, Width=110,
                                     Height=32, Style=1, TabIndex=15,
                                     ToolTipText='A Graphical CheckBox: a toggle button')
        self.fraAlign = Frame(self, Caption='Alignment', Left=400, Top=170, Width=220, Height=100,
                              TabIndex=16)
        self.optAlign = ControlArray()
        self.optAlign[0] = OptionButton(self.fraAlign, Caption='Left', Left=12, Top=36, Width=62,
                                        Height=32, Value=True, Style=1, TabIndex=17,
                                        ToolTipText='Graphical OptionButtons: toggle buttons, one of them pressed')
        self.optAlign[1] = OptionButton(self.fraAlign, Caption='Center', Left=78, Top=36, Width=62,
                                        Height=32, Style=1, TabIndex=18,
                                        ToolTipText='Graphical OptionButtons: toggle buttons, one of them pressed')
        self.optAlign[2] = OptionButton(self.fraAlign, Caption='Right', Left=144, Top=36, Width=62,
                                        Height=32, Style=1, TabIndex=19,
                                        ToolTipText='Graphical OptionButtons: toggle buttons, one of them pressed')
        self.fraBasket = Frame(self, Caption='Basket', Left=250, Top=290, Width=200, Height=110,
                               TabIndex=20)
        self.cmdHop = CommandButton(self, Caption='&Hop in', Left=470, Top=330, Width=110,
                                    Height=30, TabIndex=21,
                                    ToolTipText='Moves itself into the Basket frame and out again (Container)')
    # endregion

    def Form_Load(self):
        self.clicks = 0

    def cmdClick_Click(self):
        self.clicks += 1
        self.lblClicks.Caption = f"Clicked {self.clicks} times"

    def cmdAuto_Click(self):
        self.cmdClick.Value = True  # clicks it, firing cmdClick_Click

    def chkBold_Click(self):
        self.lblSample.FontBold = self.chkBold.Value == vpChecked

    def chkItalic_Click(self):
        self.lblSample.FontItalic = self.chkItalic.Value == vpChecked

    def chkMixed_Click(self):
        self.lblClicks.Caption = f"The third CheckBox's Value is {self.chkMixed.Value}"

    def fraSize_Click(self):
        # Option buttons are a group per container: Size and Color are separate choices
        self.lblClicks.Caption = "Each Frame's option buttons are a group of their own"

    def optSmall_Click(self):
        self.lblSample.FontSize = 12

    def optLarge_Click(self):
        self.lblSample.FontSize = 20

    def optBlack_Click(self):
        self.lblSample.ForeColor = None  # the color scheme's text color

    def optBlue_Click(self):
        self.lblSample.ForeColor = vpBlue

    # --- Style = Graphical ----------------------------------------------------------------
    def cmdStar_Click(self):
        self.lblClicks.Caption = "The picture button was clicked (a sun while pressed)"

    def chkUnderline_Click(self):
        # A Graphical CheckBox is a toggle button: pressed while its Value is vpChecked
        self.lblSample.FontUnderline = self.chkUnderline.Value == vpChecked

    def cmdHop_Click(self):
        # VB's Set cmdHop.Container = fraBasket: the button moves into the frame; its
        # Left and Top are then in the frame
        hop = self.cmdHop
        if hop.Container is self:
            hop.Container = self.fraBasket
            hop.Move(45, 50)
            hop.Caption = "&Hop out"
        else:
            hop.Container = self
            hop.Move(470, 330)
            hop.Caption = "&Hop in"
        self.lblClicks.Caption = f"cmdHop is in {hop.Container.Name}"

    def optAlign_Click(self, Index):
        # Graphical OptionButtons: one of the Frame's is pressed
        self.lblSample.Alignment = (vpLeftJustify, vpCenter, vpRightJustify)[Index]


if __name__ == "__main__":
    run(pgButtons)
