"""Kitchen Sink page: the CodeBox, a code editor: Python coloring (Language) plus the
page's own (TODO and FIXME in the Highlight event), line numbers, the current line,
breakpoint markers and a foldable region in the gutter (LineMarker, GutterClick,
HideLines, ShowLines), and protected lines the user can't change (ProtectLines,
ProtectedEdit)."""

import re

from vp6 import *

# The code shown (a list of lines, so the IDE doesn't take its class and methods for
# this file's own)
SAMPLE = "\n".join([
    '"""A form, as the designer writes it."""',
    '',
    'from vp6 import *',
    '',
    '',
    'class Greeter(Form):',
    "    # region Generated - protected: the user can't change it, code can",
    '    def InitializeComponent(self):',
    '        self.Caption = "Greeter"',
    '        self.cmdHello = CommandButton(self, Caption="Hello")',
    '    # endregion',
    '',
    '    def cmdHello_Click(self):',
    '        name = InputBox("Your name?")  # TODO: a default name',
    '        MsgBox(f"Hello, {name}!")',
    '',
    '',
    '    def Form_Load(self):',
    '        pass  # FIXME: say hello at start',
    '',
])
NOTE = re.compile(r"\b(TODO|FIXME)\b")
BREAKPOINT = "●"  # a red dot in the gutter


class pgCode(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'CodeBox'
        self.Width = 640
        self.Height = 440
        self.codSample = CodeBox(self, Text='', Left=16, Top=16, Width=608, Height=300, Language=1,
                                 TabIndex=1,
                                 ToolTipText='Click the gutter: a breakpoint, or fold the region')
        self.chkNumbers = CheckBox(self, Caption='Line &numbers', Left=16, Top=326, Width=130,
                                   Height=25, Value=1, TabIndex=2)
        self.chkCurrent = CheckBox(self, Caption='&Current line', Left=150, Top=326, Width=130,
                                   Height=25, Value=1, TabIndex=3)
        self.chkWrap = CheckBox(self, Caption='&Word wrap', Left=284, Top=326, Width=110,
                                Height=25, TabIndex=4)
        self.chkPython = CheckBox(self, Caption='&Python colors', Left=398, Top=326, Width=130,
                                  Height=25, Value=1, TabIndex=5)
        self.cmdFold = CommandButton(self, Caption='&Fold region', Left=524, Top=324, Width=100,
                                     Height=29, TabIndex=6)
        self.lblEvent = Label(self,
                              Caption='Click the gutter for a breakpoint, or by line 7 to fold the region.',
                              Left=16, Top=362, Width=608, Height=40, WordWrap=True, TabIndex=7)
    # endregion

    def Form_Load(self):
        self.codSample.Text = SAMPLE
        self.codSample.ClearUndo()
        self.region = self.find_region()
        self.codSample.ProtectLines(*self.region)
        self.codSample.LineMarker[self.region[0]] = "-"  # the region can fold

    def find_region(self) -> tuple[int, int]:
        """The lines of the "# region" to "# endregion" block (from 0)."""
        code = self.codSample
        lines = [code.GetLine(n).strip() for n in range(code.LineCount)]
        first = next(n for n, line in enumerate(lines) if line.startswith("# region"))
        return first, lines.index("# endregion", first)

    # --- coloring: the page's own on top of Python's ------------------------------------------
    def codSample_Highlight(self, Line, Text, State):
        for match in NOTE.finditer(Text):
            self.codSample.HighlightText(match.start(), len(match.group()), ForeColor=vpBlack,
                                         BackColor=RGB(255, 220, 80), Bold=True)
        return State  # (nothing continues on the next line)

    # --- the gutter -----------------------------------------------------------------------------
    def codSample_GutterClick(self, Line):
        code = self.codSample
        if Line == self.region[0]:
            self.toggle_fold()
        elif code.LineMarker(Line) == BREAKPOINT:
            code.LineMarker[Line] = ""
            self.lblEvent.Caption = f"Breakpoint removed from line {Line + 1}"
        else:
            code.LineMarker[Line] = BREAKPOINT
            self.lblEvent.Caption = f"Breakpoint on line {Line + 1} (GutterClick)"

    def toggle_fold(self):
        code = self.codSample
        first, last = self.region
        if code.IsLineHidden(first + 1):
            code.ShowLines(first + 1, last)
            code.LineMarker[first] = "-"
            self.cmdFold.Caption = "&Fold region"
        else:
            code.HideLines(first + 1, last)
            code.LineMarker[first] = "+"
            self.cmdFold.Caption = "Un&fold region"
        self.lblEvent.Caption = f"Lines {first + 2} to {last + 1} " + (
            "hidden (HideLines)" if code.IsLineHidden(first + 1) else "shown (ShowLines)")

    def cmdFold_Click(self):
        self.toggle_fold()

    def codSample_ProtectedEdit(self, Line):
        Beep()
        self.lblEvent.Caption = (f"Line {Line + 1} is protected: the designer keeps it "
                                 "(ProtectLines)")

    # --- options --------------------------------------------------------------------------------
    def chkNumbers_Click(self):
        self.codSample.LineNumbers = self.chkNumbers.Value == vpChecked

    def chkCurrent_Click(self):
        self.codSample.HighlightCurrentLine = self.chkCurrent.Value == vpChecked

    def chkWrap_Click(self):
        self.codSample.WordWrap = self.chkWrap.Value == vpChecked

    def chkPython_Click(self):
        self.codSample.Language = 1 if self.chkPython.Value == vpChecked else 0

    def codSample_Change(self):
        # (an edit above the region moves it: ask the CodeBox where it is now)
        code = self.codSample
        first = next((n for n in range(code.LineCount) if code.IsLineProtected(n)), None)
        if first is not None:
            last = first
            while last + 1 < code.LineCount and code.IsLineProtected(last + 1):
                last += 1
            self.region = (first, last)


if __name__ == "__main__":
    run(pgCode)
