"""Kitchen Sink page: data-bound controls. A Data control shows the pets of a
small SQLite database, one at a time, in the controls bound to it (DataSource,
DataField): a Label, TextBoxes, a ComboBox, a CheckBox and an Image (a picture
kept in the database); a FlexGrid bound to it shows them all. Its arrows move
through the records, saving what was changed (Validate first, Reposition
after); past the last one it starts a new record (EOFAction). The buttons use
its Recordset: AddNew, Delete, FindFirst; UpdateRecord and UpdateControls;
OpenDatabase for a summary of the table."""

import os

from vp6 import *

FOLDER = os.path.dirname(os.path.abspath(__file__))
DATABASE = os.path.join(FOLDER, "pets.db")  # (made the first time the page is shown)

# The pets to start with: name, kind, age, vaccinated, notes and the color of their picture
PETS = (
    ("Bella", "Cat", 3, True, "Sleeps on the keyboard", vpYellow),
    ("Max", "Dog", 5, True, "Fetches anything but the ball", RGB(160, 110, 60)),
    ("Coco", "Parrot", 12, False, "Says 'Hello' and 'End'", vpGreen),
    ("Luna", "Rabbit", 1, True, "", RGB(200, 200, 200)),
    ("Oscar", "Tortoise", 47, False, "Older than VB", RGB(90, 140, 90)),
)


def portrait(color) -> Picture:
    """A pet's picture: a face in its color (kept in the database as a PNG)."""
    picture = Picture(64, 64, vpWhite)
    picture.FillStyle = vpFSSolid
    picture.FillColor = color
    picture.Circle(32, 34, 24, vpBlack)
    picture.FillColor = vpBlack
    picture.Circle(24, 28, 3, vpBlack)
    picture.Circle(40, 28, 3, vpBlack)
    picture.Circle(32, 40, 8, vpBlack, 3.6, 5.8)  # a smile
    return picture


def make_database(path: str) -> None:
    """A new database (CreateDatabase), its table made with Execute and filled
    by a Recordset of its own: AddNew, the fields' values, Update."""
    db: Database = CreateDatabase(path)
    db.Execute("CREATE TABLE pets (Id INTEGER PRIMARY KEY, Name TEXT NOT NULL, Kind TEXT, "
               "Age INTEGER, Vaccinated INTEGER, Notes TEXT, Photo BLOB)")
    rs = db.OpenRecordset("pets")
    for name, kind, age, vaccinated, notes, color in PETS:
        rs.AddNew()
        rs["Name"], rs["Kind"], rs["Age"] = name, kind, age
        rs["Vaccinated"], rs["Notes"] = vaccinated, notes
        rs["Photo"] = portrait(color)  # a Picture: saved as a PNG
        rs.Update()
    db.Close()


def field_list(recordset: Recordset) -> str:
    """The names of a Recordset's fields (each a Field: Name, Value...)."""
    fields: list[Field] = list(recordset.Fields)
    return ", ".join(field.Name for field in fields)


class pgData(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Data-bound controls'
        self.Width = 640
        self.Height = 440
        self.lblNumberCaption = Label(self, Caption='Number:', Left=16, Top=16, Width=76,
                                      Height=22)
        self.lblNumber = Label(self, Caption='', Left=100, Top=16, Width=120, Height=22,
                               DataSource='dtaPets', DataField='Id')
        self.lblName = Label(self, Caption='&Name:', Left=16, Top=45, Width=76, Height=22)
        self.txtName = TextBox(self, Text='', Left=100, Top=42, Width=220, Height=25, TabIndex=1,
                               DataSource='dtaPets', DataField='Name')
        self.lblKind = Label(self, Caption='&Kind:', Left=16, Top=75, Width=76, Height=22)
        self.cboKind = ComboBox(self, Left=100, Top=72, Width=220, Height=25,
                                List=['Cat', 'Dog', 'Parrot', 'Rabbit', 'Tortoise'], Text='',
                                TabIndex=2, DataSource='dtaPets', DataField='Kind')
        self.lblAge = Label(self, Caption='&Age:', Left=16, Top=105, Width=76, Height=22)
        self.txtAge = TextBox(self, Text='', Left=100, Top=102, Width=80, Height=25, TabIndex=3,
                              ToolTipText='A number: Validate checks it', DataSource='dtaPets',
                              DataField='Age')
        self.chkVaccinated = CheckBox(self, Caption='&Vaccinated', Left=190, Top=102, Width=130,
                                      Height=25, TabIndex=4, DataSource='dtaPets',
                                      DataField='Vaccinated')
        self.lblNotes = Label(self, Caption='No&tes:', Left=16, Top=135, Width=76, Height=22)
        self.txtNotes = TextBox(self, MultiLine=True, Text='', Left=100, Top=132, Width=220,
                                Height=60, TabIndex=5, DataSource='dtaPets', DataField='Notes')
        self.imgPhoto = Image(self, Left=336, Top=16, Width=96, Height=96, Stretch=True,
                              BorderStyle=1, ToolTipText='A picture kept in the database (a BLOB)',
                              DataSource='dtaPets', DataField='Photo')
        self.chkReadOnly = CheckBox(self, Caption='&Read only', Left=336, Top=132, Width=100,
                                    Height=25, TabIndex=6,
                                    ToolTipText="The Data control's ReadOnly: nothing is saved")
        self.cmdAdd = CommandButton(self, Caption='A&dd a pet', Left=448, Top=16, Width=176,
                                    Height=30, TabIndex=7, ToolTipText='Recordset.AddNew')
        self.cmdDelete = CommandButton(self, Caption='Dele&te', Left=448, Top=52, Width=176,
                                       Height=30, TabIndex=8,
                                       ToolTipText='Recordset.Delete, then MoveNext')
        self.cmdFind = CommandButton(self, Caption='&Find…', Left=448, Top=88, Width=176,
                                     Height=30, TabIndex=9,
                                     ToolTipText="Recordset.FindFirst: Name LIKE 'B%'")
        self.cmdUndo = CommandButton(self, Caption='&Undo changes', Left=448, Top=124, Width=104,
                                     Height=30, TabIndex=10,
                                     ToolTipText='Data.UpdateControls: the record shown again')
        self.cmdSave = CommandButton(self, Caption='&Save', Left=556, Top=124, Width=68, Height=30,
                                     TabIndex=11, ToolTipText='Data.UpdateRecord: saved now')
        self.cmdSummary = CommandButton(self, Caption='Su&mmary', Left=448, Top=160, Width=176,
                                        Height=30, TabIndex=12,
                                        ToolTipText='OpenDatabase and a GROUP BY query (read-only)')
        self.dtaPets = Data(self, Caption='Pets', Left=16, Top=204, Width=416, Height=30,
                            DatabaseName='pets.db',
                            RecordSource='SELECT * FROM pets ORDER BY Name', EOFAction=2,
                            ToolTipText='Its arrows: the first, previous, next and last pet; past the last, a new one')
        self.lblStatus = Label(self, Caption='', Left=448, Top=208, Width=176, Height=22)
        self.grdPets = FlexGrid(self, Left=16, Top=244, Width=608, Height=180, FixedCols=0,
                                SelectionMode=1, TabIndex=13,
                                ToolTipText='Bound to the Data control too: every pet; choose one',
                                DataSource='dtaPets')
    # endregion

    def Form_Load(self):
        # The Data control opens its database after Form_Load: there is time to make it
        if not os.path.exists(DATABASE):
            make_database(DATABASE)

    def status(self, text):
        self.lblStatus.Caption = text

    # --- the Data control's events --------------------------------------------------------------
    def dtaPets_Validate(self, Action, Save):
        # Before leaving a record (Action: why), Save: whether something was changed
        if Save and self.txtAge.Text and not self.txtAge.Text.isdigit():
            MsgBox("The age is a whole number.", vpExclamation)
            self.txtAge.SetFocus()
            return vpDataActionCancel  # stay on this record
        if Save and self.txtName.DataChanged and not self.txtName.Text.strip():
            self.txtName.DataChanged = False  # an emptied name: not saved
        return None

    def dtaPets_Reposition(self):
        rs = self.dtaPets.Recordset
        if rs.EditMode == vpEditAdd:
            self.dtaPets.Caption = "A new pet"
            self.status("Type, then move on to save")
        elif rs.EOF or rs.BOF:
            self.dtaPets.Caption = "No pet"
        else:
            self.dtaPets.Caption = f"Pet {rs.AbsolutePosition + 1} of {rs.RecordCount}"
            self.status(f"{rs('Name')}, {rs('Kind') or 'unknown kind'}")

    def dtaPets_Error(self, Description):
        self.status("Not saved")
        MsgBox(f"The pet couldn't be saved:\n{Description}", vpExclamation)

    # --- the buttons: its Recordset ---------------------------------------------------------------
    def cmdAdd_Click(self):
        self.dtaPets.Recordset.AddNew()  # the bound controls empty, saved when moving on
        self.txtName.SetFocus()

    def cmdDelete_Click(self):
        rs = self.dtaPets.Recordset
        if rs.EditMode == vpEditAdd:
            rs.CancelUpdate()  # (a new pet not saved yet: dropped)
            self.dtaPets.UpdateControls()
            return
        if rs.EOF or rs.BOF:
            return
        if MsgBox(f"Delete {rs('Name')}?", vpYesNo + vpQuestion) != vpYes:
            return
        rs.Delete()
        rs.MoveNext()  # as in VB: after Delete there is no current record
        if rs.EOF and rs.RecordCount:
            rs.MoveLast()

    def cmdFind_Click(self):
        text = InputBox("Find the first pet whose name begins with:", "Find", "B")
        if not text:
            return
        rs = self.dtaPets.Recordset
        rs.FindFirst("Name LIKE '%s%%'" % text.replace("'", "''"))  # a SQL condition
        if rs.NoMatch:
            self.status(f"No name begins with {text}")

    def cmdUndo_Click(self):
        self.dtaPets.UpdateControls()

    def cmdSave_Click(self):
        self.dtaPets.UpdateRecord()
        self.status("Saved")

    def chkReadOnly_Click(self):
        self.dtaPets.ReadOnly = self.chkReadOnly.Value == vpChecked
        self.dtaPets.Refresh()  # opened again, read-only or not

    def cmdSummary_Click(self):
        # A Database of its own, and a query that can't be changed (Updatable is False)
        db = OpenDatabase(DATABASE, ReadOnly=True)
        rs = db.OpenRecordset("SELECT Kind, COUNT(*) AS Pets, AVG(Age) AS Age FROM pets "
                              "GROUP BY Kind ORDER BY Kind")
        lines = [f"Fields: {field_list(rs)}", ""]
        while not rs.EOF:
            lines.append(f"{rs('Kind') or '?'}: {rs('Pets')} (age {rs('Age') or 0:.0f})")
            rs.MoveNext()
        db.Close()
        MsgBox("\n".join(lines), vpInformation, "Pets by kind")


if __name__ == "__main__":
    run(pgData)
