"""Kitchen Sink page: MsgBox, InputBox, a modal form and Beep."""

from vp6 import *
from frmDialog import frmDialog


class pgDialogs(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Dialogs'
        self.Width = 640
        self.Height = 440
        self.cmdMsgBox = CommandButton(self, Caption='&MsgBox', Left=16, Top=16, Width=180,
                                       Height=32, TabIndex=1)
        self.cmdInputBox = CommandButton(self, Caption='&InputBox', Left=16, Top=56, Width=180,
                                         Height=32, TabIndex=2)
        self.cmdModal = CommandButton(self, Caption='Modal &form...', Left=16, Top=96, Width=180,
                                      Height=32, TabIndex=3,
                                      ToolTipText='Shows frmDialog with Show(vpModal): it has its own Dark scheme')
        self.cmdBeep = CommandButton(self, Caption='&Beep', Left=16, Top=136, Width=180, Height=32,
                                     TabIndex=4)
        self.lblResult = Label(self, Caption='', Left=210, Top=22, Width=410, Height=140,
                               WordWrap=True, TabIndex=5)
    # endregion

    shell = None  # the Kitchen Sink window showing this page (None when run on its own)

    def cmdMsgBox_Click(self):
        answer = MsgBox("Do you like VP6?", vpYesNoCancel + vpQuestion, "MsgBox")
        names = {vpYes: "Yes", vpNo: "No", vpCancel: "Cancel"}
        self.lblResult.Caption = f"MsgBox returned {answer} ({names.get(answer, '?')})"

    def cmdInputBox_Click(self):
        text = InputBox("Type something:", "InputBox", "Hello")
        self.lblResult.Caption = f"InputBox returned {text!r}"

    def cmdModal_Click(self):
        dialog = frmDialog()
        Load(dialog)
        # Modal: waits until the dialog is hidden; centered on this window
        dialog.Show(vpModal, self.shell or self)
        self.lblResult.Caption = f"The dialog's Result: {dialog.Result!r}"
        Unload(dialog)

    def cmdBeep_Click(self):
        Beep()
        self.lblResult.Caption = "Beep!"


if __name__ == "__main__":
    run(pgDialogs)
