"""Kitchen Sink page: DockPanels, tool windows docked to the page's edges, like the IDE's
panels. Drag a caption bar to float a panel and drop it on an edge; double-click it, or
use its buttons, to float, dock or close it. The page's DockLayout saves and restores
where they all are."""

from vp6 import *


class pgDocking(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Docking panels'
        self.Width = 640
        self.Height = 440
        self.dckTools = DockPanel(self, Left=0, Top=0, Width=150, Height=440, Caption='Tools')
        self.cmdShowAll = CommandButton(self.dckTools, Caption='&Show all', Left=8, Top=8,
                                        Width=128, Height=28, TabIndex=1,
                                        ToolTipText='Show the closed panels again (Visible = True)')
        self.cmdSave = CommandButton(self.dckTools, Caption='Sa&ve layout', Left=8, Top=40,
                                     Width=128, Height=28, TabIndex=2,
                                     ToolTipText="Remember where the panels are (the page's DockLayout)")
        self.cmdRestore = CommandButton(self.dckTools, Caption='&Restore layout', Left=8, Top=72,
                                        Width=128, Height=28, Enabled=False, TabIndex=3)
        self.cmdFloat = CommandButton(self.dckTools, Caption='&Float output', Left=8, Top=104,
                                      Width=128, Height=28, TabIndex=4,
                                      ToolTipText='Float the Output panel (Float), or dock it (Dock)')
        self.chkKeep = CheckBox(self.dckTools, Caption='&Keep Output open', Left=8, Top=140,
                                Width=136, Height=25, TabIndex=5,
                                ToolTipText="Output's Close event cancels closing it")
        self.dckProps = DockPanel(self, Left=490, Top=0, Width=150, Height=440,
                                  Caption='Properties', Align=4)
        self.grdProps = FlexGrid(self.dckProps, Left=0, Top=0, Width=140, Height=200, Rows=4,
                                 FixedCols=0, FormatString='Panel|Where', TabIndex=6)
        self.dckOutput = DockPanel(self, Left=0, Top=330, Width=640, Height=110, Caption='Output',
                                   Align=2)
        self.rtbLog = RichTextBox(self.dckOutput, Text='', Left=0, Top=0, Width=300, Height=80,
                                  Locked=True, BorderStyle=0, TabIndex=7)
        self.picCenter = PictureBox(self, Left=150, Top=0, Width=340, Height=330, BorderStyle=0,
                                    Align=5)
        self.lblHelp = Label(self.picCenter,
                             Caption="Drag a panel's caption bar to float it, and drop it on an edge to dock it there (a blue frame shows where). Double-click a caption bar to float or dock its panel; drag a docked panel's inner edge to resize it.",
                             Left=16, Top=16, Width=300, Height=120, WordWrap=True, TabIndex=8)
    # endregion

    def Form_Load(self):
        self.saved = None
        self.show_where()

    # --- the panels' contents follow their size ----------------------------------------------
    def dckOutput_Resize(self):
        inner = self.dckOutput
        self.rtbLog.Move(0, 0, max(inner.Width - 12, 40), max(inner.Height - 30, 20))

    def dckProps_Resize(self):
        width = max(self.dckProps.Width - 12, 40)
        self.grdProps.Move(0, 0, width, max(self.dckProps.Height - 30, 40))
        self.grdProps.ColWidth[0] = width // 2
        self.grdProps.ColWidth[1] = width - width // 2 - 4

    def picCenter_Resize(self):
        self.lblHelp.Width = max(self.picCenter.Width - 32, 60)

    # --- events --------------------------------------------------------------------------------
    def log(self, text, color=None):
        self.rtbLog.AppendText(text + "\n", Color=color)

    def where(self, panel) -> str:
        if not panel.Visible:
            return "closed"
        if panel.Floating:
            return "floating"
        return ("top", "bottom", "left", "right")[panel.Align - 1]

    def show_where(self):
        grid = self.grdProps
        panels = (self.dckTools, self.dckProps, self.dckOutput)
        for row, panel in enumerate(panels, start=1):
            grid.TextMatrix[row, 0] = panel.Caption
            grid.TextMatrix[row, 1] = self.where(panel)

    def dckTools_DockChange(self):
        self.docked(self.dckTools)

    def dckProps_DockChange(self):
        self.docked(self.dckProps)

    def dckOutput_DockChange(self):
        self.docked(self.dckOutput)
        self.cmdFloat.Caption = "&Dock output" if self.dckOutput.Floating else "&Float output"

    def docked(self, panel):
        self.log(f"{panel.Caption}: {self.where(panel)} (DockChange)", RGB(30, 110, 255))
        self.show_where()

    def dckOutput_Close(self):
        if self.chkKeep.Value == vpChecked:
            self.log("Output stays open (its Close event returned True)", vpRed)
            return True  # cancel
        return False

    def dckTools_Close(self):
        self.lblHelp.Caption = ("Tools closed: double-click its row in the Properties "
                                "panel to show it again.")
        return False

    def grdProps_DblClick(self):
        # A closed panel comes back where it was (docked or floating)
        panel = (self.dckTools, self.dckProps, self.dckOutput)[self.grdProps.Row - 1] \
            if 1 <= self.grdProps.Row <= 3 else None
        if panel is not None:
            panel.Visible = True
            self.show_where()

    # --- the buttons ---------------------------------------------------------------------------
    def cmdShowAll_Click(self):
        for panel in (self.dckTools, self.dckProps, self.dckOutput):
            panel.Visible = True
        self.show_where()

    def cmdSave_Click(self):
        self.saved = self.DockLayout
        self.cmdRestore.Enabled = True
        self.log("Layout saved (DockLayout)")

    def cmdRestore_Click(self):
        if self.saved:
            self.DockLayout = self.saved
            self.log("Layout restored")
            self.show_where()

    def cmdFloat_Click(self):
        if self.dckOutput.Floating:
            self.dckOutput.Dock()
        else:
            self.dckOutput.Float()


if __name__ == "__main__":
    run(pgDocking)
