"""Kitchen Sink page: drawing with the graphics methods. A sketch pad (a
PictureBox with AutoRedraw: Line from the mouse, Cls), shapes (Line boxes,
Circle, arcs and pie slices, PSet, Print centered with TextWidth and
TextHeight), DrawWidth, DrawStyle, FillStyle and FillColor, a clock drawn in
a Paint event (AutoRedraw False) that a Timer refreshes, in a User scale
(Scale: its center 0, 0, up is up), and the page's own Form_Paint."""

import math
import time

from vp6 import *

STYLES = ["0 - Solid", "1 - Dash", "2 - Dot", "3 - Dash-Dot", "4 - Dash-Dot-Dot",
          "5 - Transparent", "6 - Inside Solid"]


class pgDrawing(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Drawing'
        self.Width = 640
        self.Height = 440
        self.picSketch = PictureBox(self, Left=16, Top=16, Width=380, Height=300, AutoRedraw=True,
                                    BackColor=0xFFFFFF, ForeColor=0x804000, TabIndex=1,
                                    ToolTipText='Draw with the mouse: Line from the last point',
                                    MousePointer=2)
        self.picClock = PictureBox(self, Left=412, Top=16, Width=212, Height=212,
                                   BackColor=0xFFFFFF, TabIndex=2,
                                   ToolTipText='Drawn in its Paint event (AutoRedraw False)')
        self.lblWidth = Label(self, Caption='DrawWidth:', Left=16, Top=330, Width=76, Height=20,
                              TabIndex=3)
        self.hsbWidth = HScrollBar(self, Left=92, Top=330, Width=120, Height=20, Min=1, Max=12,
                                   Value=2, TabIndex=4)
        self.cboStyle = ComboBox(self, Style=2, Left=228, Top=326, Width=168, Height=25,
                                 TabIndex=5, ToolTipText='DrawStyle')
        self.cmdShapes = CommandButton(self, Caption='Draw &shapes', Left=16, Top=362, Width=120,
                                       Height=30, TabIndex=6,
                                       ToolTipText='Line boxes, Circle, arcs, PSet and Print')
        self.cmdClear = CommandButton(self, Caption='C&ls', Left=144, Top=362, Width=80, Height=30,
                                      TabIndex=7, ToolTipText='Cls: clears the drawing')
        self.lblStatus = Label(self, Caption='', Left=16, Top=404, Width=608, Height=25,
                               TabIndex=8)
        self.tmrClock = Timer(self, Interval=1000)
    # endregion

    def Form_Load(self):
        for style in STYLES:
            self.cboStyle.AddItem(style)
        self.cboStyle.ListIndex = 0
        self.picSketch.DrawWidth = self.hsbWidth.Value
        self.cmdShapes_Click()

    # --- the page's own Paint (a form's AutoRedraw is False too) -----------------------------
    def Form_Paint(self):
        # (no property changes here that repaint the form, e.g. ForeColor: Paint again, and again)
        self.CurrentX, self.CurrentY = 412, 240
        self.Print("Form_Paint draws this,")
        self.CurrentX = 412
        self.Print("under the page's controls.")
        self.Line(412, 284, 624, 284)

    # --- the sketch pad: AutoRedraw keeps what is drawn -------------------------------------
    def picSketch_MouseDown(self, Button, Shift, X, Y):
        self.picSketch.PSet(X, Y)  # the current point: where the line starts

    def picSketch_MouseMove(self, Button, Shift, X, Y):
        if Button == vpLeftButton:
            self.picSketch.Line(X, Y)  # from the current point to here

    def hsbWidth_Change(self):
        self.picSketch.DrawWidth = self.hsbWidth.Value
        self.lblStatus.Caption = f"DrawWidth = {self.hsbWidth.Value}"

    def cboStyle_Click(self):
        self.picSketch.DrawStyle = self.cboStyle.ListIndex
        self.lblStatus.Caption = f"DrawStyle = {self.cboStyle.Text}: draw with the mouse"

    def cmdClear_Click(self):
        self.picSketch.Cls()
        self.lblStatus.Caption = "Cls: the drawing is gone; draw with the mouse"

    def cmdShapes_Click(self):
        pic = self.picSketch
        width, style = pic.DrawWidth, pic.DrawStyle
        pic.Cls()
        pic.DrawWidth, pic.DrawStyle = 2, vpSolid
        pic.Line(10, 10, 110, 70, vpBlue, "B")  # a box
        pic.Line(120, 10, 220, 70, QBColor(10), "BF")  # filled with its color
        pic.FillStyle, pic.FillColor = vpCross, vpRed  # a hatch
        pic.Line(230, 10, 360, 70, vpRed, "B")
        pic.FillStyle, pic.FillColor = vpFSSolid, vpYellow
        pic.Circle(60, 130, 45, QBColor(6))
        pic.FillStyle = vpDiagonalCross
        pic.Circle(170, 130, 50, vpMagenta, Aspect=0.5)  # an ellipse
        pic.FillStyle, pic.FillColor = vpFSSolid, QBColor(9)
        pic.Circle(290, 130, 45, vpBlue, -math.pi / 4, -7 * math.pi / 4)  # a pie (negative)
        pic.FillStyle = vpFSTransparent
        pic.Circle(290, 130, 55, vpBlue, math.pi / 4, 3 * math.pi / 4)  # an arc
        for i in range(36):  # points along a wave
            pic.PSet(20 + i * 10, 215 + 20 * math.sin(i / 3), QBColor(12))
        pic.DrawWidth = 1
        text = "Print, centered with TextWidth"
        pic.CurrentX = (pic.ScaleWidth - pic.TextWidth(text)) / 2
        pic.CurrentY = pic.ScaleHeight - pic.TextHeight(text) - 10
        pic.Print(text)
        pic.DrawWidth, pic.DrawStyle = width, style
        self.lblStatus.Caption = ("AutoRedraw: the drawing stays; draw on it with the mouse "
                                  f"(Point at the box's middle: {pic.Point(170, 40):#08x})")

    # --- the clock: drawn in Paint, again each time the Timer refreshes it ----------------
    def tmrClock_Timer(self):
        self.picClock.Refresh()  # repaint: Paint draws it anew

    def picClock_Paint(self):
        pic = self.picClock
        # A User scale (ScaleMode 0), as in VB: the center is 0, 0, the face's edge 1
        # away, and up is up (the top is 1.1, the bottom -1.1)
        pic.Scale(-1.1, 1.1, 1.1, -1.1)
        pic.DrawWidth, pic.FillStyle, pic.FillColor = 2, vpFSSolid, 0xF0F0F0
        pic.Circle(0, 0, 1, 0x404040)
        for hour in range(12):
            angle = hour * math.pi / 6
            pic.Line(0.9 * math.cos(angle), 0.9 * math.sin(angle),
                     math.cos(angle), math.sin(angle), 0x404040)
        now = time.localtime()
        hands = ((now.tm_hour % 12 + now.tm_min / 60) / 12, 0.5, 5, 0x202020), \
            ((now.tm_min + now.tm_sec / 60) / 60, 0.75, 3, 0x202020), \
            (now.tm_sec / 60, 0.85, 1, vpRed)
        for turn, length, width, color in hands:
            angle = math.pi / 2 - turn * 2 * math.pi  # (DrawWidth: pixels, whatever the scale)
            pic.DrawWidth = width
            pic.Line(0, 0, length * math.cos(angle), length * math.sin(angle), color)
        pic.DrawWidth = 1
        stamp = time.strftime("%H:%M:%S", now)
        pic.CurrentX, pic.CurrentY = -pic.TextWidth(stamp) / 2, -0.4  # (TextWidth: its units)
        pic.Print(stamp)


if __name__ == "__main__":
    run(pgDrawing)
