"""Kitchen Sink page: the TextBox editing API, as a small code editor: the caret's line
and column (SelChange, CurrentLine, CurrentColumn), Tab typing a tab (AcceptsTab),
indenting a line (GetCharFromLine), going to a line (FirstVisibleLine), Undo and Redo
(CanUndo, CanRedo), the word under the mouse (GetCharFromPoint) and a list of completions
following the caret (CaretLeft, CaretTop, CaretHeight)."""

import keyword
import re

from vp6 import *

SAMPLE = '''def greet(name):
    """Say hello."""
    message = f"Hello, {name}!"
    print(message)
    return message


for person in ("Ada", "Grace", "Linus"):
    greet(person)
'''


class pgEditing(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Editing text'
        self.Width = 640
        self.Height = 440
        self.cmdUndo = CommandButton(self, Caption='&Undo', Left=16, Top=12, Width=80, Height=29,
                                     Enabled=False, TabIndex=1)
        self.cmdRedo = CommandButton(self, Caption='&Redo', Left=100, Top=12, Width=80, Height=29,
                                     Enabled=False, TabIndex=2)
        self.cmdIndent = CommandButton(self, Caption='&Indent', Left=184, Top=12, Width=80,
                                       Height=29, TabIndex=3,
                                       ToolTipText="Four spaces at the start of the caret's line")
        self.lblGoTo = Label(self, Caption='&Go to line:', Left=330, Top=18, Width=80, Height=22,
                             Alignment=1, TabIndex=4)
        self.txtLine = TextBox(self, Text='1', Left=414, Top=14, Width=50, Height=25, TabIndex=5)
        self.cmdGoTo = CommandButton(self, Caption='Go', Left=470, Top=12, Width=60, Height=29,
                                     TabIndex=6)
        self.txtCode = TextBox(self, MultiLine=True, Text='', Left=16, Top=50, Width=608,
                               Height=300, ScrollBars=3, AcceptsTab=True, FontName='Courier New',
                               TabIndex=7,
                               ToolTipText='Tab types a tab here (AcceptsTab); type a few letters for completions')
        self.lstComplete = ListBox(self, Left=16, Top=50, Width=160, Height=97, Visible=False,
                                   TabIndex=8,
                                   ToolTipText='Completions: click one, or press Enter')
        self.lblPosition = Label(self, Caption='', Left=16, Top=358, Width=300, Height=22,
                                 TabIndex=9)
        self.lblMouse = Label(self, Caption='', Left=320, Top=358, Width=304, Height=22,
                              Alignment=1, TabIndex=10)
        self.lblHelp = Label(self,
                             Caption='Type "pr" or "gr" for completions (Enter takes the first, Esc closes them). Tab types a tab.',
                             Left=16, Top=386, Width=608, Height=40, WordWrap=True, TabIndex=11)
    # endregion

    def Form_Load(self):
        self.completing = False
        self.txtCode.Text = SAMPLE
        self.txtCode.ClearUndo()  # (loading isn't an edit to undo)
        self.txtCode.SelStart = 0
        self.update_buttons()

    # --- where the caret is ---------------------------------------------------------------
    def txtCode_SelChange(self):
        code = self.txtCode
        self.lblPosition.Caption = (f"Line {code.CurrentLine + 1}, column "
                                    f"{code.CurrentColumn + 1} of {code.LineCount} lines")
        if self.lstComplete.Visible and not self.word_before_caret():
            self.lstComplete.Visible = False

    def txtCode_Change(self):
        self.update_buttons()
        if not self.completing:
            self.show_completions()

    def update_buttons(self):
        self.cmdUndo.Enabled = self.txtCode.CanUndo
        self.cmdRedo.Enabled = self.txtCode.CanRedo

    def txtCode_MouseMove(self, Button, Shift, X, Y):
        # The word under the mouse pointer
        code = self.txtCode
        position = code.GetCharFromPoint(X, Y)
        line = code.GetLineFromChar(position)
        column = code.GetColumnFromChar(position)
        text = code.GetLine(line)
        start = column
        while start > 0 and (text[start - 1].isalnum() or text[start - 1] == "_"):
            start -= 1
        match = re.match(r"\w+", text[start:])
        self.lblMouse.Caption = f"Under the mouse: {match.group()}" if match else ""

    # --- undo, indenting, going to a line ---------------------------------------------------
    def cmdUndo_Click(self):
        self.txtCode.Undo()
        self.update_buttons()

    def cmdRedo_Click(self):
        self.txtCode.Redo()
        self.update_buttons()

    def cmdIndent_Click(self):
        code = self.txtCode
        column = code.CurrentColumn
        code.SelStart = code.GetCharFromLine(code.CurrentLine)  # the line's start
        code.SelText = "    "
        code.CurrentColumn = column + 4  # the caret stays by its text
        code.SetFocus()

    def cmdGoTo_Click(self):
        code = self.txtCode
        try:
            line = int(self.txtLine.Text) - 1
            code.CurrentLine = line
        except (ValueError, IndexError):
            Beep()
            self.lblPosition.Caption = f"There are {code.LineCount} lines"
            return
        code.FirstVisibleLine = line  # that line at the top
        code.SetFocus()

    # --- completions under the caret ----------------------------------------------------------
    def word_before_caret(self) -> str:
        code = self.txtCode
        if code.SelLength:
            return ""
        before = code.GetLine(code.CurrentLine)[:code.CurrentColumn]
        match = re.search(r"\w+$", before)
        return match.group() if match else ""

    def show_completions(self):
        prefix = self.word_before_caret()
        words = set(keyword.kwlist) | {"print", "range", "len"} | set(
            re.findall(r"\w{4,}", self.txtCode.Text))
        matches = sorted(w for w in words if len(prefix) >= 2 and w.startswith(prefix)
                         and w != prefix)
        lst = self.lstComplete
        if not matches:
            lst.Visible = False
            return
        lst.Clear()
        for word in matches:
            lst.AddItem(word)
        code = self.txtCode
        # Just under the caret: the TextBox's place plus the caret's place in it
        lst.Move(code.Left + code.CaretLeft, code.Top + code.CaretTop + code.CaretHeight + 2)
        lst.Visible = True
        lst.ZOrder(0)

    def complete(self, index: int = 0):
        lst, code = self.lstComplete, self.txtCode
        word, prefix = lst.List[index], self.word_before_caret()
        lst.Visible = False
        self.completing = True
        code.SelText = word[len(prefix):]  # the rest of the word
        self.completing = False
        code.SetFocus()

    def lstComplete_Click(self):
        if self.lstComplete.Visible and self.lstComplete.ListIndex >= 0:
            self.complete(self.lstComplete.ListIndex)

    def txtCode_KeyPress(self, KeyAscii):
        if self.lstComplete.Visible:
            if KeyAscii in (vpKeyReturn, vpKeyTab):  # take the first completion
                self.complete(0)
                return 0
            if KeyAscii == vpKeyEscape:
                self.lstComplete.Visible = False
                return 0
        return KeyAscii


if __name__ == "__main__":
    run(pgEditing)
