"""Kitchen Sink page: a form shown in another form, popping out and back."""

from vp6 import *


class pgEmbedded(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Forms inside forms'
        self.Width = 640
        self.Height = 440
        self.picInfo = PictureBox(self, Left=0, Top=0, Width=640, Height=400, BorderStyle=0,
                                  Align=5, TabIndex=1,
                                  ToolTipText='Align = 5 - Fill: the space the button pane leaves')
        self.lblInfo = Label(self.picInfo, TextFormat=2,
                             Caption='This page is **a form of its own** (`pgEmbedded`), shown in the content pane with `ShowIn`: it fills the pane and follows its size.\n\n[Pop it out](popout) into a window of its own, or use the button below.',
                             Left=16, Top=16, Width=600, Height=120, WordWrap=True, TabIndex=2)
        self.lblShown = Label(self.picInfo, Caption='Shown here for 0 s', Left=16, Top=150,
                              Width=600, Height=25, TabIndex=3)
        self.tmrShown = Timer(self, Left=560, Top=150, Interval=1000, Enabled=False)
        self.picButtons = PictureBox(self, Left=0, Top=400, Width=640, Height=40, BorderStyle=0,
                                     Align=2, TabIndex=4,
                                     ToolTipText='Align = 2 - Bottom: docked to the bottom edge')
        self.cmdPop = CommandButton(self.picButtons, Caption='Pop &out', Left=16, Top=4, Width=160,
                                    Height=32, TabIndex=5,
                                    ToolTipText='Show this form in a window of its own, or put it back')
    # endregion

    def Form_Load(self):
        self.home = None  # the container it was in before popping out
        self.seconds = 0

    # In a container, the form is activated when it becomes visible there and
    # deactivated when it is hidden (another page chosen): the clock only runs
    # while the page can be seen
    def Form_Activate(self):
        self.tmrShown.Enabled = True

    def Form_Deactivate(self):
        self.tmrShown.Enabled = False

    def tmrShown_Timer(self):
        self.seconds += 1
        self.lblShown.Caption = f"Shown here for {self.seconds} s"

    # Two docked panes lay the form out: picButtons at the bottom (Align = Bottom)
    # and picInfo in the rest (Align = Fill); their Resize events size what is on them
    def picInfo_Resize(self):
        self.lblInfo.Width = max(self.picInfo.Width - 32, 16)

    def lblInfo_LinkClick(self, URL):
        # The Label's Caption is Markdown (TextFormat = 2): a link fires LinkClick
        if URL == "popout":
            self.cmdPop_Click()

    def cmdPop_Click(self):
        if self.Container is not None:  # shown in the Kitchen Sink's content pane
            self.home = self.Container
            self.ShowIn(None)  # a window of its own
            self.cmdPop.Caption = "Put &back"
        elif self.home is not None:
            self.ShowIn(self.home)
            self.cmdPop.Caption = "Pop &out"


if __name__ == "__main__":
    run(pgEmbedded)
