"""Kitchen Sink page: DriveListBox, DirListBox and FileListBox, linked together as in
VB (Change hands each control's choice to the next)."""

import os

from vp6 import *

PATTERNS = ("All files (*.*)|*.*", "Python (*.py)|*.py", "Pictures (*.png;*.jpg)|*.png;*.jpg",
            "Text (*.txt;*.md)|*.txt;*.md")


class pgFiles(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Files and folders'
        self.Width = 640
        self.Height = 440
        self.lblDrive = Label(self, Caption='&Drive:', Left=16, Top=16, Width=200, Height=22,
                              TabIndex=1)
        self.drvDrive = DriveListBox(self, Left=16, Top=40, Width=200, Height=25, TabIndex=2,
                                     ToolTipText='The drives (volumes): choosing one shows its folders')
        self.lblFolder = Label(self, Caption='F&older:', Left=16, Top=76, Width=200, Height=22,
                               TabIndex=3)
        self.dirFolder = DirListBox(self, Left=16, Top=100, Width=200, Height=230, TabIndex=4,
                                    ToolTipText='Double-click a folder to open it')
        self.lblFiles = Label(self, Caption='F&iles:', Left=232, Top=16, Width=224, Height=22,
                              TabIndex=5)
        self.filFiles = FileListBox(self, Left=232, Top=40, Width=224, Height=250, TabIndex=6,
                                    ToolTipText='The files in the folder matching the pattern')
        self.lblPattern = Label(self, Caption='&Type:', Left=232, Top=304, Width=44, Height=22,
                                TabIndex=7)
        self.cboPattern = ComboBox(self, Style=2, Left=276, Top=300, Width=180, Height=25,
                                   TabIndex=8, ToolTipText="Sets the FileListBox's Pattern")
        self.chkHidden = CheckBox(self, Caption='S&how hidden files and folders', Left=16, Top=340,
                                  Width=260, Height=25, TabIndex=9)
        self.imgPreview = Image(self, Left=472, Top=40, Width=152, Height=152, Stretch=True,
                                BorderStyle=1, ToolTipText='The chosen picture')
        self.lblChosen = Label(self, Caption='Choose a file', Left=472, Top=200, Width=152,
                               Height=110, WordWrap=True, TabIndex=10)
        self.lblEvent = Label(self, Caption='', Left=16, Top=380, Width=608, Height=25,
                              TabIndex=11)
    # endregion

    def Form_Load(self):
        for pattern in PATTERNS:
            self.cboPattern.AddItem(pattern.split("|")[0])
        self.cboPattern.ListIndex = 0
        # Start in the project's folder (the program's current folder)
        self.dirFolder.Path = os.getcwd()
        self.filFiles.Path = self.dirFolder.Path

    def drvDrive_Change(self):
        # A drive was chosen: show its folders
        self.dirFolder.Path = self.drvDrive.Drive

    def dirFolder_Change(self):
        # A folder was opened: list its files
        self.filFiles.Path = self.dirFolder.Path

    def dirFolder_Click(self):
        index = self.dirFolder.ListIndex  # -1: the folder itself, -2 its parent..., 0... in it
        self.lblEvent.Caption = (f"Selected List({index}): "
                                 f"{os.path.basename(self.dirFolder.List(index)) or '/'} "
                                 "(double-click to open it)")

    def filFiles_PathChange(self):
        self.lblEvent.Caption = (f"PathChange: {self.filFiles.Path} has "
                                 f"{self.filFiles.ListCount} matching files")

    def filFiles_PatternChange(self):
        self.lblEvent.Caption = (f"PatternChange: {self.filFiles.Pattern} "
                                 f"({self.filFiles.ListCount} files)")

    def filFiles_Click(self):
        path = os.path.join(self.filFiles.Path, self.filFiles.FileName)
        self.lblChosen.Caption = f"{self.filFiles.FileName}\n{os.path.getsize(path):,} bytes"
        picture = path.lower().endswith((".png", ".jpg", ".jpeg", ".gif", ".bmp"))
        self.imgPreview.Picture = path if picture else ""

    def filFiles_DblClick(self):
        MsgBox(f"You double-clicked {self.filFiles.FileName}", vpInformation, "FileListBox")

    def cboPattern_Click(self):
        self.filFiles.Pattern = PATTERNS[self.cboPattern.ListIndex].split("|")[1]

    def chkHidden_Click(self):
        hidden = self.chkHidden.Value == vpChecked
        self.dirFolder.ShowHidden = hidden
        self.filFiles.Hidden = hidden


if __name__ == "__main__":
    run(pgFiles)
