"""Kitchen Sink page: App, Screen, Forms, Clipboard, Debug, DoEvents, End."""

import time

from vp6 import *


class pgGlobals(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'App, Screen, Clipboard...'
        self.Width = 640
        self.Height = 440
        self.lblInfo = Label(self, Caption='', Left=16, Top=16, Width=600, Height=100,
                             WordWrap=True, TabIndex=1)
        self.txtClip = TextBox(self, Text='Copy me', Left=16, Top=130, Width=240, Height=25,
                               TabIndex=2)
        self.cmdCopy = CommandButton(self, Caption='&Copy', Left=270, Top=128, Width=100,
                                     Height=30, TabIndex=3)
        self.cmdPaste = CommandButton(self, Caption='&Paste', Left=380, Top=128, Width=100,
                                      Height=30, TabIndex=4)
        self.cmdCount = CommandButton(self, Caption='Count to &100', Left=16, Top=176, Width=160,
                                      Height=32, TabIndex=5,
                                      ToolTipText='A long loop that stays responsive thanks to DoEvents')
        self.cmdDebug = CommandButton(self, Caption='Debug.P&rint', Left=16, Top=216, Width=160,
                                      Height=32, TabIndex=6,
                                      ToolTipText="Writes to the IDE's Immediate window (stdout)")
        self.cmdEnd = CommandButton(self, Caption='&End the program', Left=16, Top=256, Width=160,
                                    Height=32, TabIndex=7,
                                    ToolTipText='End: stops at once, without Form_Unload')
        self.lblResult = Label(self, Caption='', Left=190, Top=182, Width=430, Height=25,
                               TabIndex=8)
    # endregion

    def Form_Load(self):
        self.lblInfo.Caption = (
            f"App.Title: {App.Title}   App.EXEName: {App.EXEName}\n"
            f"App.Path: {App.Path}\n"
            f"Screen: {Screen.Width} x {Screen.Height}   Forms loaded: {Forms.Count}\n"
            f"RGB(255, 0, 0) = {RGB(255, 0, 0)} = vpRed   QBColor(14) = {QBColor(14):#08x}")

    def cmdCopy_Click(self):
        Clipboard.SetText(self.txtClip.Text)
        self.lblResult.Caption = f"Copied {Clipboard.GetText()!r} to the clipboard"

    def cmdPaste_Click(self):
        self.txtClip.Text = Clipboard.GetText()

    def cmdCount_Click(self):
        for i in range(1, 101):
            self.cmdCount.Caption = f"Counting {i}"
            DoEvents()  # keep the window responsive during the loop
            time.sleep(0.01)
        self.cmdCount.Caption = "Count to &100"

    def cmdDebug_Click(self):
        Debug.Print("Hello from the Kitchen Sink:", App.Title)
        self.lblResult.Caption = "Written with Debug.Print (see the Immediate window)"

    def cmdEnd_Click(self):
        End()  # ends at once, without Form_Unload


if __name__ == "__main__":
    run(pgGlobals)
