"""Kitchen Sink page: App (version, PrevInstance), Command(), settings (SaveSetting,
GetSetting, GetAllSettings, DeleteSetting), Screen (Fonts), Forms, Clipboard, Debug,
DoEvents, End."""

import time

from vp6 import *


class pgGlobals(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'App, Screen, settings...'
        self.Width = 640
        self.Height = 440
        self.lblInfo = Label(self, Caption='', Left=16, Top=8, Width=608, Height=134,
                             WordWrap=True, TabIndex=1)
        self.txtClip = TextBox(self, Text='Copy me', Left=16, Top=152, Width=240, Height=25,
                               TabIndex=2)
        self.cmdCopy = CommandButton(self, Caption='&Copy', Left=270, Top=150, Width=100,
                                     Height=30, TabIndex=3)
        self.cmdPaste = CommandButton(self, Caption='&Paste', Left=380, Top=150, Width=100,
                                      Height=30, TabIndex=4)
        self.cmdSave = CommandButton(self, Caption='&Save setting', Left=16, Top=190, Width=120,
                                     Height=30, TabIndex=5,
                                     ToolTipText='SaveSetting: the text above, there next time')
        self.cmdForget = CommandButton(self, Caption='&Forget', Left=144, Top=190, Width=100,
                                       Height=30, TabIndex=6,
                                       ToolTipText="DeleteSetting: the program's settings section")
        self.lblSettings = Label(self, Caption='', Left=254, Top=196, Width=370, Height=25,
                                 TabIndex=7)
        self.cboFont = ComboBox(self, Style=2, Left=16, Top=232, Width=240, Height=25, TabIndex=8,
                                ToolTipText='Screen.Fonts: the fonts installed')
        self.lblFont = Label(self, Caption='The quick brown fox', Left=270, Top=228, Width=354,
                             Height=32, TabIndex=9)
        self.cmdCount = CommandButton(self, Caption='Count to &100', Left=16, Top=272, Width=160,
                                      Height=32, TabIndex=10,
                                      ToolTipText='A long loop that stays responsive thanks to DoEvents')
        self.cmdDebug = CommandButton(self, Caption='Debug.P&rint', Left=16, Top=312, Width=160,
                                      Height=32, TabIndex=11,
                                      ToolTipText="Writes to the IDE's Immediate window (stdout)")
        self.cmdEnd = CommandButton(self, Caption='&End the program', Left=16, Top=352, Width=160,
                                    Height=32, TabIndex=12,
                                    ToolTipText='End: stops at once, without Form_Unload')
        self.lblResult = Label(self, Caption='', Left=190, Top=278, Width=434, Height=25,
                               TabIndex=13)
    # endregion

    def Form_Load(self):
        self.lblInfo.Caption = (
            f"App.Title: {App.Title}   App.EXEName: {App.EXEName}   "
            f"Version {App.Major}.{App.Minor}.{App.Revision}\n"
            f"App.ProductName: {App.ProductName}   App.CompanyName: {App.CompanyName}\n"
            f"App.FileDescription: {App.FileDescription}\n"
            f"App.Path: {App.Path}\n"
            f"App.PrevInstance: {App.PrevInstance}   Command(): {Command()!r}\n"
            f"Screen: {Screen.Width} x {Screen.Height}, {Screen.FontCount} fonts   "
            f"Forms loaded: {Forms.Count}\n"
            f"RGB(255, 0, 0) = {RGB(255, 0, 0)} = vpRed   QBColor(14) = {QBColor(14):#08x}")
        # The text saved last time (the Save setting button), else "Copy me"
        self.txtClip.Text = GetSetting(App.Title, "Globals", "Text", "Copy me")
        self.show_settings()
        self.cboFont.Clear()
        for name in Screen.Fonts:
            self.cboFont.AddItem(name)
            if name == self.lblFont.FontName:
                self.cboFont.ListIndex = self.cboFont.NewIndex  # the label's font

    # --- settings ---------------------------------------------------------------------------
    def cmdSave_Click(self):
        SaveSetting(App.Title, "Globals", "Text", self.txtClip.Text)
        SaveSetting(App.Title, "Globals", "Saved", time.strftime("%H:%M:%S"))
        self.show_settings()

    def cmdForget_Click(self):
        DeleteSetting(App.Title, "Globals")
        self.show_settings()

    def show_settings(self):
        pairs = GetAllSettings(App.Title, "Globals")
        self.lblSettings.Caption = "Settings: " + (
            ", ".join(f"{key}={value!r}" for key, value in pairs) if pairs else "none saved")

    def cboFont_Click(self):
        self.lblFont.FontName = self.cboFont.Text

    # --- clipboard, DoEvents, Debug, End ----------------------------------------------------
    def cmdCopy_Click(self):
        Clipboard.SetText(self.txtClip.Text)
        self.lblResult.Caption = f"Copied {Clipboard.GetText()!r} to the clipboard"

    def cmdPaste_Click(self):
        self.txtClip.Text = Clipboard.GetText()

    def cmdCount_Click(self):
        for i in range(1, 101):
            self.cmdCount.Caption = f"Counting {i}"
            DoEvents()  # keep the window responsive during the loop
            time.sleep(0.01)
        self.cmdCount.Caption = "Count to &100"

    def cmdDebug_Click(self):
        Debug.Print("Hello from the Kitchen Sink:", App.Title)
        self.lblResult.Caption = "Written with Debug.Print (see the Immediate window)"

    def cmdEnd_Click(self):
        End()  # ends at once, without Form_Unload


if __name__ == "__main__":
    run(pgGlobals)
