"""Kitchen Sink page: FlexGrid. A price list (FormatString headings and alignments, rows
from AddItem with RowData, sorting by the clicked heading, the current cell in
RowColChange) and an editable property sheet with an editor per cell (text, list, check
box, color, a "..." button), checked in ValidateEdit and applied in AfterEdit."""

from vp6 import *

FRUIT = (("Apple", 1.20, 140), ("Banana", 0.35, 260), ("Cherry", 4.80, 35),
         ("Mango", 2.10, 48), ("Kiwi", 0.60, 90), ("Plum", 0.45, 120))
SORTS = {False: vpGridSortGenericAscending, True: vpGridSortGenericDescending}
ALIGNMENTS = ("Left", "Right", "Center")  # vpLeftJustify, vpRightJustify, vpCenter


class pgGrid(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'FlexGrid'
        self.Width = 640
        self.Height = 440
        self.grdPrices = FlexGrid(self, Left=16, Top=16, Width=300, Height=200, Rows=1, Cols=4,
                                  FormatString='|<Fruit|>Price|>In stock', SelectionMode=1,
                                  TabIndex=1,
                                  ToolTipText='Click a heading to sort by it (again: the other way)')
        self.lblCell = Label(self, Caption='', Left=16, Top=222, Width=300, Height=40,
                             WordWrap=True, TabIndex=2)
        self.grdProps = FlexGrid(self, Left=332, Top=16, Width=292, Height=200, Rows=7,
                                 FormatString='Property|<Value', Editable=True, TabIndex=3,
                                 ToolTipText='Double-click, F2 or type to edit; click a check box or a ... button')
        self.lblSample = Label(self, Caption='A sample label', Left=332, Top=230, Width=292,
                               Height=40, BorderStyle=1, TabIndex=4)
        self.lblEvent = Label(self, Caption='', Left=16, Top=290, Width=608, Height=40,
                              WordWrap=True, TabIndex=5)
    # endregion

    def Form_Load(self):
        # --- the price list -----------------------------------------------------------------
        grid = self.grdPrices
        for number, (fruit, price, stock) in enumerate(FRUIT, start=1):
            grid.AddItem(f"{number}\t{fruit}\t{price:.2f}\t{stock}")
            grid.RowData[grid.Rows - 1] = number * 100  # an id kept with the row
        for col, width in enumerate((30, 90, 70, 80)):
            grid.ColWidth[col] = width
        self.descending = {}
        # --- the property sheet: one editor per row -------------------------------------------
        props = self.grdProps
        props.ColWidth[0] = 100
        props.ColWidth[1] = 170
        rows = (("Caption", "A sample label", vpGridEditText, None),
                ("Visible", "True", vpGridEditCheck, None),
                ("Alignment", "Left", vpGridEditList, ALIGNMENTS),
                ("BackColor", "#fff2a8", vpGridEditColor, None),
                ("FontName", "", vpGridEditButton, None),
                ("Width", "292", vpGridEditText, None))
        for row, (name, value, editor, choices) in enumerate(rows, start=1):
            props.TextMatrix[row, 0] = name
            props.Row, props.Col = row, 1
            props.CellEditor = editor
            if choices:
                props.CellList = list(choices)
            props.Text = value
        props.Row, props.Col = 1, 1
        self.apply_all()

    # --- the price list ----------------------------------------------------------------------
    def grdPrices_Click(self):
        grid = self.grdPrices
        if grid.MouseRow == 0 and grid.MouseCol >= 1:  # a heading: sort by its column
            self.sort_by(grid.MouseCol)

    def sort_by(self, col):
        grid = self.grdPrices
        descending = self.descending.get(col, False)
        grid.Col = col
        grid.Sort = SORTS[descending]
        self.descending[col] = not descending
        self.lblEvent.Caption = (f"Sorted by {grid.TextMatrix(0, col)}, "
                                 f"{'descending' if descending else 'ascending'}")

    def grdPrices_RowColChange(self):
        grid = self.grdPrices
        row = grid.Row
        self.lblCell.Caption = (f"Row {row}: {grid.TextMatrix(row, 1)} costs "
                                f"{grid.TextMatrix(row, 2)} (RowData {grid.RowData(row)})")

    # --- the property sheet ------------------------------------------------------------------
    def grdProps_ValidateEdit(self, Row, Col, Text):
        if self.grdProps.TextMatrix(Row, 0) == "Width" and not Text.isdigit():
            Beep()
            self.lblEvent.Caption = f"Width must be a number, not {Text!r} (ValidateEdit)"
            return True  # cancel: the old value stays
        return False

    def grdProps_AfterEdit(self, Row, Col):
        name, value = self.grdProps.TextMatrix(Row, 0), self.grdProps.TextMatrix(Row, 1)
        self.lblEvent.Caption = f"{name} = {value} (AfterEdit)"
        self.apply_all()

    def grdProps_CellButtonClick(self, Row, Col):
        # A "..." button: ask for the value some other way
        name = InputBox("Font name:", "FontName", self.grdProps.TextMatrix(Row, Col))
        if name:
            self.grdProps.TextMatrix[Row, Col] = name
            self.apply_all()

    def apply_all(self):
        props, label = self.grdProps, self.lblSample
        values = {props.TextMatrix(r, 0): props.TextMatrix(r, 1) for r in range(1, props.Rows)}
        label.Caption = values["Caption"]
        label.Visible = values["Visible"] == "True"
        label.Alignment = ALIGNMENTS.index(values["Alignment"])
        label.BackColor = values["BackColor"] or None
        label.ForeColor = vpBlack
        label.FontName = values["FontName"] or None
        label.Width = int(values["Width"])


if __name__ == "__main__":
    run(pgGrid)
