"""Kitchen Sink page: the introduction (a Markdown Label with links)."""

from vp6 import *


class pgIntro(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Introduction'
        self.Width = 640
        self.Height = 440
        self.lblIntro = Label(self, TextFormat=2,
                              Caption="# Welcome to the VP6 Kitchen Sink\n\nThis project shows **everything VP6 can do**, one topic at a time. Choose a topic in the tree on the left: each one is a form of its own (open it in the designer to see how it's made), shown here with `ShowIn`.\n\n- [Text and labels](text) · [Buttons and options](buttons) · [Lists](lists) · [Scroll bars](scrollbars)\n- [Pictures](pictures) · [Lines and z-order](zorder) · [TreeView](tree) · [Timer](timer)\n- [Docked panes and Splitter](layout) · [Scrolling](scrolling) · [Forms inside forms](embedded)\n- [Dialogs](dialogs) · [Color schemes](schemes) · [Keyboard](keyboard) · [Mouse](mouse)\n- [Control arrays](arrays) · [Menus](menus) · [App, Screen, settings...](globals)\n\nPress **F1** for the keyboard shortcuts.",
                              Left=16, Top=16, Width=600, Height=400, WordWrap=True, TabIndex=1)
    # endregion

    shell = None  # the Kitchen Sink window showing this page (None when run on its own)

    def Form_Resize(self):
        self.lblIntro.Move(16, 16, max(self.ScaleWidth - 32, 100), max(self.ScaleHeight - 32, 100))

    def lblIntro_LinkClick(self, URL):
        # The links in the Markdown caption are page keys: show that page
        if self.shell is not None:
            self.shell.show_page(URL)


if __name__ == "__main__":
    run(pgIntro)
