"""Kitchen Sink page: KeyPreview, KeyPress, Default/Cancel buttons, Validate and
CausesValidation, ActiveControl and SendKeys."""

from vp6 import *


class pgKeyboard(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Keyboard'
        self.Width = 640
        self.Height = 440
        self.KeyPreview = True
        self.lblKeys = Label(self,
                             Caption="Press keys: this page's Form_KeyDown sees them first (KeyPreview = True).",
                             Left=16, Top=16, Width=600, Height=25, TabIndex=1)
        self.lblLastKey = Label(self, Caption='', Left=16, Top=44, Width=600, Height=25,
                                TabIndex=2)
        self.lblUpper = Label(self, Caption='Upper case:', Left=16, Top=90, Width=110, Height=25,
                              TabIndex=3)
        self.txtUpper = TextBox(self, Text='', Left=130, Top=86, Width=200, Height=25, TabIndex=4,
                                ToolTipText='KeyPress returns the upper-case key')
        self.lblDigits = Label(self, Caption='Digits only:', Left=16, Top=126, Width=110,
                               Height=25, TabIndex=5)
        self.txtDigits = TextBox(self, Text='', Left=130, Top=122, Width=200, Height=25,
                                 TabIndex=6,
                                 ToolTipText="KeyPress returns 0 for other keys: they're swallowed")
        self.cmdOK = CommandButton(self, Caption='OK (Enter)', Left=16, Top=170, Width=140,
                                   Height=32, Default=True, TabIndex=7)
        self.cmdCancel = CommandButton(self, Caption='Cancel (Esc)', Left=170, Top=170, Width=140,
                                       Height=32, Cancel=True, TabIndex=8)
        self.lblButtons = Label(self, Caption='', Left=330, Top=176, Width=290, Height=25,
                                TabIndex=9)
        self.lblAge = Label(self, Caption='&Age:', Left=16, Top=230, Width=110, Height=25,
                            TabIndex=10)
        self.txtAge = TextBox(self, Text='30', Left=130, Top=226, Width=80, Height=25, TabIndex=11,
                              ToolTipText='Validate: the focus stays here until it is a number from 0 to 130')
        self.lblCity = Label(self, Caption='Ci&ty:', Left=16, Top=266, Width=110, Height=25,
                             TabIndex=12)
        self.txtCity = TextBox(self, Text='', Left=130, Top=262, Width=200, Height=25, TabIndex=13)
        self.cmdHelp = CommandButton(self, Caption='&Help', Left=350, Top=224, Width=100,
                                     Height=30, TabIndex=14,
                                     ToolTipText="CausesValidation = False: works while Age isn't valid",
                                     CausesValidation=False)
        self.lblValid = Label(self, Caption='', Left=16, Top=300, Width=600, Height=25,
                              TabIndex=15)
        self.lblActive = Label(self, Caption='', Left=16, Top=330, Width=600, Height=25,
                               TabIndex=16)
        self.cmdType = CommandButton(self, Caption='Type &for me', Left=16, Top=370, Width=140,
                                     Height=32, TabIndex=17,
                                     ToolTipText='SendKeys: types into the upper-case box, then Enter')
        self.tmrActive = Timer(self, Left=600, Top=370, Interval=250)
    # endregion

    def Form_KeyDown(self, KeyCode, Shift):
        mods = [name for bit, name in ((vpShiftMask, "Shift"), (vpCtrlMask, "Ctrl"),
                                       (vpAltMask, "Alt")) if Shift & bit]
        self.lblLastKey.Caption = f"KeyDown: key code {KeyCode} {'+'.join(mods)}"

    def Form_KeyUp(self, KeyCode, Shift):
        self.lblLastKey.Caption += " (released)"

    def txtUpper_KeyPress(self, KeyAscii):
        return ord(chr(KeyAscii).upper())  # another code replaces the key

    def txtDigits_KeyPress(self, KeyAscii):
        if not chr(KeyAscii).isdigit() and KeyAscii != vpKeyBack:
            return 0  # 0 swallows the key

    def cmdOK_Click(self):
        self.lblButtons.Caption = "OK: the Default button (Enter)"

    def cmdCancel_Click(self):
        self.lblButtons.Caption = "Cancel: the Cancel button (Esc)"

    # --- Validate: checked before the focus leaves -----------------------------------------------
    def txtAge_Validate(self):
        text = self.txtAge.Text.strip()
        if not (text.isdigit() and int(text) <= 130):
            Beep()
            self.lblValid.Caption = f"{text!r} isn't an age: the focus stays in Age (Validate)"
            return True  # cancel: the focus doesn't leave
        self.lblValid.Caption = f"Age {text}: fine"
        return False

    def cmdHelp_Click(self):
        # CausesValidation = False: clicking it doesn't wait for a valid Age
        self.lblValid.Caption = "Help: an age is a whole number from 0 to 130"

    # --- the control with the focus ---------------------------------------------------------------
    def tmrActive_Timer(self):
        active = Screen.ActiveControl
        mine = self.ActiveControl
        self.lblActive.Caption = (f"Screen.ActiveControl: {active.Name if active else '-'}; "
                                  f"this page's ActiveControl: {mine.Name if mine else '-'}")

    # --- SendKeys: keys typed for you ------------------------------------------------------------
    def cmdType_Click(self):
        self.txtUpper.Text = ""
        self.txtUpper.SetFocus()
        # Typed into the box with the focus once this handler is done; its KeyPress
        # makes them upper case, and ~ (Enter) clicks the Default button
        SendKeys("typed for you~")


if __name__ == "__main__":
    run(pgKeyboard)
