"""Kitchen Sink page: KeyPreview, KeyPress and Default/Cancel buttons."""

from vp6 import *


class pgKeyboard(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Keyboard'
        self.Width = 640
        self.Height = 440
        self.KeyPreview = True
        self.lblKeys = Label(self,
                             Caption="Press keys: this page's Form_KeyDown sees them first (KeyPreview = True).",
                             Left=16, Top=16, Width=600, Height=25, TabIndex=1)
        self.lblLastKey = Label(self, Caption='', Left=16, Top=44, Width=600, Height=25,
                                TabIndex=2)
        self.lblUpper = Label(self, Caption='Upper case:', Left=16, Top=90, Width=110, Height=25,
                              TabIndex=3)
        self.txtUpper = TextBox(self, Text='', Left=130, Top=86, Width=200, Height=25, TabIndex=4,
                                ToolTipText='KeyPress returns the upper-case key')
        self.lblDigits = Label(self, Caption='Digits only:', Left=16, Top=126, Width=110,
                               Height=25, TabIndex=5)
        self.txtDigits = TextBox(self, Text='', Left=130, Top=122, Width=200, Height=25,
                                 TabIndex=6,
                                 ToolTipText="KeyPress returns 0 for other keys: they're swallowed")
        self.cmdOK = CommandButton(self, Caption='OK (Enter)', Left=16, Top=170, Width=140,
                                   Height=32, Default=True, TabIndex=7)
        self.cmdCancel = CommandButton(self, Caption='Cancel (Esc)', Left=170, Top=170, Width=140,
                                       Height=32, Cancel=True, TabIndex=8)
        self.lblButtons = Label(self, Caption='', Left=330, Top=176, Width=290, Height=25,
                                TabIndex=9)
    # endregion

    def Form_KeyDown(self, KeyCode, Shift):
        mods = [name for bit, name in ((vpShiftMask, "Shift"), (vpCtrlMask, "Ctrl"),
                                       (vpAltMask, "Alt")) if Shift & bit]
        self.lblLastKey.Caption = f"KeyDown: key code {KeyCode} {'+'.join(mods)}"

    def Form_KeyUp(self, KeyCode, Shift):
        self.lblLastKey.Caption += " (released)"

    def txtUpper_KeyPress(self, KeyAscii):
        return ord(chr(KeyAscii).upper())  # another code replaces the key

    def txtDigits_KeyPress(self, KeyAscii):
        if not chr(KeyAscii).isdigit() and KeyAscii != vpKeyBack:
            return 0  # 0 swallows the key

    def cmdOK_Click(self):
        self.lblButtons.Caption = "OK: the Default button (Enter)"

    def cmdCancel_Click(self):
        self.lblButtons.Caption = "Cancel: the Cancel button (Esc)"


if __name__ == "__main__":
    run(pgKeyboard)
