"""Kitchen Sink page: how the window is laid out (Align, Splitter, Fill)."""

from vp6 import *


class pgLayout(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Docked panes and Splitter'
        self.Width = 640
        self.Height = 440
        self.lblLayout = Label(self, TextFormat=2,
                               Caption="This window is laid out with **docked controls** (`Align`), not code:\n\n- `sbStatus`: a **StatusBar**, *Bottom* (click its clock to see the date)\n- `tbrMain`: a **Toolbar**, *Top*: the pages, the navigation pane and the colors\n- `picNav`: *Left*, holding the TreeView\n- `splNav`: a **Splitter** beside it; drag it to resize the navigation pane\n- `picHeader`: *Top*, the page title\n- `picContent`: *Fill*, the rest, with `ScrollBars`: the pages are shown in it\n\nThey follow the window's size; their `Resize` events size what is on them.",
                               Left=16, Top=16, Width=600, Height=270, WordWrap=True, TabIndex=1)
        self.chkNav = CheckBox(self, Caption='Show the &navigation pane (also in the View menu)',
                               Left=16, Top=296, Width=360, Height=25, Value=1, TabIndex=2)
        self.cmdWider = CommandButton(self, Caption='Make it &wider', Left=16, Top=330, Width=180,
                                      Height=32, TabIndex=3)
    # endregion

    shell = None  # the Kitchen Sink window showing this page (None when run on its own)

    def Form_Resize(self):
        self.lblLayout.Width = max(self.ScaleWidth - 32, 100)

    def chkNav_Click(self):
        if self.shell is not None:
            self.shell.show_navigation(self.chkNav.Value == vpChecked)

    def cmdWider_Click(self):
        if self.shell is not None:
            self.shell.picNav.Width += 40  # the Fill pane gives up the space


if __name__ == "__main__":
    run(pgLayout)
