"""Kitchen Sink page: ListView."""

from vp6 import *


class pgListView(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'ListView'
        self.Width = 640
        self.Height = 440
        self.lvwPets = ListView(self, Left=16, Top=16, Width=400, Height=260, View=3,
                                ColumnHeaders=['Name|name|150', 'Kind|kind|120', 'Legs|legs|70|right'],
                                ListItems=['Rex|rex|paw|paw|Dog|4', 'Tom|tom|paw|paw|Cat|4', 'Polly|polly|star|star|Parrot|2', 'Fern|fern|leaf|leaf|Plant|0', 'Basket|basket|folder|folder|Thing|0'],
                                Icons='imlLarge', SmallIcons='imlSmall', TabIndex=1,
                                ToolTipText='Click a column title to sort by it; again to reverse')
        self.lblView = Label(self, Caption='View:', Left=430, Top=20, Width=60, Height=25,
                             TabIndex=2)
        self.cboView = ComboBox(self, Style=2, Left=490, Top=16, Width=130, Height=25,
                                List=['Icon', 'SmallIcon', 'List', 'Report'], Text='Report',
                                TabIndex=3)
        self.chkChecks = CheckBox(self, Caption='Check &boxes', Left=430, Top=56, Width=190,
                                  Height=25, TabIndex=4)
        self.chkMulti = CheckBox(self, Caption='&Multiple selection', Left=430, Top=86, Width=190,
                                 Height=25, TabIndex=5)
        self.txtName = TextBox(self, Text='Nemo', Left=430, Top=130, Width=190, Height=25,
                               TabIndex=6)
        self.cmdAdd = CommandButton(self, Caption='&Add a fish', Left=430, Top=162, Width=190,
                                    Height=30, TabIndex=7)
        self.cmdRemove = CommandButton(self, Caption='&Remove the selected', Left=430, Top=198,
                                       Width=190, Height=30, TabIndex=8)
        self.lblEvent = Label(self, Caption='Click an item, or a column title', Left=16, Top=290,
                              Width=600, Height=25, TabIndex=9)
        self.imlLarge = ImageList(self, Left=430, Top=244,
                                  ListImages=['images/paw.png|paw', 'images/star.png|star', 'images/leaf.png|leaf', 'images/folder.png|folder'])
        self.imlSmall = ImageList(self, Left=470, Top=244, ImageWidth=16, ImageHeight=16,
                                  ListImages=['images/paw.png|paw', 'images/star.png|star', 'images/leaf.png|leaf', 'images/folder.png|folder'])
    # endregion

    # --- the ListView -------------------------------------------------------------------------
    def lvwPets_ItemClick(self, Item):
        # Item: the ListItem clicked; its SubItems are the Report view's other columns
        self.lblEvent.Caption = (f"{Item.Text}: {Item.SubItems(1)}, {Item.SubItems(2)} legs "
                                 f"(item {Item.Index} of {self.lvwPets.ListItems.Count})")

    def lvwPets_ColumnClick(self, ColumnHeader):
        # Sort by the column clicked; clicking it again reverses the order
        pets = self.lvwPets
        column = ColumnHeader.SubItemIndex  # 0 = the Text, 1 = the first SubItem...
        if pets.Sorted and pets.SortKey == column:
            pets.SortOrder = vpLvwDescending if pets.SortOrder == vpLvwAscending \
                else vpLvwAscending
        else:
            pets.SortKey, pets.SortOrder = column, vpLvwAscending
        pets.Sorted = True
        order = "Z to A" if pets.SortOrder == vpLvwDescending else "A to Z"
        self.lblEvent.Caption = f"Sorted by {ColumnHeader.Text}, {order}"

    def lvwPets_ItemCheck(self, Item):
        self.lblEvent.Caption = f"{Item.Text} is {'checked' if Item.Checked else 'unchecked'}"

    # --- around it -------------------------------------------------------------------------------
    def cboView_Click(self):
        self.lvwPets.View = self.cboView.ListIndex  # vpLvwIcon ... vpLvwReport

    def chkChecks_Click(self):
        self.lvwPets.Checkboxes = self.chkChecks.Value == vpChecked

    def chkMulti_Click(self):
        self.lvwPets.MultiSelect = self.chkMulti.Value == vpChecked

    def cmdAdd_Click(self):
        name = self.txtName.Text.strip() or "Fish"
        item: ListItem = self.lvwPets.ListItems.Add(Text=name, Icon="star",
                                                    SmallIcon="star")
        item.SubItems[1] = "Fish"  # VB's Item.SubItems(1) = "Fish"
        item.SubItems[2] = "0"
        item.EnsureVisible()
        self.lvwPets.SelectedItem = item
        self.lblEvent.Caption = f"Added {name} as item {item.Index}"

    def cmdRemove_Click(self):
        removed = [item.Text for item in self.lvwPets.ListItems if item.Selected]
        for item in list(self.lvwPets.ListItems):
            if item.Selected:
                self.lvwPets.ListItems.Remove(item)
        self.lblEvent.Caption = f"Removed {', '.join(removed)}" if removed else \
            "Select an item first"


if __name__ == "__main__":
    run(pgListView)
