"""Kitchen Sink page: three MarkdownBoxes showing the same text: its source with the
syntax colored (Mode = vpMarkdownSource), a visual editor (vpMarkdownVisual) and a
rendered preview (vpMarkdownPreview). Editing either editor updates the other two (their
Change events); the buttons format the selection in the editor used last (ApplyFormat)."""

from vp6 import *

SAMPLE = """# Markdown

Type in the **source** or in the *visual* editor: the other two follow.
Ctrl+B and Ctrl+I format, ~~strike~~ and `code` too.

## Lists

- Enter continues a list
- an empty item ends it
    - nested items

1. First
2. Second

- [x] task lists
- [ ] tables

> A quote, and [a link](https://www.python.org): click it in the preview.

```python
print("Hello from VP6")
```

| Mode | Shows |
| --- | --- |
| Source | the Markdown |
| Visual | an editor |
| Preview | the page |

![VP6](vp6.png)
"""

# The format of each button of cmdFormat, in order
FORMATS = (vpMarkdownBold, vpMarkdownItalic, vpMarkdownStrikeThru, vpMarkdownCode,
           vpMarkdownHeading1, vpMarkdownHeading2, vpMarkdownHeading3, vpMarkdownParagraph,
           vpMarkdownBulletList, vpMarkdownNumberedList, vpMarkdownQuote)


class pgMarkdown(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Markdown'
        self.Width = 640
        self.Height = 440
        self.cmdFormat = ControlArray()
        self.cmdFormat[0] = CommandButton(self, Caption='B', Left=16, Top=12, Width=40, Height=29,
                                          FontBold=True, TabIndex=1,
                                          ToolTipText='Bold (vpMarkdownBold, Ctrl+B)')
        self.cmdFormat[1] = CommandButton(self, Caption='I', Left=58, Top=12, Width=40, Height=29,
                                          FontItalic=True, TabIndex=2,
                                          ToolTipText='Italic (vpMarkdownItalic, Ctrl+I)')
        self.cmdFormat[2] = CommandButton(self, Caption='S', Left=100, Top=12, Width=40, Height=29,
                                          TabIndex=3,
                                          ToolTipText='Strikethrough (vpMarkdownStrikeThru)')
        self.cmdFormat[3] = CommandButton(self, Caption='Code', Left=142, Top=12, Width=56,
                                          Height=29, TabIndex=4,
                                          ToolTipText='Code (vpMarkdownCode)')
        self.cmdFormat[4] = CommandButton(self, Caption='H1', Left=206, Top=12, Width=40,
                                          Height=29, TabIndex=5,
                                          ToolTipText='A heading (vpMarkdownHeading1)')
        self.cmdFormat[5] = CommandButton(self, Caption='H2', Left=248, Top=12, Width=40,
                                          Height=29, TabIndex=6,
                                          ToolTipText='A heading (vpMarkdownHeading2)')
        self.cmdFormat[6] = CommandButton(self, Caption='H3', Left=290, Top=12, Width=40,
                                          Height=29, TabIndex=7,
                                          ToolTipText='A heading (vpMarkdownHeading3)')
        self.cmdFormat[7] = CommandButton(self, Caption='Text', Left=332, Top=12, Width=50,
                                          Height=29, TabIndex=8,
                                          ToolTipText='A plain paragraph (vpMarkdownParagraph)')
        self.cmdFormat[8] = CommandButton(self, Caption='- List', Left=390, Top=12, Width=70,
                                          Height=29, TabIndex=9,
                                          ToolTipText='A bulleted list (vpMarkdownBulletList)')
        self.cmdFormat[9] = CommandButton(self, Caption='1. List', Left=462, Top=12, Width=70,
                                          Height=29, TabIndex=10,
                                          ToolTipText='A numbered list (vpMarkdownNumberedList)')
        self.cmdFormat[10] = CommandButton(self, Caption='Quote', Left=534, Top=12, Width=70,
                                           Height=29, TabIndex=11,
                                           ToolTipText='A quote (vpMarkdownQuote)')
        self.lblSource = Label(self, Caption='Source', Left=16, Top=50, Width=196, Height=20,
                               FontBold=True, TabIndex=12)
        self.lblVisual = Label(self, Caption='Visual editor', Left=222, Top=50, Width=196,
                               Height=20, FontBold=True, TabIndex=13)
        self.lblPreview = Label(self, Caption='Preview', Left=428, Top=50, Width=196, Height=20,
                                FontBold=True, TabIndex=14)
        self.mdSource = MarkdownBox(self, Text='', Left=16, Top=72, Width=196, Height=330,
                                    TabIndex=15,
                                    ToolTipText='Mode = vpMarkdownSource: the Markdown, colored')
        self.mdVisual = MarkdownBox(self, Mode=1, Text='', Left=222, Top=72, Width=196, Height=330,
                                    TabIndex=16,
                                    ToolTipText='Mode = vpMarkdownVisual: edited as it reads')
        self.mdPreview = MarkdownBox(self, Mode=2, Text='', Left=428, Top=72, Width=196,
                                     Height=330, TabIndex=17,
                                     ToolTipText='Mode = vpMarkdownPreview: rendered, read-only')
        self.lblStatus = Label(self, Caption='', Left=16, Top=410, Width=608, Height=22,
                               TabIndex=18)
    # endregion

    def Form_Load(self):
        self.syncing = False
        self.editor = self.mdSource  # the editor the buttons format (the one used last)
        self.mdSource.Text = SAMPLE  # (its Change event shows it in the other two)

    # --- keeping the three in step -------------------------------------------------------------
    def show_everywhere(self, changed):
        """The Markdown of the box that changed, in the other two (each Change sets
        the others' Text, which fires their Change too: syncing stops it there)."""
        if self.syncing:
            return
        self.syncing = True
        try:
            for box in (self.mdSource, self.mdVisual, self.mdPreview):
                if box is not changed:
                    box.Text = changed.Text
        finally:
            self.syncing = False

    def mdSource_Change(self):
        self.show_everywhere(self.mdSource)

    def mdVisual_Change(self):
        self.show_everywhere(self.mdVisual)

    def mdPreview_Change(self):
        words = len(self.mdPreview.Text.split())
        self.lblStatus.Caption = f"{words} words of Markdown, {self.mdSource.LineCount} lines"

    # --- formatting ------------------------------------------------------------------------------
    def mdSource_GotFocus(self):
        self.editor = self.mdSource

    def mdVisual_GotFocus(self):
        self.editor = self.mdVisual

    def cmdFormat_Click(self, Index):
        self.editor.ApplyFormat(FORMATS[Index])  # (the same again undoes it)
        self.editor.SetFocus()

    # --- links ------------------------------------------------------------------------------------
    def mdPreview_LinkClick(self, URL):
        # Without this handler, the browser would open the link
        self.lblStatus.Caption = f"LinkClick: {URL}"


if __name__ == "__main__":
    run(pgMarkdown)
