"""Kitchen Sink page: MDI forms (the Notes window, frmMDI, and its note forms,
frmNote) and a popup form (frmSuggest, ShowPopup) listing suggestions under a
TextBox that keeps the focus: Up and Down choose, Enter takes, Esc hides."""

from vp6 import *
from frmMDI import frmMDI
from frmSuggest import frmSuggest

FRUITS = ("Apple", "Apricot", "Avocado", "Banana", "Blackberry", "Blueberry", "Cherry",
          "Clementine", "Coconut", "Cranberry", "Date", "Fig", "Grape", "Grapefruit", "Guava",
          "Kiwi", "Lemon", "Lime", "Lychee", "Mango", "Melon", "Nectarine", "Orange", "Papaya",
          "Peach", "Pear", "Pineapple", "Plum", "Pomegranate", "Raspberry", "Strawberry")


class pgMDI(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'MDI and popup forms'
        self.Width = 640
        self.Height = 440
        self.fraMDI = Frame(self, Caption='MDI forms', Left=16, Top=16, Width=608, Height=150,
                            TabIndex=1)
        self.lblMDI = Label(self.fraMDI,
                            Caption="An MDI form (MDIForm) is a window for child forms (MDIChild = True): the notes open inside it, its Window menu lists them (WindowList) and arranges them, and the active note's menu replaces its own.",
                            Left=12, Top=24, Width=584, Height=64, WordWrap=True, TabIndex=2)
        self.cmdOpenMDI = CommandButton(self.fraMDI, Caption='&Open the Notes window', Left=12,
                                        Top=100, Width=200, Height=32, TabIndex=3)
        self.fraPopup = Frame(self, Caption='A popup form', Left=16, Top=180, Width=608,
                              Height=180, TabIndex=4)
        self.lblPopup = Label(self.fraPopup,
                              Caption='Type a fruit: a popup form (ShowPopup) lists suggestions under the box without taking the focus. Up and Down choose, Enter takes one, Esc hides the list.',
                              Left=12, Top=24, Width=584, Height=44, WordWrap=True, TabIndex=5)
        self.txtFruit = TextBox(self.fraPopup, Text='', Left=12, Top=76, Width=200, Height=25,
                                TabIndex=6)
        self.lblChosen = Label(self.fraPopup, Caption='', Left=230, Top=80, Width=360, Height=25,
                               TabIndex=7)
    # endregion

    def Form_Load(self):
        frmSuggest.chosen = self.take

    def Form_Deactivate(self):
        frmSuggest.Hide()  # (another page: the list goes too)

    def cmdOpenMDI_Click(self):
        frmMDI.Show()  # its MDIForm_Load opens two notes

    # --- the popup -----------------------------------------------------------------------
    def txtFruit_Change(self):
        typed = self.txtFruit.Text.strip().lower()
        matches = [fruit for fruit in FRUITS if typed and fruit.lower().startswith(typed)]
        if not matches:
            frmSuggest.Hide()
            return
        frmSuggest.fill(matches)
        # Under the TextBox: X, Y in this page's client area (the Frame's position added)
        frmSuggest.ShowPopup(self.fraPopup.Left + self.txtFruit.Left,
                             self.fraPopup.Top + self.txtFruit.Top + self.txtFruit.Height,
                             self)

    def txtFruit_KeyDown(self, KeyCode, Shift):
        if not frmSuggest.Visible:
            return
        if KeyCode == vpKeyDown:
            frmSuggest.move(1)
        elif KeyCode == vpKeyUp:
            frmSuggest.move(-1)
        elif KeyCode == vpKeyReturn:
            self.take(frmSuggest.lstChoices.Text)
        elif KeyCode == vpKeyEscape:
            frmSuggest.Hide()

    def take(self, fruit):
        self.txtFruit.Text = fruit  # (its Change shows the list again: hidden after)
        frmSuggest.Hide()
        self.txtFruit.SelStart = len(fruit)
        self.lblChosen.Caption = f"Chosen: {fruit}"


if __name__ == "__main__":
    run(pgMDI)
