"""Kitchen Sink page: menus, a menu control array grown at run time, and a popup menu
(PopupMenu) for a right-click."""

from vp6 import *


class pgMenus(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Menus'
        self.Width = 640
        self.Height = 440
        self.lblMenus = Label(self, TextFormat=2,
                              Caption="The window's menus are **Menu** controls, designed with the **Menu Editor** (Tools > Menu Editor, Ctrl+E):\n\n- *File*: **End** has a Shortcut (Ctrl+Q)\n- *View*: a checked item, and the color schemes as a **menu control array**\n- *Bookmarks*: a menu control array too: add a page to it below (`Load` at run time)\n- *Help*: **Keys** has the Shortcut F1\n- *Page*: this page's own menu. A form shown in another form has no menu bar of its own: its menus join the window's while it is visible (**NegotiatePosition** = Right; Help is Right too, so it stays last)",
                              Left=16, Top=16, Width=600, Height=230, WordWrap=True, TabIndex=1)
        self.cboPages = ComboBox(self, Style=2, Left=16, Top=260, Width=240, Height=25, TabIndex=2)
        self.cmdBookmark = CommandButton(self, Caption='Add a &bookmark', Left=270, Top=258,
                                         Width=170, Height=30, TabIndex=3)
        self.lblPage = Label(self, Caption='', Left=16, Top=300, Width=600, Height=25, TabIndex=4)
        self.lblPopup = Label(self,
                              Caption='Right-click here for a popup menu (PopupMenu in MouseUp)',
                              Left=16, Top=340, Width=400, Height=40, Alignment=2, BorderStyle=1,
                              TabIndex=5)
        self.cmdPopup = CommandButton(self, Caption='&Menu below', Left=430, Top=340, Width=150,
                                      Height=40, TabIndex=6,
                                      ToolTipText='PopupMenu at a place: centered under the button')
        self.mnuPage = Menu(self, Caption='&Page', NegotiatePosition=3)
        self.mnuPageHello = Menu(self.mnuPage, Caption='&Say hello', Shortcut='Ctrl+H')
        self.mnuPopup = Menu(self, Caption='Popup', Visible=False)
        self.mnuPopupHello = Menu(self.mnuPopup, Caption='&Say hello')
        self.mnuPopupShout = Menu(self.mnuPopup, Caption='S&hout')
        self.mnuPopupSep = Menu(self.mnuPopup, Caption='-')
        self.mnuPopupClear = Menu(self.mnuPopup, Caption='&Clear')
    # endregion

    shell = None  # the Kitchen Sink window showing this page (None when run on its own)

    def Form_Load(self):
        self.pages = self.shell.page_titles() if self.shell is not None else []
        for _key, title in self.pages:
            self.cboPages.AddItem(title)
        if self.pages:
            self.cboPages.ListIndex = 0
        self.cmdBookmark.Enabled = bool(self.pages)

    def mnuPageHello_Click(self):
        # This page's own menu, on the window's menu bar while the page is visible
        self.lblPage.Caption = "Hello from the Menus page's own menu!"

    # --- a popup menu: a menu-bar menu made invisible, shown by PopupMenu -------------------
    def lblPopup_MouseUp(self, Button, Shift, X, Y):
        if Button == vpRightButton:
            # Where the mouse is; "Say hello" in bold (the default)
            chosen = self.PopupMenu(self.mnuPopup, DefaultMenu=self.mnuPopupHello)
            if chosen is None:
                self.lblPage.Caption = "The popup menu was closed without a choice"

    def cmdPopup_Click(self):
        button = self.cmdPopup  # centered under the button (X, Y in the form)
        self.PopupMenu(self.mnuPopup, vpPopupMenuCenterAlign, button.Left + button.Width // 2,
                       button.Top + button.Height)

    def mnuPopupHello_Click(self):
        self.lblPage.Caption = "Hello from the popup menu!"

    def mnuPopupShout_Click(self):
        self.lblPage.Caption = "HELLO FROM THE POPUP MENU!"

    def mnuPopupClear_Click(self):
        self.lblPage.Caption = ""

    def cmdBookmark_Click(self):
        key, title = self.pages[self.cboPages.ListIndex]
        self.shell.add_bookmark(key, title)


if __name__ == "__main__":
    run(pgMenus)
