"""Kitchen Sink page: menus, and a menu control array grown at run time."""

from vp6 import *


class pgMenus(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Menus'
        self.Width = 640
        self.Height = 440
        self.lblMenus = Label(self, TextFormat=2,
                              Caption="# Menus\n\nThe window's menus are **Menu** controls, designed with the **Menu Editor** (Tools > Menu Editor, Ctrl+E):\n\n- *File*: **End** has a Shortcut (Ctrl+Q)\n- *View*: a checked item, and the color schemes as a **menu control array**\n- *Bookmarks*: a menu control array too: add a page to it below (`Load` at run time)\n- *Help*: **Keys** has the Shortcut F1",
                              Left=16, Top=16, Width=600, Height=180, WordWrap=True, TabIndex=1)
        self.cboPages = ComboBox(self, Style=2, Left=16, Top=210, Width=240, Height=25, TabIndex=2)
        self.cmdBookmark = CommandButton(self, Caption='Add a &bookmark', Left=270, Top=208,
                                         Width=170, Height=30, TabIndex=3)
    # endregion

    shell = None  # the Kitchen Sink window showing this page (None when run on its own)

    def Form_Load(self):
        self.pages = self.shell.page_titles() if self.shell is not None else []
        for _key, title in self.pages:
            self.cboPages.AddItem(title)
        if self.pages:
            self.cboPages.ListIndex = 0
        self.cmdBookmark.Enabled = bool(self.pages)

    def cmdBookmark_Click(self):
        key, title = self.pages[self.cboPages.ListIndex]
        self.shell.add_bookmark(key, title)


if __name__ == "__main__":
    run(pgMenus)
