"""Kitchen Sink page: mouse events."""

from vp6 import *


class pgMouse(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Mouse'
        self.Width = 640
        self.Height = 440
        self.picPad = PictureBox(self, Left=16, Top=16, Width=300, Height=200, BackColor=0xF0F0F0,
                                 TabIndex=1)
        self.lblPad = Label(self.picPad,
                            Caption='Click, double-click or drag here with any button', Left=8,
                            Top=8, Width=284, Height=40, WordWrap=True, ForeColor=0x404040,
                            TabIndex=2)
        self.lblMouse = Label(self, Caption='', Left=330, Top=16, Width=290, Height=160,
                              WordWrap=True, TabIndex=3)
    # endregion

    def Form_MouseMove(self, Button, Shift, X, Y):
        self.lblMouse.Caption = f"Mouse at {X}, {Y} on the page"

    def picPad_MouseDown(self, Button, Shift, X, Y):
        names = [name for bit, name in ((vpLeftButton, "left"), (vpRightButton, "right"),
                                        (vpMiddleButton, "middle")) if Button & bit]
        self.lblMouse.Caption = f"{' + '.join(names)} button down at {X}, {Y}"

    def picPad_MouseMove(self, Button, Shift, X, Y):
        if Button:
            self.lblMouse.Caption = f"Dragging at {X}, {Y}"

    def picPad_MouseUp(self, Button, Shift, X, Y):
        self.lblMouse.Caption += " - released"

    def picPad_Click(self):
        self.lblPad.Caption = "Click"

    def picPad_DblClick(self):
        self.lblPad.Caption = "Double-click"


if __name__ == "__main__":
    run(pgMouse)
