"""Kitchen Sink page: PictureBox (a container) and Image (lightweight)."""

from vp6 import *


class pgPictures(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Pictures'
        self.Width = 640
        self.Height = 440
        self.picLogo = PictureBox(self, Left=16, Top=16, Width=240, Height=180, Picture='vp6.png',
                                  Stretch=True, TabIndex=1)
        self.lblOnPicture = Label(self.picLogo, Caption='Click to set a Tag', Left=12, Top=140,
                                  Width=216, Height=25, Alignment=2, BackColor=0xFFFFFF,
                                  ForeColor=0x000000, TabIndex=2,
                                  ToolTipText='An opaque Label (BackStyle = 1, the default): it hides the picture behind it')
        self.lblTransparent = Label(self.picLogo, Caption='Transparent label', Left=120, Top=8,
                                    Width=112, Height=20, Alignment=1, BackStyle=0,
                                    BackColor=0x000000, ForeColor=0xFFFFFF, TabIndex=3,
                                    ToolTipText='BackStyle = 0 (Transparent): the picture shows through; its BackColor (black) is ignored')
        self.imgThumb = Image(self, Left=270, Top=16, Width=64, Height=48, Stretch=True,
                              BorderStyle=1, Picture='vp6.png',
                              ToolTipText='An Image (a lightweight picture): click it')
        self.chkPicture = CheckBox(self, Caption='Show the big picture', Left=350, Top=28,
                                   Width=200, Height=25, Value=1, TabIndex=3)
        self.lblPicture = Label(self,
                                Caption='A PictureBox is a container (the Label is inside it); an Image is a lightweight picture. Right-click the picture.',
                                Left=270, Top=80, Width=350, Height=80, WordWrap=True, TabIndex=4)
    # endregion

    def picLogo_Click(self):
        self.lblPicture.Caption = f"PictureBox clicked (Tag: {self.picLogo.Tag or 'none'})"

    def picLogo_MouseDown(self, Button, Shift, X, Y):
        if Button == vpRightButton:
            self.lblPicture.Caption = f"Right button at {X}, {Y} on the picture"

    def lblOnPicture_Click(self):
        # A Label inside the PictureBox container
        tag = InputBox("A Tag for the picture:", "Tag", self.picLogo.Tag)
        if tag:
            self.picLogo.Tag = tag
            self.lblOnPicture.Caption = tag

    def imgThumb_Click(self):
        # The same picture scaled down (Stretch = True): shows or hides the big one
        self.chkPicture.Value = vpUnchecked if self.picLogo.Visible else vpChecked

    def chkPicture_Click(self):
        self.picLogo.Visible = self.chkPicture.Value == vpChecked


if __name__ == "__main__":
    run(pgPictures)
