"""Kitchen Sink page: running other programs. A Process control runs a small
Python program that answers what you send it (WriteLine): its Output and
ErrorOutput shown as they come, its exit code (Exited), a program that can't
be started (Error), Kill; and VB's Shell opening the project's folder."""

import sys

from vp6 import *

# The program the page talks with: it upper-cases each line, complains about
# "error" on its standard error, and ends with exit code 3 on "quit"
ECHO = ("import sys\n"
        "print('Ready: send me lines (error: to my standard error; quit: the end)', "
        "flush=True)\n"
        "for line in sys.stdin:\n"
        "    line = line.strip()\n"
        "    if line == 'quit':\n"
        "        sys.exit(3)\n"
        "    if line == 'error':\n"
        "        print('That was an error', file=sys.stderr, flush=True)\n"
        "        continue\n"
        "    print(line.upper(), flush=True)\n")


class pgProcess(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Running programs'
        self.Width = 640
        self.Height = 440
        self.cmdStart = CommandButton(self, Caption='&Start the program', Left=16, Top=16,
                                      Width=160, Height=30, TabIndex=1,
                                      ToolTipText='Process.Start: a Python program that answers')
        self.cmdKill = CommandButton(self, Caption='&Kill', Left=184, Top=16, Width=80, Height=30,
                                     Enabled=False, TabIndex=2, ToolTipText='Process.Kill')
        self.cmdMissing = CommandButton(self, Caption='Start a &missing one', Left=272, Top=16,
                                        Width=170, Height=30, TabIndex=3,
                                        ToolTipText="Its Error event: it can't be started")
        self.cmdShell = CommandButton(self, Caption='S&hell: the folder', Left=450, Top=16,
                                      Width=174, Height=30, TabIndex=4,
                                      ToolTipText="Shell: the project's folder in the system's file manager")
        self.txtOutput = TextBox(self, MultiLine=True, Text='', Left=16, Top=56, Width=608,
                                 Height=290, Locked=True, ScrollBars=2, TabIndex=5)
        self.txtSend = TextBox(self, Text='', Left=16, Top=358, Width=480, Height=25, TabIndex=6,
                               ToolTipText='A line for the program (Enter sends it)')
        self.cmdSend = CommandButton(self, Caption='Se&nd', Left=504, Top=356, Width=120,
                                     Height=30, Default=True, Enabled=False, TabIndex=7)
        self.lblStatus = Label(self, Caption='Not running', Left=16, Top=396, Width=608, Height=25,
                               TabIndex=8)
        self.prcEcho = Process(self, Left=588, Top=396)
    # endregion

    def show(self, text):
        self.txtOutput.SelStart = len(self.txtOutput.Text)
        self.txtOutput.SelText = text

    def set_running(self, running):
        # One program at a time for a Process (Start again while it runs: an error)
        self.cmdKill.Enabled = self.cmdSend.Enabled = running
        self.cmdStart.Enabled = self.cmdMissing.Enabled = not running

    def cmdStart_Click(self):
        self.txtOutput.Text = ""
        # A list: the program and its arguments as they are (no quoting needed)
        self.prcEcho.Start([sys.executable, "-u", "-c", ECHO])
        self.set_running(True)
        self.lblStatus.Caption = f"Running (process {self.prcEcho.ProcessID})"

    def cmdSend_Click(self):
        if self.prcEcho.Running:
            self.show(f"> {self.txtSend.Text}\n")
            self.prcEcho.WriteLine(self.txtSend.Text)  # to its standard input
            self.txtSend.Text = ""

    def cmdKill_Click(self):
        self.prcEcho.Kill()

    def cmdMissing_Click(self):
        self.prcEcho.Start("no-such-program --version")

    def cmdShell_Click(self):
        # Shell starts a program on its own: here the system's file manager
        opener = {"darwin": "open", "win32": "explorer"}.get(sys.platform, "xdg-open")
        pid = Shell([opener, App.Path], vpNormalFocus)
        self.lblStatus.Caption = f"Shell started {opener} (process {pid})"

    # --- the program's events ----------------------------------------------------------------
    def prcEcho_Output(self, Text):
        self.show(Text)  # what it prints, as it prints it

    def prcEcho_ErrorOutput(self, Text):
        self.show(f"[standard error] {Text}")

    def prcEcho_Exited(self, ExitCode):
        self.set_running(False)
        self.lblStatus.Caption = f"Exited with code {ExitCode}" + \
            (" (killed)" if ExitCode == -1 else "")

    def prcEcho_Error(self, Description):
        self.set_running(False)
        self.lblStatus.Caption = Description


if __name__ == "__main__":
    run(pgProcess)
