"""Kitchen Sink page: a RichTextBox as a small word processor (bold, italic, underline,
colors, sizes and alignment for the selection, kept in step by SelChange; Find; saving and
loading HTML) and a read-only one as a colored log (AppendText)."""

import os
import tempfile
import time

from vp6 import *

BLUE = RGB(30, 110, 255)  # (readable on light and dark backgrounds)
COLORS = (("Automatic", None), ("Red", vpRed), ("Green", RGB(0, 150, 0)), ("Blue", BLUE))
SIZES = (10, 12, 14, 18, 24)
SAVED = os.path.join(tempfile.gettempdir(), "vp6-kitchen-sink.html")
SAVED_TEXT = os.path.join(tempfile.gettempdir(), "vp6-kitchen-sink.txt")


class pgRichText(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'RichTextBox'
        self.Width = 640
        self.Height = 440
        self.chkBold = CheckBox(self, Caption='B', Left=16, Top=12, Width=32, Height=30, Style=1,
                                FontBold=True, TabIndex=1, ToolTipText='Bold (SelBold)')
        self.chkItalic = CheckBox(self, Caption='I', Left=50, Top=12, Width=32, Height=30, Style=1,
                                  FontItalic=True, TabIndex=2, ToolTipText='Italic (SelItalic)')
        self.chkUnderline = CheckBox(self, Caption='U', Left=84, Top=12, Width=32, Height=30,
                                     Style=1, FontUnderline=True, TabIndex=3,
                                     ToolTipText='Underline (SelUnderline)')
        self.cboColor = ComboBox(self, Style=2, Left=128, Top=14, Width=120, Height=25, TabIndex=4,
                                 ToolTipText='The text color (SelColor)')
        self.cboSize = ComboBox(self, Style=2, Left=256, Top=14, Width=70, Height=25, TabIndex=5,
                                ToolTipText='The text size (SelFontSize)')
        self.optAlign = ControlArray()
        self.optAlign[0] = OptionButton(self, Caption='Left', Left=338, Top=12, Width=60,
                                        Height=30, Value=True, Style=1, TabIndex=6,
                                        ToolTipText="The paragraphs' alignment (SelAlignment)")
        self.optAlign[1] = OptionButton(self, Caption='Center', Left=400, Top=12, Width=60,
                                        Height=30, Style=1, TabIndex=7,
                                        ToolTipText="The paragraphs' alignment (SelAlignment)")
        self.optAlign[2] = OptionButton(self, Caption='Right', Left=462, Top=12, Width=60,
                                        Height=30, Style=1, TabIndex=8,
                                        ToolTipText="The paragraphs' alignment (SelAlignment)")
        self.rtbDoc = RichTextBox(self, Text='', Left=16, Top=50, Width=608, Height=180,
                                  TabIndex=9,
                                  ToolTipText='Select some text and format it with the buttons above')
        self.txtFind = TextBox(self, Text='VP6', Left=16, Top=240, Width=150, Height=25,
                               TabIndex=10)
        self.cmdFind = CommandButton(self, Caption='&Find next', Left=174, Top=238, Width=100,
                                     Height=29, TabIndex=11)
        self.chkCase = CheckBox(self, Caption='&Match case', Left=282, Top=230, Width=130,
                                Height=22, TabIndex=17)
        self.chkWord = CheckBox(self, Caption='&Whole word', Left=282, Top=252, Width=130,
                                Height=22, TabIndex=18)
        self.cmdSave = CommandButton(self, Caption='&Save', Left=420, Top=238, Width=100,
                                     Height=29, TabIndex=12,
                                     ToolTipText='Save the text with its formatting, as HTML (SaveFile)')
        self.cmdLoad = CommandButton(self, Caption='&Load', Left=524, Top=238, Width=100,
                                     Height=29, Enabled=False, TabIndex=13,
                                     ToolTipText='Load what was saved (LoadFile)')
        self.lblStatus = Label(self, Caption='', Left=16, Top=274, Width=380, Height=22,
                               TabIndex=14)
        self.rtbLog = RichTextBox(self, Text='', Left=16, Top=302, Width=490, Height=120,
                                  Locked=True, TabIndex=15,
                                  ToolTipText='A read-only RichTextBox as a log: AppendText adds colored lines')
        self.cmdLog = CommandButton(self, Caption='&Add to log', Left=516, Top=302, Width=108,
                                    Height=29, TabIndex=16)
        self.lblCount = Label(self, Caption='', Left=400, Top=274, Width=224, Height=22,
                              Alignment=1, TabIndex=19)
    # endregion

    def Form_Load(self):
        self.syncing = True  # (filling the ComboBoxes clicks them: not a format yet)
        self.log_lines = 0
        for name, _color in COLORS:
            self.cboColor.AddItem(name)
        for size in SIZES:
            self.cboSize.AddItem(str(size))
        self.syncing = False
        # Formatted text, the VB way: put the cursor at the end, set the format, add text
        doc = self.rtbDoc
        doc.AppendText("A RichTextBox", Bold=True)
        doc.AppendText(" has text in ")
        doc.AppendText("colors", Color=vpRed)
        doc.AppendText(", ")
        doc.AppendText("bold", Bold=True)
        doc.AppendText(", ")
        doc.AppendText("italic", Italic=True)
        doc.AppendText(" and ")
        doc.AppendText("underlined", Underline=True)
        doc.AppendText(".\nSelect some of it and format it with the buttons above; "
                       "VP6 finds itself with Find.\n")
        doc.SelStart = len(doc.Text)
        doc.SelFontSize = 18
        doc.SelColor = BLUE
        doc.SelText = "A larger blue line, added with SelText"
        doc.SelStart = 0
        self.rtbDoc_SelChange()

    def rtbDoc_Change(self):
        text = self.rtbDoc.Text
        self.lblCount.Caption = f"{len(text.split())} words, {len(text)} characters"

    # --- the selection's format ------------------------------------------------------------
    def rtbDoc_SelChange(self):
        # Show the selection's format on the buttons (None: mixed, like VB's Null)
        doc = self.rtbDoc
        self.syncing = True
        self.chkBold.Value = vpChecked if doc.SelBold else vpUnchecked
        self.chkItalic.Value = vpChecked if doc.SelItalic else vpUnchecked
        self.chkUnderline.Value = vpChecked if doc.SelUnderline else vpUnchecked
        colors = [color for _name, color in COLORS]
        color = doc.SelColor if doc.SelColor in colors[1:] else None
        self.cboColor.ListIndex = colors.index(color)
        size = doc.SelFontSize
        self.cboSize.ListIndex = SIZES.index(size) if size in SIZES else -1
        if doc.SelAlignment is not None:  # (the buttons: Left, Center, Right)
            self.optAlign[(vpLeftJustify, vpCenter, vpRightJustify).index(doc.SelAlignment)
                          ].Value = True
        self.syncing = False
        line = doc.GetLineFromChar(doc.SelStart) + 1
        self.lblStatus.Caption = (f"Line {line}, position {doc.SelStart}, "
                                  f"{doc.SelLength} selected")

    def chkBold_Click(self):
        if not self.syncing:
            self.rtbDoc.SelBold = self.chkBold.Value == vpChecked
            self.rtbDoc.SetFocus()

    def chkItalic_Click(self):
        if not self.syncing:
            self.rtbDoc.SelItalic = self.chkItalic.Value == vpChecked
            self.rtbDoc.SetFocus()

    def chkUnderline_Click(self):
        if not self.syncing:
            self.rtbDoc.SelUnderline = self.chkUnderline.Value == vpChecked
            self.rtbDoc.SetFocus()

    def cboColor_Click(self):
        if not self.syncing:
            self.rtbDoc.SelColor = COLORS[self.cboColor.ListIndex][1]

    def cboSize_Click(self):
        if not self.syncing and self.cboSize.ListIndex >= 0:
            self.rtbDoc.SelFontSize = SIZES[self.cboSize.ListIndex]

    def optAlign_Click(self, Index):
        if not self.syncing:
            self.rtbDoc.SelAlignment = (vpLeftJustify, vpCenter, vpRightJustify)[Index]

    # --- Find, Save and Load -----------------------------------------------------------------
    def find_options(self) -> int:
        options = 0
        if self.chkCase.Value == vpChecked:
            options += vpRtfMatchCase
        if self.chkWord.Value == vpChecked:
            options += vpRtfWholeWord
        return options

    def cmdFind_Click(self):
        # Each Find starts after the selection; at the end, start over
        text, options = self.txtFind.Text, self.find_options()
        found = self.rtbDoc.Find(text, None, None, options)
        if found < 0:
            found = self.rtbDoc.Find(text, 0, None, options)
        # Count them all without selecting any (vpRtfNoHighlight)
        count, position = 0, self.rtbDoc.Find(text, 0, None, options + vpRtfNoHighlight)
        while position >= 0:
            count += 1
            position = self.rtbDoc.Find(text, position + 1, None, options + vpRtfNoHighlight)
        self.lblStatus.Caption = (f"Found at {found} ({count} in all)" if found >= 0 else
                                  f"{text!r} isn't there")

    def cmdSave_Click(self):
        self.rtbDoc.SaveFile(SAVED, vpRtfHTML)
        self.rtbDoc.SaveFile(SAVED_TEXT, vpRtfText)  # and the plain text beside it
        self.cmdLoad.Enabled = True
        self.lblStatus.Caption = f"Saved as HTML (and as text): {SAVED}"

    def cmdLoad_Click(self):
        self.rtbDoc.LoadFile(SAVED, vpRtfHTML)
        self.lblStatus.Caption = f"Loaded {SAVED}"

    # --- the log ------------------------------------------------------------------------------
    def cmdLog_Click(self):
        self.log_lines += 1
        kind, color = (("info", BLUE), ("warning", RGB(200, 120, 0)),
                       ("error", vpRed))[self.log_lines % 3]
        self.rtbLog.AppendText(time.strftime("%H:%M:%S "), Color=RGB(128, 128, 128))
        self.rtbLog.AppendText(kind.upper(), Color=color, Bold=True)
        self.rtbLog.AppendText(f" message {self.log_lines}\n")


if __name__ == "__main__":
    run(pgRichText)
