"""Kitchen Sink page: a page taller than the content pane, which scrolls."""

from vp6 import *


class pgScrolling(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Scrolling'
        self.Width = 640
        self.Height = 1000
        self.lblTop = Label(self, TextFormat=2,
                            Caption="# Scrolling\n\nThis page is **1000 pixels tall**. The content pane is a PictureBox with `ScrollBars = 3 - Both`: a scroll bar appears when what is in it doesn't fit. Scroll down (the status bar shows the pane's Scroll event).",
                            Left=16, Top=16, Width=600, Height=140, WordWrap=True, TabIndex=1)
        self.lblMiddle = Label(self, Caption='Halfway down', Left=16, Top=500, Width=300,
                               Height=25, TabIndex=2)
        self.cmdTop = CommandButton(self, Caption='Back to the &top', Left=16, Top=920, Width=180,
                                    Height=32, TabIndex=3,
                                    ToolTipText="Sets the content pane's ScrollTop to 0")
        self.lblBottom = Label(self, Caption='The bottom of the page', Left=210, Top=926,
                               Width=300, Height=25, TabIndex=4)
    # endregion

    shell = None  # the Kitchen Sink window showing this page (None when run on its own)

    def Form_Resize(self):
        self.lblTop.Width = max(self.ScaleWidth - 32, 100)

    def cmdTop_Click(self):
        if self.shell is not None:
            self.shell.picContent.ScrollTop = 0


if __name__ == "__main__":
    run(pgScrolling)
