"""Kitchen Sink page: light and dark color schemes."""

from vp6 import *

# The color scheme for each element of the optScheme control array, by Index
SCHEMES = (vpSchemeSystem, vpSchemeLight, vpSchemeDark, vpSchemeIDE)


class pgSchemes(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Color schemes'
        self.Width = 640
        self.Height = 440
        self.fraSchemes = Frame(self, Caption="This window's color scheme", Left=16, Top=16,
                                Width=260, Height=140, TabIndex=1)
        self.optScheme = ControlArray()
        self.optScheme[0] = OptionButton(self.fraSchemes, Caption='&System colors', Left=12,
                                         Top=28, Width=230, Height=25, Value=True, TabIndex=2)
        self.optScheme[1] = OptionButton(self.fraSchemes, Caption='&Light', Left=12, Top=54,
                                         Width=230, Height=25, TabIndex=3)
        self.optScheme[2] = OptionButton(self.fraSchemes, Caption='&Dark', Left=12, Top=80,
                                         Width=230, Height=25, TabIndex=4)
        self.optScheme[3] = OptionButton(self.fraSchemes, Caption='Follow the &IDE', Left=12,
                                         Top=106, Width=230, Height=25, TabIndex=5)
        self.lblSchemes = Label(self,
                                Caption='The scheme applies to the whole window (the View menu has the same choices). A form can also have its own: the modal dialog on the Dialogs page is always Dark.',
                                Left=290, Top=22, Width=330, Height=120, WordWrap=True, TabIndex=6)
    # endregion

    shell = None  # the Kitchen Sink window showing this page (None when run on its own)

    def optScheme_Click(self, Index):
        # optScheme is a control array: one handler for its four option buttons,
        # told apart by Index (also the element's place in SCHEMES)
        if self.shell is not None:
            self.shell.set_scheme(Index)
        else:
            self.ColorScheme = SCHEMES[Index]


if __name__ == "__main__":
    run(pgSchemes)
