"""Kitchen Sink page: HScrollBar and VScrollBar."""

from vp6 import *


class pgScrollBars(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Scroll bars'
        self.Width = 640
        self.Height = 440
        self.lblSize = Label(self, Caption='Font size:', Left=16, Top=20, Width=80, Height=25,
                             TabIndex=1)
        self.hsbSize = HScrollBar(self, Left=100, Top=24, Width=200, Height=17, Min=8, Max=24,
                                  Value=12, LargeChange=2, TabIndex=2)
        self.lblSizeValue = Label(self, Caption='12', Left=310, Top=20, Width=60, Height=25,
                                  TabIndex=3)
        self.lblSample = Label(self, Caption='Aa Bb Cc', Left=16, Top=60, Width=360, Height=70,
                               FontSize=12, TabIndex=4)
        self.vsbLevel = VScrollBar(self, Left=400, Top=16, Width=17, Height=200, Max=100, Value=50,
                                   LargeChange=10, TabIndex=5)
        self.lblLevel = Label(self, Caption='50', Left=426, Top=16, Width=60, Height=25,
                              TabIndex=6)
    # endregion

    def hsbSize_Change(self):
        self.lblSizeValue.Caption = str(self.hsbSize.Value)
        self.lblSample.FontSize = self.hsbSize.Value

    def hsbSize_Scroll(self):
        self.hsbSize_Change()  # update live while the thumb is dragged

    def vsbLevel_Change(self):
        self.lblLevel.Caption = str(self.vsbLevel.Value)

    def vsbLevel_Scroll(self):
        self.vsbLevel_Change()


if __name__ == "__main__":
    run(pgScrollBars)
