"""Kitchen Sink page: TabStrip."""

from vp6 import *

COLORS = (0x0000FF, 0x00C000, 0xFF0000)  # red, green, blue (VB's BGR order)


class pgTabs(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'TabStrip'
        self.Width = 640
        self.Height = 440
        self.tbsOptions = TabStrip(self, Left=16, Top=16, Width=440, Height=250,
                                   Tabs=['&General|general|Your name and a greeting', '&Colors|colors|Pick a color', '&About|about|What this page shows'],
                                   TabIndex=1)
        self.fraGeneral = Frame(self, Left=24, Top=56, Width=424, Height=200, TabIndex=2)
        self.lblName = Label(self.fraGeneral, Caption='Your name:', Left=16, Top=24, Width=90,
                             Height=25, TabIndex=3)
        self.txtName = TextBox(self.fraGeneral, Text='', Left=110, Top=20, Width=200, Height=25,
                               TabIndex=4)
        self.lblGreeting = Label(self.fraGeneral, Caption='Hello!', Left=16, Top=64, Width=380,
                                 Height=25, TabIndex=5)
        self.fraColors = Frame(self, Left=24, Top=56, Width=424, Height=200, TabIndex=6)
        self.optColor = ControlArray()
        self.optColor[0] = OptionButton(self.fraColors, Caption='Red', Left=16, Top=20, Width=100,
                                        Height=25, Value=True, TabIndex=7)
        self.optColor[1] = OptionButton(self.fraColors, Caption='Green', Left=16, Top=50,
                                        Width=100, Height=25, TabIndex=8)
        self.optColor[2] = OptionButton(self.fraColors, Caption='Blue', Left=16, Top=80, Width=100,
                                        Height=25, TabIndex=9)
        self.lblSwatch = Label(self.fraColors, Caption='', Left=140, Top=20, Width=120, Height=85,
                               BorderStyle=1, BackColor=0x0000FF, TabIndex=10)
        self.fraAbout = Frame(self, Left=24, Top=56, Width=424, Height=200, TabIndex=11)
        self.lblAbout = Label(self.fraAbout, TextFormat=2,
                              Caption="A **TabStrip** isn't a container: each tab has a Frame of its own, placed over the strip's client area (`ClientLeft`, `ClientTop`, `ClientWidth`, `ClientHeight`). Its `Click` event shows the Frame of the `SelectedItem`; returning `True` from `BeforeClick` keeps the current tab.",
                              Left=16, Top=16, Width=390, Height=160, WordWrap=True, TabIndex=12)
        self.chkLock = CheckBox(self, Caption='&Lock the tabs (BeforeClick returns True)', Left=16,
                                Top=280, Width=320, Height=25, TabIndex=13)
        self.lblPlacement = Label(self, Caption='Tabs on the:', Left=16, Top=316, Width=90,
                                  Height=25, TabIndex=14)
        self.cboPlacement = ComboBox(self, Style=2, Left=110, Top=316, Width=120, Height=25,
                                     List=['Top', 'Bottom', 'Left', 'Right'], Text='Top',
                                     TabIndex=15)
        self.lblEvent = Label(self, Caption='', Left=16, Top=356, Width=440, Height=25,
                              TabIndex=16)
    # endregion

    def Form_Load(self):
        self.frames = (self.fraGeneral, self.fraColors, self.fraAbout)  # in the tabs' order
        self.place_frames()
        self.show_tab()

    def place_frames(self):
        """Each tab's Frame covers the TabStrip's client area."""
        strip = self.tbsOptions
        for frame in self.frames:
            frame.Move(strip.ClientLeft + 4, strip.ClientTop + 4, strip.ClientWidth - 8,
                       strip.ClientHeight - 8)

    def show_tab(self):
        """Show the Frame of the selected tab, hide the others."""
        selected = self.tbsOptions.SelectedItem.Index  # from 1
        for number, frame in enumerate(self.frames, 1):
            frame.Visible = number == selected

    # --- the TabStrip ---------------------------------------------------------------------
    def tbsOptions_Click(self):
        # Another tab was chosen (by the user, or by code setting SelectedItem)
        self.show_tab()
        tab: Tab = self.tbsOptions.SelectedItem  # a Tab: Caption, Key, Index...
        self.lblEvent.Caption = f"Click: {tab.Caption.replace('&', '')} (key {tab.Key!r})"

    def tbsOptions_BeforeClick(self):
        # The user is choosing another tab: True keeps this one
        if self.chkLock.Value == vpChecked:
            self.lblEvent.Caption = "BeforeClick: the tabs are locked"
            return True

    def cboPlacement_Click(self):
        self.tbsOptions.Placement = self.cboPlacement.ListIndex  # vpTabPlacementTop...
        self.place_frames()  # the client area moved

    # --- what is on the tabs ------------------------------------------------------------------
    def txtName_Change(self):
        name = self.txtName.Text.strip()
        self.lblGreeting.Caption = f"Hello, {name}!" if name else "Hello!"

    def optColor_Click(self, Index):
        self.lblSwatch.BackColor = COLORS[Index]


if __name__ == "__main__":
    run(pgTabs)
