"""Kitchen Sink page: a Terminal running your shell (ANSI): type in it; the
demo button types a command that writes bold, underlined, inverse and colored
text and sets the terminal's title (TitleChange); Clear, Restart, and the
shell's end (Exited)."""

import sys

from vp6 import *

if sys.platform == "win32":  # (cmd.exe, without a pseudo-terminal there)
    DEMO = "echo The VP6 Terminal & ver\r"
else:
    DEMO = ("printf '\\033]0;VP6 Terminal\\007\\033[1mbold\\033[0m \\033[4munderlined\\033[0m "
            "\\033[7minverse\\033[0m'; for c in 31 32 33 34 35 36; do "
            "printf ' \\033[%sm color %s \\033[0m' $c $c; done; echo\r")


class pgTerminal(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Terminal'
        self.Width = 640
        self.Height = 440
        self.termShell = Terminal(self, Left=16, Top=16, Width=608, Height=340, TabIndex=1)
        self.cmdDemo = CommandButton(self, Caption='&Demo', Left=16, Top=366, Width=100, Height=30,
                                     TabIndex=2,
                                     ToolTipText='Write: types a command that writes colors')
        self.cmdClear = CommandButton(self, Caption='C&lear', Left=124, Top=366, Width=90,
                                      Height=30, TabIndex=3)
        self.cmdRestart = CommandButton(self, Caption='&Restart', Left=222, Top=366, Width=90,
                                        Height=30, TabIndex=4,
                                        ToolTipText='Kill the shell and start a new one')
        self.lblStatus = Label(self, Caption='', Left=320, Top=372, Width=304, Height=25,
                               TabIndex=5)
        self.lblHelp = Label(self,
                             Caption="It's a terminal: the shell gets your keys (Ctrl+C interrupts, Tab completes). Copy: Cmd+C on macOS, Ctrl+Shift+C elsewhere.",
                             Left=16, Top=402, Width=608, Height=30, WordWrap=True, TabIndex=6)
    # endregion

    def Form_Load(self):
        self.lblStatus.Caption = "Shell running" if self.termShell.Running else ""

    def cmdDemo_Click(self):
        if not self.termShell.Running:
            self.termShell.Start()
        self.termShell.Write(DEMO)  # as if typed: \r is Enter
        self.termShell.SetFocus()

    def cmdClear_Click(self):
        self.termShell.Clear()
        self.termShell.Write("\x0c" if sys.platform != "win32" else "cls\r")  # (a new prompt)
        self.termShell.SetFocus()

    def cmdRestart_Click(self):
        self.restart = True  # (started again in Exited, once the shell has gone)
        self.termShell.Clear()
        if self.termShell.Running:
            self.termShell.Kill()
        else:
            self.termShell_Exited(-1)

    def termShell_Exited(self, ExitCode):
        if getattr(self, "restart", False):
            self.restart = False
            self.termShell.Start()
            self.lblStatus.Caption = "Shell restarted"
        else:
            self.lblStatus.Caption = f"The shell ended ({ExitCode}): Restart starts it again"

    def termShell_TitleChange(self, Title):
        self.lblStatus.Caption = f"Title: {Title}"


if __name__ == "__main__":
    run(pgTerminal)
