"""Kitchen Sink page: Labels and TextBoxes."""

from vp6 import *


class pgText(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Text and labels'
        self.Width = 640
        self.Height = 440
        self.lblName = Label(self, Caption='&Name:', Left=16, Top=20, Width=70, Height=25,
                             TabIndex=1)
        self.txtName = TextBox(self, Text='', Left=90, Top=16, Width=200, Height=25, TabIndex=2,
                               ToolTipText='Type a name, then Greet (or press Enter)')
        self.cmdGreet = CommandButton(self, Caption='&Greet', Left=300, Top=14, Width=90,
                                      Height=30, Default=True, TabIndex=3,
                                      ToolTipText='The Default button: Enter clicks it')
        self.lblNotes = Label(self, Caption='Notes:', Left=16, Top=60, Width=70, Height=25,
                              TabIndex=4)
        self.txtNotes = TextBox(self, MultiLine=True,
                                Text='A multi-line\nTextBox with\na vertical scroll bar', Left=90,
                                Top=56, Width=300, Height=90, ScrollBars=2, TabIndex=5)
        self.lblPassword = Label(self, Caption='Password:', Left=16, Top=164, Width=70, Height=25,
                                 TabIndex=6)
        self.txtPassword = TextBox(self, Text='', Left=90, Top=160, Width=200, Height=25,
                                   PasswordChar='*', TabIndex=7)
        self.lblUpper = Label(self, Caption='UPPER:', Left=16, Top=200, Width=70, Height=25,
                              TabIndex=8)
        self.txtUpper = TextBox(self, Text='', Left=90, Top=196, Width=200, Height=25, TabIndex=9,
                                ToolTipText='KeyPress turns what you type into upper case')
        self.lblInfo = Label(self, Caption='', Left=16, Top=240, Width=380, Height=50,
                             WordWrap=True, TabIndex=10)
        self.fraAlign = Frame(self, Caption='Label alignment', Left=410, Top=16, Width=210,
                              Height=170, TabIndex=11)
        self.lblLeft = Label(self.fraAlign, Caption='Left Justify', Left=12, Top=28, Width=184,
                             Height=25, BorderStyle=1, TabIndex=12)
        self.lblCenter = Label(self.fraAlign, Caption='Center', Left=12, Top=60, Width=184,
                               Height=25, Alignment=2, BorderStyle=1, TabIndex=13)
        self.lblRight = Label(self.fraAlign, Caption='Right Justify', Left=12, Top=92, Width=184,
                              Height=25, Alignment=1, BorderStyle=1, TabIndex=14)
        self.lblAuto = Label(self.fraAlign, Caption='AutoSize fits me', Left=12, Top=128, Width=60,
                             Height=25, AutoSize=True, BackColor=0xC0FFFF, ForeColor=0x000000,
                             TabIndex=15)
    # endregion

    def fraAlign_Click(self):
        self.lblInfo.Caption = "Frames are containers; click events work on them too"

    def txtName_Change(self):
        self.lblInfo.Caption = f"Hello, {self.txtName.Text}!" if self.txtName.Text else ""

    def cmdGreet_Click(self):
        name = self.txtName.Text.strip()
        if not name:
            Beep()
            name = InputBox("What is your name?", "Greeting", "World")
            if not name:
                return
            self.txtName.Text = name
        MsgBox(f"Hello, {name}!", vpInformation, "Greeting")

    def txtNotes_GotFocus(self):
        self.lblInfo.Caption = "Editing the multi-line TextBox (GotFocus)"

    def txtPassword_LostFocus(self):
        self.lblInfo.Caption = f"The password has {len(self.txtPassword.Text)} characters (LostFocus)"

    def txtUpper_KeyPress(self, KeyAscii):
        # Returning a character code replaces the typed key (0 would swallow it)
        return ord(chr(KeyAscii).upper())


if __name__ == "__main__":
    run(pgText)
