"""Kitchen Sink page: a Timer that runs only while the page is visible."""

import time

from vp6 import *


class pgTimer(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Timer'
        self.Width = 640
        self.Height = 440
        self.lblClock = Label(self, Caption='00:00:00', Left=16, Top=16, Width=240, Height=40,
                              Alignment=2, FontSize=20, TabIndex=1)
        self.chkBold = CheckBox(self, Caption='&Bold clock', Left=16, Top=70, Width=160, Height=25,
                                TabIndex=2)
        self.chkTimer = CheckBox(self, Caption='Clock &running', Left=16, Top=96, Width=160,
                                 Height=25, Value=1, TabIndex=3)
        self.tmrClock = Timer(self, Left=280, Top=16, Interval=1000, Enabled=False)
        self.lblTimerInfo = Label(self,
                                  Caption='The Timer only runs while this page is visible: Form_Activate starts it and Form_Deactivate stops it.',
                                  Left=16, Top=140, Width=420, Height=60, WordWrap=True,
                                  TabIndex=4)
    # endregion

    def Form_Activate(self):
        # Shown in the content pane (a form in a container is activated there)
        self.tmrClock.Enabled = self.chkTimer.Value == vpChecked
        self.tmrClock_Timer()

    def Form_Deactivate(self):
        self.tmrClock.Enabled = False  # another page was chosen

    def tmrClock_Timer(self):
        self.lblClock.Caption = time.strftime("%H:%M:%S")

    def chkBold_Click(self):
        self.lblClock.FontBold = self.chkBold.Value == vpChecked

    def chkTimer_Click(self):
        self.tmrClock.Enabled = self.chkTimer.Value == vpChecked


if __name__ == "__main__":
    run(pgTimer)
