"""Kitchen Sink page: the TreeView's Nodes, check boxes and events."""

from vp6 import *


class pgTree(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'TreeView'
        self.Width = 640
        self.Height = 440
        self.tvwDemo = TreeView(self, Left=16, Top=16, Width=260, Height=300, Checkboxes=True,
                                Items=['Animals|animals', '    Cats|cats', '    Dogs|dogs', 'Plants|plants', '    Trees|trees'],
                                TabIndex=1)
        self.txtNode = TextBox(self, Text='New node', Left=290, Top=16, Width=160, Height=25,
                               TabIndex=2)
        self.cmdAddChild = CommandButton(self, Caption='Add a &child', Left=290, Top=50, Width=160,
                                         Height=30, TabIndex=3,
                                         ToolTipText='Nodes.Add(selected node, vpTvwChild, ...)')
        self.cmdRemove = CommandButton(self, Caption='&Remove', Left=290, Top=86, Width=160,
                                       Height=30, TabIndex=4)
        self.lblTree = Label(self,
                             Caption='The nodes were typed in the designer (Items); add more in code.',
                             Left=290, Top=130, Width=330, Height=120, WordWrap=True, TabIndex=5)
    # endregion

    def Form_Load(self):
        self.tvwDemo.Nodes("animals").Expanded = True

    def tvwDemo_NodeClick(self, Node):
        self.lblTree.Caption = (f"{Node.FullPath}: Index {Node.Index}, "
                                f"{Node.Children} children, key {Node.Key!r}")

    def tvwDemo_NodeCheck(self, Node):
        self.lblTree.Caption = f"{Node.Text} is {'checked' if Node.Checked else 'unchecked'}"

    def tvwDemo_Expand(self, Node):
        self.lblTree.Caption = f"Expanded {Node.Text}"

    def tvwDemo_Collapse(self, Node):
        self.lblTree.Caption = f"Collapsed {Node.Text}"

    def cmdAddChild_Click(self):
        parent = self.tvwDemo.SelectedItem
        text = self.txtNode.Text.strip() or "New node"
        if parent is None:
            node = self.tvwDemo.Nodes.Add(None, vpTvwLast, "", text)
        else:
            node = self.tvwDemo.Nodes.Add(parent, vpTvwChild, "", text)
        node.EnsureVisible()
        self.lblTree.Caption = f"Added {node.FullPath}"

    def cmdRemove_Click(self):
        node = self.tvwDemo.SelectedItem
        if node is not None:
            self.tvwDemo.Nodes.Remove(node)  # with its children
            self.lblTree.Caption = f"Removed {node.Text}"


if __name__ == "__main__":
    run(pgTree)
