"""Kitchen Sink page: your own controls. ctlRating (ctlRating.py, a user control of this
project, VB's UserControl) placed three times, with its own properties and its events
handled here."""

from vp6 import *
from ctlRating import ctlRating


class pgUserControl(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Your own controls'
        self.Width = 640
        self.Height = 440
        self.lblFood = Label(self, Caption='Food:', Left=16, Top=28, Width=80, Height=25,
                             TabIndex=1)
        self.rtgFood = ctlRating(self, Left=100, Top=20, Width=160, Height=36, TabIndex=2, Value=4)
        self.lblService = Label(self, Caption='Service:', Left=16, Top=76, Width=80, Height=25,
                                TabIndex=3)
        self.rtgService = ctlRating(self, Left=100, Top=68, Width=160, Height=36, TabIndex=4,
                                    Value=2, Max=3, StarColor=0xFF8040)
        self.lblFixed = Label(self, Caption='Critics:', Left=16, Top=124, Width=80, Height=25,
                              TabIndex=5)
        self.rtgFixed = ctlRating(self, Left=100, Top=116, Width=160, Height=36, TabIndex=6,
                                  StarColor=0x40C040, Locked=True)
        self.cmdReset = CommandButton(self, Caption='&Reset food', Left=300, Top=22, Width=120,
                                      Height=30, TabIndex=7,
                                      ToolTipText='Sets its Value from code: its Change event fires here too')
        self.lblAverage = Label(self, Caption='', Left=16, Top=170, Width=600, Height=25,
                                TabIndex=8)
        self.lblEvent = Label(self, Caption='', Left=16, Top=200, Width=600, Height=25, TabIndex=9)
        self.lblHow = Label(self,
                            Caption='ctlRating is a user control of this project (ctlRating.py): open it from the Project panel to design it like a form. Its Properties and Events are declared in its class; the stars on it are a control array of Labels.',
                            Left=16, Top=250, Width=600, Height=60, WordWrap=True, TabIndex=10)
    # endregion

    def Form_Load(self):
        self.show_average()

    def show_average(self):
        ratings = (self.rtgFood, self.rtgService, self.rtgFixed)
        score = sum(r.Value / r.Max for r in ratings) / len(ratings) * 5
        self.lblAverage.Caption = f"Average: {score:.1f} of 5 stars"

    # --- the user controls' events --------------------------------------------------------------
    def rtgFood_Change(self, Value):
        self.lblEvent.Caption = f"Food: {Value} stars (Change)"
        self.show_average()

    def rtgService_Change(self, Value):
        self.lblEvent.Caption = f"Service: {Value} of {self.rtgService.Max} stars (Change)"
        self.show_average()

    def rtgFood_Hover(self, Stars):
        self.lblEvent.Caption = f"Food: {Stars} stars? (Hover)"

    def cmdReset_Click(self):
        self.rtgFood.Value = 0  # its Change event comes here


if __name__ == "__main__":
    run(pgUserControl)
