"""Kitchen Sink page: Slider, ProgressBar and UpDown."""

from vp6 import *

PRICE = 4  # per copy
DAYS = ("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")


class pgValues(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Sliders, progress and spinners'
        self.Width = 640
        self.Height = 440
        self.lblVolume = Label(self, Caption='Volume:', Left=16, Top=20, Width=70, Height=25,
                               TabIndex=1)
        self.sldVolume = Slider(self, Left=90, Top=12, Width=260, Height=41, Max=100, Value=50,
                                LargeChange=10, TickFrequency=10, TabIndex=2,
                                ToolTipText='Drag the thumb, click beside it, or use the arrow keys')
        self.lblVolumeValue = Label(self, Caption='50', Left=360, Top=20, Width=60, Height=25,
                                    TabIndex=3)
        self.lblSliderEvent = Label(self,
                                    Caption='Drag the slider: Scroll while dragging, Change when you let go',
                                    Left=16, Top=60, Width=420, Height=25, TabIndex=4)
        self.prgLevel = ProgressBar(self, Left=460, Top=12, Width=25, Height=160, Value=50,
                                    Orientation=1,
                                    ToolTipText='A vertical ProgressBar following the slider')
        self.sldLevel = Slider(self, Left=500, Top=12, Width=45, Height=160, Max=100, Value=50,
                               LargeChange=25, Orientation=1, TickStyle=2, TickFrequency=25,
                               TabIndex=5, ToolTipText='A vertical Slider, ticks on both sides')
        self.cmdStart = CommandButton(self, Caption='Start', Left=16, Top=110, Width=97, Height=33,
                                      TabIndex=6)
        self.prgWork = ProgressBar(self, Left=124, Top=114, Width=300, Height=25,
                                   ToolTipText='Filled by a Timer, one step every 50 ms')
        self.lblWork = Label(self, Caption='', Left=16, Top=150, Width=420, Height=25, TabIndex=7)
        self.tmrWork = Timer(self, Left=440, Top=114, Interval=50, Enabled=False)
        self.lblCopies = Label(self, Caption='Copies:', Left=16, Top=210, Width=70, Height=25,
                               TabIndex=8)
        self.txtCopies = TextBox(self, Text='1', Left=90, Top=206, Width=48, Height=25, TabIndex=9,
                                 ToolTipText='Type a number: the next click starts from it')
        self.udCopies = UpDown(self, Left=138, Top=206, Width=17, Height=25, Min=1, Max=20,
                               Value=1, BuddyControl='txtCopies', SyncBuddy=True,
                               ToolTipText='1 to 20; hold a button down')
        self.lblTotal = Label(self, Caption='Total: 4 EUR', Left=170, Top=210, Width=200,
                              Height=25, TabIndex=10)
        self.lblDayCaption = Label(self, Caption='Day:', Left=16, Top=250, Width=70, Height=25,
                                   TabIndex=11)
        self.lblDay = Label(self, Caption='1', Left=90, Top=250, Width=30, Height=25, TabIndex=12)
        self.udDay = UpDown(self, Left=120, Top=248, Width=40, Height=25, Min=1, Max=7, Value=1,
                            Wrap=True, Orientation=0, BuddyControl='lblDay', SyncBuddy=True,
                            ToolTipText='Wraps around: after Sunday comes Monday again')
        self.lblDayName = Label(self, Caption='Monday', Left=170, Top=250, Width=200, Height=25,
                                TabIndex=13)
        self.lblUpDownEvent = Label(self, Caption='', Left=16, Top=290, Width=420, Height=25,
                                    TabIndex=14)
    # endregion

    # --- Slider -------------------------------------------------------------------------
    def sldVolume_Scroll(self):
        # While the thumb is dragged
        self.lblVolumeValue.Caption = str(self.sldVolume.Value)
        self.lblSliderEvent.Caption = f"Scroll: {self.sldVolume.Value}"

    def sldVolume_Change(self):
        # Once the value has changed (the drag ended, a key, a click, or code)
        self.lblVolumeValue.Caption = str(self.sldVolume.Value)
        self.lblSliderEvent.Caption = f"Change: the volume is now {self.sldVolume.Value}"

    def sldLevel_Scroll(self):
        self.prgLevel.Value = self.sldLevel.Value

    def sldLevel_Change(self):
        self.prgLevel.Value = self.sldLevel.Value

    # --- ProgressBar ---------------------------------------------------------------------
    def cmdStart_Click(self):
        self.prgWork.Value = self.prgWork.Min
        self.cmdStart.Enabled = False
        self.tmrWork.Enabled = True

    def tmrWork_Timer(self):
        self.prgWork.Value += 2
        self.lblWork.Caption = f"Working... {self.prgWork.Value} %"
        if self.prgWork.Value >= self.prgWork.Max:
            self.tmrWork.Enabled = False
            self.cmdStart.Enabled = True
            self.lblWork.Caption = "Done"

    def prgWork_Click(self):
        self.lblWork.Caption = f"The bar is at {self.prgWork.Value} of {self.prgWork.Max}"

    # --- UpDown --------------------------------------------------------------------------
    def udCopies_Change(self):
        # The buddy TextBox already shows the Value (SyncBuddy)
        self.lblTotal.Caption = f"Total: {self.udCopies.Value * PRICE} EUR"

    def udCopies_UpClick(self):
        self.lblUpDownEvent.Caption = "UpClick"

    def udCopies_DownClick(self):
        self.lblUpDownEvent.Caption = "DownClick"

    def udDay_Change(self):
        self.lblDayName.Caption = DAYS[self.udDay.Value - 1]


if __name__ == "__main__":
    run(pgValues)
