"""Kitchen Sink page: web pages, in a WebView (the platform's own web view) or a
WebBrowser (Qt WebEngine, Chromium): an address box, Back, Forward and Refresh, HTML of
its own (LoadHTML), JavaScript (RunScript), and their events (DocumentComplete,
TitleChange, ProgressChange, NavigateError; the WebBrowser's BeforeNavigate, NewWindow
and StatusTextChange)."""

from vp6 import *

WELCOME = """<html><head><title>Welcome</title>
<style>body { font-family: sans-serif; margin: 2em; color: #234; }</style></head>
<body><h1>A web page</h1>
<p>This page is HTML of the program's own (<code>LoadHTML</code>).
Type an address above, or follow a link:</p>
<ul><li><a href="https://www.python.org">python.org</a></li>
<li><a href="https://doc.qt.io/qtforpython-6/" target="_blank">Qt for Python</a>
(a new window: the WebBrowser's NewWindow)</li>
<li><a href="https://example.org">example.org</a> (the WebBrowser's BeforeNavigate
keeps it out)</li></ul>
</body></html>"""


class pgWeb(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Web pages'
        self.Width = 640
        self.Height = 440
        self.cmdBack = CommandButton(self, Caption='<', Left=16, Top=12, Width=36, Height=28,
                                     Enabled=False, TabIndex=1, ToolTipText='GoBack')
        self.cmdForward = CommandButton(self, Caption='>', Left=56, Top=12, Width=36, Height=28,
                                        Enabled=False, TabIndex=2, ToolTipText='GoForward')
        self.txtAddress = TextBox(self, Text='', Left=100, Top=13, Width=380, Height=25,
                                  TabIndex=3, ToolTipText='A web address, a domain or a file')
        self.cmdGo = CommandButton(self, Caption='&Go', Left=488, Top=12, Width=60, Height=28,
                                   Default=True, TabIndex=4, ToolTipText='Navigate')
        self.cmdRefresh = CommandButton(self, Caption='&Refresh', Left=552, Top=12, Width=72,
                                        Height=28, TabIndex=5)
        self.webPage = WebView(self, Left=16, Top=48, Width=608, Height=300, TabIndex=6)
        self.brwPage = WebBrowser(self, Left=16, Top=48, Width=608, Height=300, Visible=False,
                                  TabIndex=7)
        self.lblStatus = Label(self, Caption='', Left=16, Top=356, Width=608, Height=25,
                               TabIndex=8)
        self.optEngine = ControlArray()
        self.optEngine[0] = OptionButton(self, Caption="&WebView (the system's)", Left=16, Top=392,
                                         Width=180, Height=25, Value=True, TabIndex=9)
        self.optEngine[1] = OptionButton(self, Caption='Web&Browser (Chromium)', Left=200, Top=392,
                                         Width=180, Height=25, TabIndex=10)
        self.cmdHtml = CommandButton(self, Caption='Show &HTML', Left=388, Top=390, Width=110,
                                     Height=30, TabIndex=11,
                                     ToolTipText="LoadHTML: a page of the program's own")
        self.cmdScript = CommandButton(self, Caption='Run a &script', Left=506, Top=390, Width=118,
                                       Height=30, TabIndex=12,
                                       ToolTipText="RunScript: the page's JavaScript counts its links")
    # endregion

    def Form_Load(self):
        self.web = self.webPage  # the one shown
        self.webPage.LoadHTML(WELCOME)
        self.brwPage.LoadHTML(WELCOME)

    def optEngine_Click(self, Index):
        self.web = (self.webPage, self.brwPage)[Index]
        self.webPage.Visible, self.brwPage.Visible = Index == 0, Index == 1
        self.show_state(self.web.LocationURL)

    # --- going places ---------------------------------------------------------------------------
    def cmdGo_Click(self):
        if self.txtAddress.Text.strip():
            self.web.Navigate(self.txtAddress.Text)  # e.g. example.com: https:// added

    def cmdBack_Click(self):
        self.web.GoBack()

    def cmdForward_Click(self):
        self.web.GoForward()

    def cmdRefresh_Click(self):
        self.web.Refresh()

    def cmdHtml_Click(self):
        self.web.LoadHTML(WELCOME)

    def cmdScript_Click(self):
        # The result comes later, when the page has run the script
        self.web.RunScript("document.links.length", self.show_links)

    def show_links(self, count):
        self.lblStatus.Caption = f"RunScript: the page has {int(count or 0)} links"

    def show_state(self, URL):
        web = self.web
        if URL and not URL.startswith(("about:", "data:")):
            self.txtAddress.Text = URL
        self.cmdBack.Enabled = web.CanGoBack
        self.cmdForward.Enabled = web.CanGoForward
        self.lblStatus.Caption = f"Done: {web.LocationName or URL}"

    # --- the WebView's events ----------------------------------------------------------------
    def webPage_DocumentComplete(self, URL):
        if self.web is self.webPage:
            self.show_state(URL)

    def webPage_TitleChange(self, Text):
        if Text and self.web is self.webPage:
            self.lblStatus.Caption = f"Title: {Text}"

    def webPage_ProgressChange(self, Progress):
        if self.webPage.Busy:
            self.lblStatus.Caption = f"Loading... {Progress}%"

    def webPage_NavigateError(self, URL, Description):
        self.lblStatus.Caption = f"Couldn't open {URL}: {Description}"

    # --- the WebBrowser's events -------------------------------------------------------------
    def brwPage_DocumentComplete(self, URL):
        if self.web is self.brwPage:
            self.show_state(URL)

    def brwPage_ProgressChange(self, Progress):
        if self.brwPage.Busy:
            self.lblStatus.Caption = f"Loading... {Progress}%"

    def brwPage_NavigateError(self, URL, Description):
        self.lblStatus.Caption = f"Couldn't open {URL}: {Description}"

    def brwPage_BeforeNavigate(self, URL):
        # Returning True keeps it where it is
        if "example.org" in URL:
            self.lblStatus.Caption = f"BeforeNavigate kept the browser away from {URL}"
            return True
        return False

    def brwPage_NewWindow(self, URL):
        # A link opening a new window: here instead (return True to ignore it)
        self.lblStatus.Caption = f"NewWindow: {URL} (opened here)"

    def brwPage_StatusTextChange(self, Text):
        if Text:
            self.lblStatus.Caption = f"Link: {Text}"


if __name__ == "__main__":
    run(pgWeb)
