"""Kitchen Sink page: Line controls and the stacking order (ZIndex, ZOrder)."""

from vp6 import *


class pgZOrder(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Lines and z-order'
        self.Width = 640
        self.Height = 440
        self.lblZRed = Label(self, Caption='Red: ZIndex 2', Left=16, Top=16, Width=132, Height=40,
                             Alignment=2, BackColor=0x0000FF, ForeColor=0xFFFFFF, TabIndex=1,
                             ToolTipText='Click to bring to front (ZOrder 0)', ZIndex=2)
        self.lblZBlue = Label(self, Caption='Blue: ZIndex 1', Left=80, Top=28, Width=132,
                              Height=40, Alignment=2, BackColor=0xFF0000, ForeColor=0xFFFFFF,
                              TabIndex=2, ToolTipText='Click to bring to front (ZOrder 0)',
                              ZIndex=1)
        self.linZ = Line(self, X1=16, Y1=16, X2=212, Y2=68, BorderColor=0xFFFFFF, BorderStyle=2,
                         BorderWidth=2, ZIndex=3)
        self.cmdSwapZ = CommandButton(self, Caption='Swap &Z-order', Left=240, Top=24, Width=130,
                                      Height=32, TabIndex=3,
                                      ToolTipText="Swaps the two labels' ZIndex values")
        self.linSample = ControlArray()
        self.linSample[0] = Line(self, X1=16, Y1=110, X2=300, Y2=110)
        self.linSample[1] = Line(self, X1=16, Y1=130, X2=300, Y2=130)
        self.linSample[2] = Line(self, X1=16, Y1=150, X2=300, Y2=150)
        self.linSample[3] = Line(self, X1=16, Y1=170, X2=300, Y2=170)
        self.linSample[4] = Line(self, X1=16, Y1=190, X2=300, Y2=190)
        self.lblLines = Label(self, Caption='BorderStyle 1 to 5: a control array of Lines',
                              Left=316, Top=122, Width=300, Height=25, TabIndex=4)
        self.linThick = Line(self, X1=16, Y1=230, X2=300, Y2=290, BorderColor=0xC08000,
                             BorderWidth=5)
    # endregion

    def Form_Load(self):
        for line in self.linSample:  # Solid, Dash, Dot, Dash-Dot, Dash-Dot-Dot
            line.BorderStyle = line.Index + 1

    def cmdSwapZ_Click(self):
        # ZIndex: higher values are drawn on top, and changes apply at once. The
        # dashed Line linZ (ZIndex 3) is above both labels until ZOrder(0) brings
        # one in front of it; clicks go through a Line to what is underneath.
        self.lblZRed.ZIndex, self.lblZBlue.ZIndex = self.lblZBlue.ZIndex, self.lblZRed.ZIndex
        self.show_z_order()

    def lblZRed_Click(self):
        self.lblZRed.ZOrder(0)  # VB's ZOrder method: 0 = bring to front, 1 = send to back
        self.show_z_order()

    def lblZBlue_Click(self):
        self.lblZBlue.ZOrder(0)
        self.show_z_order()

    def show_z_order(self):
        self.lblZRed.Caption = f"Red: ZIndex {self.lblZRed.ZIndex}"
        self.lblZBlue.Caption = f"Blue: ZIndex {self.lblZBlue.ZIndex}"


if __name__ == "__main__":
    run(pgZOrder)
