"""Kitchen Sink page: Line and Shape controls and the stacking order (ZIndex, ZOrder)."""

from vp6 import *


class pgZOrder(Form):
    # region VP6 Designer - generated by the form designer, do not edit
    def InitializeComponent(self):
        self.Caption = 'Lines, shapes and z-order'
        self.Width = 640
        self.Height = 440
        self.lblZRed = Label(self, Caption='Red: ZIndex 2', Left=16, Top=16, Width=132, Height=40,
                             Alignment=2, BackColor=0x0000FF, ForeColor=0xFFFFFF, TabIndex=1,
                             ToolTipText='Click to bring to front (ZOrder 0)', ZIndex=2)
        self.lblZBlue = Label(self, Caption='Blue: ZIndex 1', Left=80, Top=28, Width=132,
                              Height=40, Alignment=2, BackColor=0xFF0000, ForeColor=0xFFFFFF,
                              TabIndex=2, ToolTipText='Click to bring to front (ZOrder 0)',
                              ZIndex=1)
        self.linZ = Line(self, X1=16, Y1=16, X2=212, Y2=68, BorderColor=0xFFFFFF, BorderStyle=2,
                         BorderWidth=2, ZIndex=3)
        self.cmdSwapZ = CommandButton(self, Caption='Swap &Z-order', Left=240, Top=24, Width=130,
                                      Height=32, TabIndex=3,
                                      ToolTipText="Swaps the two labels' ZIndex values")
        self.linSample = ControlArray()
        self.linSample[0] = Line(self, X1=16, Y1=110, X2=300, Y2=110)
        self.linSample[1] = Line(self, X1=16, Y1=130, X2=300, Y2=130)
        self.linSample[2] = Line(self, X1=16, Y1=150, X2=300, Y2=150)
        self.linSample[3] = Line(self, X1=16, Y1=170, X2=300, Y2=170)
        self.linSample[4] = Line(self, X1=16, Y1=190, X2=300, Y2=190)
        self.lblLines = Label(self, Caption='BorderStyle 1 to 5: a control array of Lines',
                              Left=316, Top=122, Width=300, Height=25, TabIndex=4)
        self.linThick = Line(self, X1=16, Y1=230, X2=300, Y2=290, BorderColor=0xC08000,
                             BorderWidth=5)
        self.cboShape = ComboBox(self, Style=2, Left=326, Top=180, Width=150, Height=25,
                                 List=['Rectangle', 'Square', 'Oval', 'Circle', 'Rounded Rectangle', 'Rounded Square'],
                                 TabIndex=5, ToolTipText="The Shape's Shape")
        self.cboFill = ComboBox(self, Style=2, Left=326, Top=212, Width=150, Height=25,
                                List=['Solid', 'Transparent', 'Horizontal Line', 'Vertical Line', 'Upward Diagonal', 'Downward Diagonal', 'Cross', 'Diagonal Cross'],
                                TabIndex=6, ToolTipText='Its FillStyle (in its FillColor)')
        self.chkOpaque = CheckBox(self, Caption='&Opaque', Left=330, Top=244, Width=140, Height=25,
                                  TabIndex=7,
                                  ToolTipText='BackStyle: Opaque fills it with its BackColor first')
        self.shpSample = Shape(self, Left=484, Top=176, Width=136, Height=100, Shape=4,
                               BackColor=0xA8F2FF, FillStyle=7, FillColor=0x0080C0,
                               BorderColor=0x0080C0, BorderWidth=3)
        self.shpKinds = ControlArray()
        self.shpKinds[0] = Shape(self, Left=16, Top=320, Width=90, Height=70, FillStyle=0)
        self.shpKinds[1] = Shape(self, Left=118, Top=320, Width=90, Height=70, FillStyle=0)
        self.shpKinds[2] = Shape(self, Left=220, Top=320, Width=90, Height=70, FillStyle=0)
        self.shpKinds[3] = Shape(self, Left=322, Top=320, Width=90, Height=70, FillStyle=0)
        self.shpKinds[4] = Shape(self, Left=424, Top=320, Width=90, Height=70, FillStyle=0)
        self.shpKinds[5] = Shape(self, Left=526, Top=320, Width=90, Height=70, FillStyle=0)
    # endregion

    def Form_Load(self):
        for line in self.linSample:  # Solid, Dash, Dot, Dash-Dot, Dash-Dot-Dot
            line.BorderStyle = line.Index + 1
        # Every kind of Shape, each in a color of its own (QBColor 9-14)
        for shape in self.shpKinds:
            shape.Shape = shape.Index  # vpShapeRectangle ... vpShapeRoundedSquare
            shape.FillColor = QBColor(9 + shape.Index)
            shape.BorderStyle = vpBSInsideSolid
        self.cboShape.ListIndex = vpShapeRoundedRectangle
        self.cboFill.ListIndex = vpDiagonalCross

    def cboShape_Click(self):
        self.shpSample.Shape = self.cboShape.ListIndex

    def cboFill_Click(self):
        self.shpSample.FillStyle = self.cboFill.ListIndex

    def chkOpaque_Click(self):
        self.shpSample.BackStyle = vpOpaque if self.chkOpaque.Value == vpChecked else \
            vpTransparent

    def cmdSwapZ_Click(self):
        # ZIndex: higher values are drawn on top, and changes apply at once. The
        # dashed Line linZ (ZIndex 3) is above both labels until ZOrder(0) brings
        # one in front of it; clicks go through a Line to what is underneath.
        self.lblZRed.ZIndex, self.lblZBlue.ZIndex = self.lblZBlue.ZIndex, self.lblZRed.ZIndex
        self.show_z_order()

    def lblZRed_Click(self):
        self.lblZRed.ZOrder(0)  # VB's ZOrder method: 0 = bring to front, 1 = send to back
        self.show_z_order()

    def lblZBlue_Click(self):
        self.lblZBlue.ZOrder(0)
        self.show_z_order()

    def show_z_order(self):
        self.lblZRed.Caption = f"Red: ZIndex {self.lblZRed.ZIndex}"
        self.lblZBlue.Caption = f"Blue: ZIndex {self.lblZBlue.ZIndex}"


if __name__ == "__main__":
    run(pgZOrder)
